/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Applications */
        get: operations["applications_api_v1_applications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Application */
        get: operations["application_api_v1_applications__application_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/access-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access Sessions */
        get: operations["access_sessions_api_v1_applications__application_id__access_sessions_get"];
        put?: never;
        /** Start Access */
        post: operations["start_access_api_v1_applications__application_id__access_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/access-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access Session */
        get: operations["access_session_api_v1_applications__application_id__access_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Stop Access */
        delete: operations["stop_access_api_v1_applications__application_id__access_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/evaluation-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluation Preview */
        post: operations["evaluation_preview_api_v1_applications__application_id__evaluation_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_v1_applications__application_id__evaluations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation List */
        get: operations["operation_list_api_v1_applications__application_id__operations_get"];
        put?: never;
        /** Admit */
        post: operations["admit_api_v1_applications__application_id__operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Releases */
        get: operations["releases_api_v1_applications__application_id__releases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/remote-access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Remote Access */
        get: operations["list_remote_access_api_v1_applications__application_id__remote_access_get"];
        put?: never;
        /** Issue Remote Access */
        post: operations["issue_remote_access_api_v1_applications__application_id__remote_access_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/remote-access/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remote Access Ticket */
        get: operations["remote_access_ticket_api_v1_applications__application_id__remote_access__ticket_id__get"];
        put?: never;
        post?: never;
        /** Stop Remote Access */
        delete: operations["stop_remote_access_api_v1_applications__application_id__remote_access__ticket_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resources */
        get: operations["resources_api_v1_applications__application_id__resources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/resources/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resource */
        get: operations["resource_api_v1_applications__application_id__resources__resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/resources/{resource_id}/log-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log Sources */
        get: operations["log_sources_api_v1_applications__application_id__resources__resource_id__log_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/applications/{application_id}/resources/{resource_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Logs */
        get: operations["read_logs_api_v1_applications__application_id__resources__resource_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Environments */
        get: operations["environments_api_v1_environments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/environments/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Environment Action */
        post: operations["environment_action_api_v1_environments_actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluations/{evaluation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation */
        get: operations["evaluation_api_v1_evaluations__evaluation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Events
         * @description Scoped replay with a bounded per-client window and explicit reset.
         */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gitops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Gitops */
        get: operations["gitops_api_v1_gitops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gitops/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gitops Approval */
        post: operations["gitops_approval_api_v1_gitops_approvals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gitops/promotions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gitops Promotion */
        post: operations["gitops_promotion_api_v1_gitops_promotions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observation-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Observation Events
         * @description Transient scoped watch notifications; reset after replay loss.
         */
        get: operations["observation_events_api_v1_observation_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schema */
        get: operations["schema_api_v1_openapi_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Operation */
        get: operations["operation_api_v1_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_operations__operation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/{operation_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_operations__operation_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plan */
        get: operations["plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remote-access/{ticket_id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim Remote Access */
        post: operations["claim_remote_access_api_v1_remote_access__ticket_id__claim_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remote-access/{ticket_id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Remote Access Heartbeat */
        post: operations["remote_access_heartbeat_api_v1_remote_access__ticket_id__heartbeat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/remote-access/{ticket_id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release Remote Access */
        post: operations["release_remote_access_api_v1_remote_access__ticket_id__release_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessPage */
        AccessPage: {
            /** Items */
            items: components["schemas"]["AccessSession"][];
        };
        /** AccessSession */
        AccessSession: {
            /** Application Id */
            application_id: string;
            /**
             * Binding Location
             * @enum {string}
             */
            binding_location: "local_client" | "server" | "gateway";
            /** Endpoint */
            endpoint?: string | null;
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /** Local Port */
            local_port?: number | null;
            /** Principal Id */
            principal_id: string;
            /** Reason */
            reason?: string | null;
            /** Remote Port */
            remote_port?: number | null;
            resource: components["schemas"]["ResourceIdentity"];
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "connecting" | "ready" | "failed" | "stopped" | "expired";
        };
        /** AccessStartRequest */
        AccessStartRequest: {
            /**
             * Duration Seconds
             * @default 900
             */
            duration_seconds: number;
            /** Local Port */
            local_port: number;
            /** Remote Port */
            remote_port: number;
            /** Resource Id */
            resource_id: string;
            /** Resource Uid */
            resource_uid: string;
        };
        /** Application */
        Application: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["Capability"];
            };
            /**
             * Definition Kind
             * @enum {string}
             */
            definition_kind: "inventory" | "release" | "pipeline";
            freshness: components["schemas"]["Freshness"];
            /**
             * Health
             * @default unknown
             * @enum {string}
             */
            health: "healthy" | "progressing" | "degraded" | "suspended" | "unknown";
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Operation
             * @default idle
             */
            operation: string;
            /**
             * Ownership
             * @enum {string}
             */
            ownership: "native" | "external" | "inventory";
            /**
             * Relation
             * @default unknown
             * @enum {string}
             */
            relation: "in_sync" | "changes" | "drifted" | "unknown" | "external";
            source?: components["schemas"]["SourceRevision"] | null;
            target: components["schemas"]["Target"];
        };
        /** ApplicationPage */
        ApplicationPage: {
            /** Cursor */
            cursor: string;
            /** Items */
            items: components["schemas"]["Application"][];
            /** Next Page */
            next_page?: string | null;
        };
        /** CancelRequest */
        CancelRequest: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Actions */
            actions: {
                [key: string]: components["schemas"]["Capability"];
            };
            /**
             * Api Version
             * @default piceli.ui.v1
             * @constant
             */
            api_version: "piceli.ui.v1";
            /**
             * Mode
             * @default local
             * @enum {string}
             */
            mode: "local" | "cluster";
            principal: components["schemas"]["Principal"];
            /** Targets */
            targets: components["schemas"]["Target"][];
        };
        /** Capability */
        Capability: {
            /** Allowed */
            allowed: boolean;
            /** Reason */
            reason?: string | null;
        };
        /** EnvironmentActionRequest */
        EnvironmentActionRequest: {
            /** Approved Hash */
            approved_hash?: string | null;
            /** Branch */
            branch: string;
            /** Source */
            source?: string | null;
            /**
             * Verb
             * @enum {string}
             */
            verb: "up" | "down" | "seed";
        };
        /** Evaluation */
        Evaluation: {
            /** Application Id */
            application_id: string;
            /** Created At */
            created_at?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Id */
            id: string;
            /** Plan Id */
            plan_id?: string | null;
            /** Preview Id */
            preview_id?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "interrupted";
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * EvaluationPreview
         * @description Exact authorization to evaluate a frozen source without deployment credentials.
         */
        EvaluationPreview: {
            /** Application Id */
            application_id: string;
            /** Digest */
            digest: string;
            /** Expires At */
            expires_at: string;
            /** Files */
            files: string[];
            /** Id */
            id: string;
            /** Input Digest */
            input_digest: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "deploy" | "rollback";
            /** Limits */
            limits: {
                [key: string]: number;
            };
            /** Release */
            release?: string | null;
            /** Renderer Digest */
            renderer_digest: string;
            source: components["schemas"]["SourceRevision"];
            /** Warnings */
            warnings?: string[];
        };
        /** EvaluationRequest */
        EvaluationRequest: {
            /** Approved Digest */
            approved_digest: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Preview Id */
            preview_id: string;
        };
        /** FieldChange */
        FieldChange: {
            after?: components["schemas"]["JsonValue"];
            before?: components["schemas"]["JsonValue"];
            /**
             * Op
             * @enum {string}
             */
            op: "add" | "remove" | "replace";
            /** Path */
            path: string;
        };
        /** Freshness */
        Freshness: {
            /** Observed At */
            observed_at?: string | null;
            /** Reason */
            reason?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "connected" | "reconnecting" | "stale" | "unavailable";
        };
        /** GitOpsApprovalRequest */
        GitOpsApprovalRequest: {
            /** Branch */
            branch: string;
            /** Plan Hash */
            plan_hash: string;
        };
        /** GitOpsPromotionRequest */
        GitOpsPromotionRequest: {
            /** Branch */
            branch: string;
            /** Commit */
            commit: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        JsonValue: unknown;
        /** LogBatch */
        LogBatch: {
            /** Cursor */
            cursor: string;
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
            /**
             * Gap
             * @default false
             */
            gap: boolean;
            /** Lines */
            lines: string[];
        };
        /** LogSource */
        LogSource: {
            /** Containers */
            containers: string[];
            /** Phase */
            phase?: string | null;
            pod: components["schemas"]["ResourceIdentity"];
            /** Started At */
            started_at?: string | null;
        };
        /** LogSourcePage */
        LogSourcePage: {
            freshness: components["schemas"]["Freshness"];
            /** Items */
            items: components["schemas"]["LogSource"][];
            /** Partial */
            partial?: components["schemas"]["PartialError"][];
        };
        /** Operation */
        Operation: {
            /** Actor */
            actor: string;
            /** Application Id */
            application_id: string;
            /** Approved Digest */
            approved_digest: string;
            /**
             * Attempt
             * @default 1
             */
            attempt: number;
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["Capability"];
            };
            /**
             * Checks Outcome
             * @default unknown
             * @enum {string}
             */
            checks_outcome: "unknown" | "succeeded" | "failed" | "not_configured";
            /** Created At */
            created_at: string;
            /**
             * Deployment Outcome
             * @default unknown
             * @enum {string}
             */
            deployment_outcome: "unknown" | "succeeded" | "failed";
            /** Engine Execution Id */
            engine_execution_id?: string | null;
            /** Engine Release */
            engine_release?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Id */
            id: string;
            /** Pipeline Run Id */
            pipeline_run_id?: string | null;
            /** Plan Id */
            plan_id: string;
            /** Receipts */
            receipts?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Recovery Of */
            recovery_of?: string | null;
            /** Stages */
            stages?: components["schemas"]["Stage"][];
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "succeeded" | "failed" | "interrupted" | "cancelling" | "cancelled";
            /**
             * Trigger
             * @enum {string}
             */
            trigger: "ui" | "cli" | "git";
            /** Updated At */
            updated_at: string;
        };
        /** OperationPage */
        OperationPage: {
            /** Cursor */
            cursor: string;
            /** Items */
            items: components["schemas"]["Operation"][];
            /** Next Page */
            next_page?: string | null;
        };
        /** OperationRequest */
        OperationRequest: {
            /** Approved Digest */
            approved_digest: string;
            /** Idempotency Key */
            idempotency_key: string;
            /** Plan Id */
            plan_id: string;
        };
        /** PartialError */
        PartialError: {
            /** Code */
            code: string;
            /** Scope */
            scope: string;
        };
        /** PlanRecord */
        PlanRecord: {
            /** Actions */
            actions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Application Id */
            application_id: string;
            /**
             * Authorization
             * @default manual
             * @enum {string}
             */
            authorization: "manual" | "policy";
            /** Checks */
            checks?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Diffs */
            diffs: components["schemas"]["ResourceDiff"][];
            /** Digest */
            digest: string;
            /** Engine Digest */
            engine_digest?: string | null;
            /** Evaluation Id */
            evaluation_id?: string | null;
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /**
             * Intent
             * @enum {string}
             */
            intent: "deploy" | "rollback";
            /**
             * Plan Kind
             * @default release
             * @enum {string}
             */
            plan_kind: "release" | "pipeline-preview" | "pipeline-materialized";
            /** Policy Digest */
            policy_digest?: string | null;
            /** Precondition Digest */
            precondition_digest?: string | null;
            /** Release */
            release: string;
            source?: components["schemas"]["SourceRevision"] | null;
            /** Summary */
            summary: {
                [key: string]: number;
            };
            target: components["schemas"]["Target"];
            /** Warnings */
            warnings?: string[];
        };
        /** PlanRequest */
        PlanRequest: {
            /**
             * Intent
             * @default deploy
             * @enum {string}
             */
            intent: "deploy" | "rollback";
            /** Release */
            release?: string | null;
        };
        /** Principal */
        Principal: {
            /** Id */
            id: string;
            /**
             * Kind
             * @default local
             * @enum {string}
             */
            kind: "local" | "oidc" | "service";
            /** Name */
            name: string;
        };
        /**
         * RecoveryRequest
         * @description A new attempt of the same approved plan, never implicit replanning.
         */
        RecoveryRequest: {
            /** Approved Digest */
            approved_digest: string;
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** ReleasePage */
        ReleasePage: {
            /** Cursor */
            cursor: string;
            /** Items */
            items: components["schemas"]["ReleaseSummary"][];
            /** Next Page */
            next_page?: string | null;
        };
        /** ReleaseSummary */
        ReleaseSummary: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["Capability"];
            };
            /** Created At */
            created_at?: string | null;
            /** Name */
            name: string;
            /**
             * Selected
             * @default false
             */
            selected: boolean;
            /** State */
            state: string;
        };
        /** RemoteAccessClaimRequest */
        RemoteAccessClaimRequest: {
            /** Pairing Secret */
            pairing_secret: string;
        };
        /** RemoteAccessHeartbeatRequest */
        RemoteAccessHeartbeatRequest: {
            /** Lease Secret */
            lease_secret: string;
            /** Local Port */
            local_port?: number | null;
            /**
             * State
             * @enum {string}
             */
            state: "connecting" | "ready" | "failed";
        };
        /** RemoteAccessLease */
        RemoteAccessLease: {
            /** Lease Secret */
            lease_secret: string;
            session: components["schemas"]["AccessSession"];
            target: components["schemas"]["Target"];
        };
        /** RemoteAccessReleaseRequest */
        RemoteAccessReleaseRequest: {
            /** Lease Secret */
            lease_secret: string;
        };
        /** RemoteAccessStartRequest */
        RemoteAccessStartRequest: {
            /**
             * Duration Seconds
             * @default 900
             */
            duration_seconds: number;
            /** Remote Port */
            remote_port: number;
            /** Resource Id */
            resource_id: string;
            /** Resource Uid */
            resource_uid: string;
        };
        /** RemoteAccessTicket */
        RemoteAccessTicket: {
            /** Pairing Secret */
            pairing_secret: string;
            session: components["schemas"]["AccessSession"];
        };
        /** Resource */
        Resource: {
            /** Capabilities */
            capabilities?: {
                [key: string]: components["schemas"]["Capability"];
            };
            /** Conditions */
            conditions?: {
                [key: string]: components["schemas"]["JsonValue"];
            }[];
            /** Containers */
            containers?: string[];
            /**
             * Health
             * @default unknown
             * @enum {string}
             */
            health: "healthy" | "progressing" | "degraded" | "suspended" | "unknown";
            /** Id */
            id: string;
            identity: components["schemas"]["ResourceIdentity"];
            /** Images */
            images?: string[];
            /** Manifest */
            manifest?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
            /** Owner Uids */
            owner_uids?: string[];
            /**
             * Ownership
             * @enum {string}
             */
            ownership: "managed" | "unmanaged" | "external" | "unknown";
            /** Phase */
            phase?: string | null;
            /** Ports */
            ports?: number[];
            /**
             * Presence
             * @enum {string}
             */
            presence: "present" | "missing" | "unknown";
            /**
             * Relation
             * @default unknown
             * @enum {string}
             */
            relation: "in_sync" | "changes" | "drifted" | "unknown" | "external";
            /** Resource Version */
            resource_version?: string | null;
        };
        /** ResourceDiff */
        ResourceDiff: {
            /**
             * Basis
             * @enum {string}
             */
            basis: "server-dry-run" | "client";
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
            /** Not Compared */
            not_compared?: string[];
            /** Operation */
            operation: string;
            resource: components["schemas"]["ResourceIdentity"];
            /** Unified */
            unified: string;
        };
        /** ResourceIdentity */
        ResourceIdentity: {
            /** Api Version */
            api_version: string;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Target Id */
            target_id: string;
            /** Uid */
            uid?: string | null;
        };
        /** ResourcePage */
        ResourcePage: {
            /** Cursor */
            cursor: string;
            /** Event Cursor */
            event_cursor?: string | null;
            freshness: components["schemas"]["Freshness"];
            /** Items */
            items: components["schemas"]["Resource"][];
            /** Next Page */
            next_page?: string | null;
            /** Partial */
            partial?: components["schemas"]["PartialError"][];
        };
        /** SourceRevision */
        SourceRevision: {
            /** Entrypoint */
            entrypoint: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "local" | "git" | "oci";
            /** Revision */
            revision: string;
        };
        /** Stage */
        Stage: {
            /** Name */
            name: string;
            /** Reason */
            reason?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "succeeded" | "failed" | "skipped" | "interrupted";
        };
        /** Target */
        Target: {
            /** Cluster Uid */
            cluster_uid?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Namespace */
            namespace: string;
            /** Namespace Uid */
            namespace_uid?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_api_v1_applications_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    application_api_v1_applications__application_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_sessions_api_v1_applications__application_id__access_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_access_api_v1_applications__application_id__access_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_session_api_v1_applications__application_id__access_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_access_api_v1_applications__application_id__access_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_preview_api_v1_applications__application_id__evaluation_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_v1_applications__application_id__evaluations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    operation_list_api_v1_applications__application_id__operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admit_api_v1_applications__application_id__operations_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    releases_api_v1_applications__application_id__releases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_remote_access_api_v1_applications__application_id__remote_access_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_remote_access_api_v1_applications__application_id__remote_access_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoteAccessStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoteAccessTicket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remote_access_ticket_api_v1_applications__application_id__remote_access__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_remote_access_api_v1_applications__application_id__remote_access__ticket_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resources_api_v1_applications__application_id__resources_get: {
        parameters: {
            query?: {
                cursor?: string | null;
            };
            header?: never;
            path: {
                application_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourcePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resource_api_v1_applications__application_id__resources__resource_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_sources_api_v1_applications__application_id__resources__resource_id__log_sources_get: {
        parameters: {
            query: {
                resource_uid: string;
            };
            header?: never;
            path: {
                application_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogSourcePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_logs_api_v1_applications__application_id__resources__resource_id__logs_get: {
        parameters: {
            query: {
                resource_uid: string;
                pod_name: string;
                pod_uid: string;
                container: string;
                previous?: boolean;
                tail_lines?: number;
            };
            header?: never;
            path: {
                application_id: string;
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogBatch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    environments_api_v1_environments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    environment_action_api_v1_environments_actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_api_v1_evaluations__evaluation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evaluation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query: {
                application_id: string;
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gitops_api_v1_gitops_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    gitops_approval_api_v1_gitops_approvals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitOpsApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gitops_promotion_api_v1_gitops_promotions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitOpsPromotionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observation_events_api_v1_observation_events_get: {
        parameters: {
            query: {
                application_id: string;
                after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schema_api_v1_openapi_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    operation_api_v1_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_operations__operation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_operations__operation_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_remote_access_api_v1_remote_access__ticket_id__claim_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoteAccessClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoteAccessLease"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remote_access_heartbeat_api_v1_remote_access__ticket_id__heartbeat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoteAccessHeartbeatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_remote_access_api_v1_remote_access__ticket_id__release_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoteAccessReleaseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
