// Connected infrastructure uses the existing disposable Kubernetes/controller
// showcase. These tests verify navigation, observed identities and URL state.
const path = require('node:path');
const { test, expect } = require('./session.cjs');

const productCommit = '3f9c2d1e8a7b4c5d6e0f1a2b3c4d5e6f7a8b9c0d';
const assetsCommit = 'b7e4a1c9d2f3081726354a5b6c7d8e9f0a1b2c3d';
const branchCommit = 'c1d2e3f4a5b60718293a4b5c6d7e8f9001122334';
const query = page => new URL(page.url()).searchParams;
const fits = page => expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
async function shot(page, testInfo, name) {
  const directory = process.env.PICELI_UI_CONNECTED_SHOTS;
  if (directory) await page.screenshot({ path: path.join(directory, `${testInfo.project.name}-${name}.png`), fullPage: true });
}

test('environment switchboard and expanded topology preserve selection and focus', async ({ page }, testInfo) => {
  await page.goto('/composition/overview?environment=main&scope=all&node=source&source=assets');
  const rail = page.getByRole('group', { name: 'Environment switchboard' });
  await rail.getByRole('button', { name: 'Show environment wp-login', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Inspect web in wp-login', exact: true })).toBeVisible();
  expect(query(page).get('environment')).toBe('wp-login');
  for (const key of ['scope', 'node', 'source', 'component']) expect(query(page).has(key)).toBe(false);
  await page.reload();
  await expect(rail.getByRole('button', { name: 'Show environment wp-login', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const expand = page.getByRole('button', { name: 'Expand topology', exact: true });
  await expand.click();
  const explorer = page.getByRole('dialog', { name: 'Infrastructure explorer', exact: true });
  await expect(explorer).toBeVisible();
  await explorer.getByRole('button', { name: 'Show environment main', exact: true }).click();
  await explorer.getByRole('button', { name: 'Inspect media in main', exact: true }).click();
  await expect(explorer.getByRole('complementary', { name: 'Selected component' }).getByRole('heading', { name: 'media', exact: true })).toBeVisible();
  expect(query(page).get('environment')).toBe('main');
  expect(query(page).get('component')).toBe('media');
  await fits(page);
  await shot(page, testInfo, 'expanded-topology');
  await page.keyboard.press('Escape');
  await expect(explorer).toHaveCount(0);
  await expect(expand).toBeFocused();
  await expect(page.getByRole('button', { name: 'Inspect media in main', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const inventory = page.getByText('Environment inventory', { exact: true });
  await inventory.click();
  await expect(page.getByRole('region', { name: 'Environment main', exact: true }).getByRole('link', { name: 'Open environment', exact: true })).toBeVisible();
  await fits(page);
});

test('all-environment topology restores exact source selection and scope', async ({ page }, testInfo) => {
  await page.goto('/composition/overview?environment=main');
  const allEnvironments = page.getByRole('checkbox', { name: 'All environments', exact: true });
  await expect(page.getByRole('button', { name: 'Inspect media in main', exact: true })).toBeVisible();
  await allEnvironments.focus();
  await page.keyboard.press('Space');
  await expect(allEnvironments).toBeChecked();
  await expect(page.getByRole('button', { name: 'Inspect web in wp-login', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Select environment wp-idle', exact: true })).toBeVisible();
  const source = page.getByRole('button', { name: 'Select source assets', exact: true });
  await source.focus();
  await page.keyboard.press('Enter');
  const inspector = page.getByRole('complementary', { name: 'Selected source' });
  await expect(inspector.getByRole('heading', { name: 'assets', exact: true })).toBeVisible();
  await expect(inspector.getByText(assetsCommit, { exact: true })).toBeVisible();
  expect(query(page).get('scope')).toBe('all');
  expect(query(page).get('node')).toBe('source');
  expect(query(page).get('source')).toBe('assets');
  await fits(page);
  await shot(page, testInfo, 'connected-topology');
  await page.reload();
  await expect(page.getByRole('checkbox', { name: 'All environments', exact: true })).toBeChecked();
  await expect(source).toHaveAttribute('aria-pressed', 'true');
  await expect(inspector.getByText(assetsCommit, { exact: true })).toBeVisible();
  // This control is URL-backed: wait for the router transition after a normal
  // pointer click rather than check/uncheck's synchronous checked-state probe.
  await allEnvironments.click();
  await expect(allEnvironments).not.toBeChecked();
  await expect(page.getByRole('button', { name: 'Inspect web in wp-login', exact: true })).toHaveCount(0);
  await allEnvironments.click();
  await expect(allEnvironments).toBeChecked();
  await expect(page.getByRole('button', { name: 'Inspect web in wp-login', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Select environment preview', exact: true }).click();
  const environment = page.getByRole('complementary', { name: 'Selected environment' });
  await expect(environment.getByRole('heading', { name: 'preview', exact: true })).toBeVisible();
  await expect(environment).toContainText(/approval.?required/i);
  await environment.getByRole('link', { name: 'Open preview', exact: true }).click();
  await expect(page).toHaveURL(/\/composition\/environments\/preview$/);
  await fits(page);
});

test('version comparison persists both environments and returns from exact component inspection', async ({ page }, testInfo) => {
  await page.goto('/composition/overview?view=versions');
  const baseline = page.getByRole('combobox', { name: 'Baseline environment', exact: true });
  const target = page.getByRole('combobox', { name: 'Target environment', exact: true });
  await baseline.selectOption('main');
  await target.selectOption('wp-login');
  const web = page.getByRole('row').filter({ has: page.getByRole('rowheader', { name: /^web/ }) });
  await expect(web.getByText('Different', { exact: true })).toBeVisible();
  await expect(web.getByText('Image unreported', { exact: true })).toBeVisible();
  await expect(page.getByText('Different does not mean newer.', { exact: false })).toBeVisible();
  await web.getByText('Exact identities', { exact: true }).first().click();
  await expect(web.getByText(productCommit, { exact: true })).toBeVisible();
  expect(query(page).get('baseline')).toBe('main');
  expect(query(page).get('compare')).toBe('wp-login');
  await fits(page);
  await shot(page, testInfo, 'versions');
  await page.reload();
  await expect(baseline).toHaveValue('main');
  await expect(target).toHaveValue('wp-login');
  await web.getByRole('button', { name: 'Inspect target', exact: false }).click();
  const inspector = page.getByRole('complementary', { name: 'Selected component' });
  await expect(inspector.getByRole('heading', { name: 'web', exact: true })).toBeVisible();
  await expect(inspector.getByText(branchCommit, { exact: true })).toBeVisible();
  expect(query(page).get('environment')).toBe('wp-login');
  expect(query(page).get('component')).toBe('web');
  await page.getByRole('group', { name: 'Infrastructure view' }).getByRole('button', { name: 'Versions', exact: true }).click();
  await expect(baseline).toHaveValue('main');
  await expect(target).toHaveValue('wp-login');
  await expect(web.getByText('Different', { exact: true })).toBeVisible();
  await fits(page);
});

test('attention separates approval and lifecycle states from reported failures', async ({ page }, testInfo) => {
  await page.goto('/composition/overview?view=attention');
  const investigate = page.getByRole('region', { name: 'Needs investigation', exact: true });
  const decisions = page.getByRole('region', { name: 'Decisions waiting', exact: true });
  const lifecycle = page.getByRole('region', { name: 'In progress & stopped', exact: true });
  await expect(investigate.getByText('No issues reported in this snapshot.', { exact: true })).toBeVisible();
  await expect(decisions.getByText('Plan awaiting approval', { exact: true })).toBeVisible();
  await expect(decisions).toContainText(`sha256:${'e'.repeat(64)}`);
  await expect(decisions.getByRole('link', { name: 'Inspect', exact: true })).toHaveAttribute('href', '/composition/environments/preview');
  const stopped = lifecycle.getByRole('listitem').filter({ hasText: 'wp-idle' });
  await expect(stopped.getByText('Environment stopped', { exact: true })).toBeVisible();
  await expect(stopped.getByRole('link', { name: 'Inspect', exact: true })).toHaveAttribute('href', '/composition/environments/wp-idle');
  await expect(investigate).not.toContainText('wp-idle');
  await fits(page);
  await shot(page, testInfo, 'attention');
  await lifecycle.getByRole('listitem').filter({ hasText: 'main / media' }).getByRole('link', { name: 'Inspect', exact: true }).click();
  await expect(page.getByRole('complementary', { name: 'Selected component' }).getByRole('heading', { name: 'media', exact: true })).toBeVisible();
  expect(query(page).get('environment')).toBe('main');
  expect(query(page).get('component')).toBe('media');
  await fits(page);
});

test('workspace keyboard search restores focus and jumps to the exact component', async ({ page }, testInfo) => {
  await page.goto('/applications');
  const trigger = page.getByRole('button', { name: 'Search workspace', exact: true });
  await expect(trigger).toBeVisible();
  const dialog = page.getByRole('dialog', { name: 'Go anywhere', exact: true });
  const search = page.getByRole('searchbox', { name: 'Search destinations', exact: true });
  for (const shortcut of ['Control+k', 'Meta+k']) {
    await page.keyboard.press(shortcut);
    await expect(dialog).toBeVisible();
    await expect(search).toBeFocused();
    await page.keyboard.press('Escape');
    await expect(dialog).toHaveCount(0);
    await expect(trigger).toBeFocused();
  }
  await trigger.click();
  await search.fill('media');
  const result = dialog.getByRole('link', { name: 'Component: media, main · assets', exact: true });
  await expect(result).toBeVisible();
  await fits(page);
  await shot(page, testInfo, 'workspace-search');
  await result.focus();
  await page.keyboard.press('Enter');
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('main')).toBeFocused();
  await expect(page.getByRole('complementary', { name: 'Selected component' }).getByRole('heading', { name: 'media', exact: true })).toBeVisible();
  expect(query(page).get('environment')).toBe('main');
  expect(query(page).get('component')).toBe('media');
  await fits(page);
});

test('fleet state filters survive reload without dropping search and target', async ({ page }, testInfo) => {
  await page.goto('/applications?q=Shop&layout=table');
  await expect(page.getByRole('link', { name: 'Shop', exact: true })).toBeVisible();
  const target = page.getByRole('combobox', { name: 'Target', exact: true });
  await target.selectOption({ index: 1 });
  const selectedTarget = await target.inputValue();
  const filters = page.getByRole('group', { name: 'Filter loaded applications by state' });
  const attention = filters.getByRole('button', { name: /^Needs attention/ });
  await attention.click();
  await expect(attention).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('heading', { name: 'No matching applications', exact: true })).toBeVisible();
  expect(query(page).get('state')).toBe('attention');
  expect(query(page).get('q')).toBe('Shop');
  expect(query(page).get('target')).toBe(selectedTarget);
  expect(query(page).get('layout')).toBe('table');
  await page.reload();
  await expect(attention).toHaveAttribute('aria-pressed', 'true');
  await expect(target).toHaveValue(selectedTarget);
  await expect(page.getByRole('searchbox', { name: 'Search applications' })).toHaveValue('Shop');
  await filters.getByRole('button', { name: /^All applications/ }).click();
  await expect(page.getByRole('link', { name: 'Shop', exact: true })).toBeVisible();
  expect(query(page).has('state')).toBe(false);
  expect(query(page).get('q')).toBe('Shop');
  expect(query(page).get('target')).toBe(selectedTarget);
  await fits(page);
  await shot(page, testInfo, 'fleet');
});

test('recorded activity opens the exact read-only plan without granting deployment', async ({ page }, testInfo) => {
  const writes = [];
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') writes.push(request.method()); });
  await page.goto('/applications/shop/activity');
  const failed = page.getByRole('article', { name: 'Run showcase-failed', exact: true });
  await expect(failed).toBeVisible();
  const attention = page.getByRole('group', { name: 'Run status filter' }).getByRole('button', { name: /^Needs attention/ });
  await attention.click();
  await expect(attention).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('article', { name: 'Run showcase-cancelled', exact: true })).toHaveCount(0);
  await expect(page.getByRole('article', { name: 'Run showcase-succeeded', exact: true })).toHaveCount(0);
  expect(query(page).get('activity')).toBe('needs-attention');
  await page.reload();
  await expect(attention).toHaveAttribute('aria-pressed', 'true');
  await expect(failed).toContainText('Fixture: readiness deadline reached');
  await fits(page);
  await shot(page, testInfo, 'recorded-activity');
  await failed.getByRole('link', { name: 'Review plan', exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/shop\/changes\?plan=showcase-plan$/);
  await expect(page.getByRole('heading', { name: 'Review deployment', exact: true })).toBeVisible();
  const changesTab = page.getByRole('navigation', { name: 'Application views' }).getByRole('link', { name: 'Changes', exact: true });
  await expect(changesTab).toHaveAttribute('aria-current', 'page');
  await expect(changesTab).toHaveAttribute('href', '/applications/shop/changes?plan=showcase-plan');
  await expect(page.getByText('Deployment unavailable', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Prepare a new review', exact: true })).toHaveCount(0);
  const changes = page.getByRole('region', { name: 'Resource change workbench' });
  await changes.getByRole('searchbox', { name: 'Search changes', exact: true }).fill('/spec/replicas');
  await expect(changes.getByLabel('Before /spec/replicas', { exact: true })).toHaveText('2');
  await expect(changes.getByLabel('After /spec/replicas', { exact: true })).toHaveText('3');
  await expect(changes).toContainText('Approval includes all 3 resource entries');
  await changes.getByRole('button', { name: 'Clear filters', exact: true }).click();
  await changes.getByRole('navigation', { name: 'Changed resources' }).getByRole('button', { name: /^api Service/ }).click();
  await expect(changes.getByLabel('Before /spec/ports/0/port', { exact: true })).toHaveText('8080');
  await expect(changes.getByLabel('After /spec/ports/0/port', { exact: true })).toHaveText('80');
  await page.getByRole('checkbox', { name: /^I reviewed the changes, source revision and target/ }).check();
  await expect(page.getByRole('button', { name: /^Deploy to / })).toBeDisabled();
  await fits(page);
  await shot(page, testInfo, 'recorded-plan');
  await page.goto('/applications/shop/changes');
  await expect(page.getByText('Changes unavailable', { exact: true })).toBeVisible();
  expect(writes).toEqual([]);
});

test('recorded revisions compare actual desired fields and expose ordered execution evidence', async ({ page }, testInfo) => {
  const writes = [];
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') writes.push(request.method()); });
  await page.goto('/applications/shop/activity');
  await page.getByRole('group', { name: 'Activity view' }).getByRole('button', { name: 'Compare revisions', exact: true }).click();
  const from = page.getByRole('combobox', { name: 'From revision', exact: true });
  const to = page.getByRole('combobox', { name: 'To revision', exact: true });
  await from.selectOption('showcase-plan');
  await to.selectOption('showcase-plan-previous');
  await expect(page.getByRole('article', { name: 'From revision', exact: true })).toContainText('d74e632dc981290bca241689fc0f6adeb114305a');
  await expect(page.getByRole('article', { name: 'To revision', exact: true })).toContainText('2a8cfe419e5038c114d0b4ac42efda840de81f39');
  await page.getByRole('button', { name: 'Swap revisions', exact: true }).click();
  await expect(from).toHaveValue('showcase-plan-previous');
  await expect(to).toHaveValue('showcase-plan');
  expect(query(page).get('history')).toBe('revisions');
  expect(query(page).get('compareFrom')).toBe('showcase-plan-previous');
  expect(query(page).get('compareTo')).toBe('showcase-plan');
  await page.reload();
  await expect(from).toHaveValue('showcase-plan-previous');
  await expect(to).toHaveValue('showcase-plan');
  const differences = page.getByRole('region', { name: 'Revision differences', exact: true });
  await expect(differences.getByRole('heading', { name: '3 resources differ', exact: true })).toBeVisible();
  await differences.getByRole('searchbox', { name: 'Search changes', exact: true }).fill('/spec/template/spec/containers/0/image');
  await expect(differences.getByLabel('Before /spec/template/spec/containers/0/image', { exact: true })).toHaveText(JSON.stringify('registry.example/shop/api:v1.4.0'));
  await expect(differences.getByLabel('After /spec/template/spec/containers/0/image', { exact: true })).toHaveText(JSON.stringify('registry.example/shop/api:v1.5.0'));
  await fits(page);
  await shot(page, testInfo, 'recorded-revisions');
  await page.getByRole('link', { name: 'Open To plan', exact: true }).click();
  const order = page.getByRole('region', { name: 'Execution order', exact: true });
  await expect(order.getByRole('heading', { name: 'Phase 1', exact: true })).toBeVisible();
  await expect(order.getByRole('heading', { name: 'Phase 2', exact: true })).toBeVisible();
  await order.getByRole('button', { name: 'Inspect planned action 3: Deployment api', exact: true }).click();
  await expect(order.getByRole('region', { name: 'Selected action details', exact: true })).toContainText('ConfigMap / piceli-test / public-settings');
  await expect(page.getByRole('button', { name: /^Deploy to / })).toBeDisabled();
  await shot(page, testInfo, 'deployment-phases');
  await page.goto('/runs/showcase-failed');
  const recordedOrder = page.getByRole('region', { name: 'Execution order', exact: true });
  const deployment = recordedOrder.getByRole('button', { name: 'Inspect recorded action 3: Deployment api', exact: true });
  await expect(deployment).toContainText('Applied');
  await deployment.click();
  await expect(recordedOrder.getByRole('region', { name: 'Selected action details', exact: true })).toContainText('Readiness has not been recorded');
  const journal = page.getByRole('region', { name: 'Execution journal and logs', exact: true });
  await expect(journal.getByRole('list', { name: 'Recorded journal transitions' }).getByRole('listitem').last()).toContainText('failed');
  await journal.getByRole('searchbox', { name: 'Find recorded transition', exact: true }).fill('Deployment');
  await expect(journal.getByRole('list', { name: 'Recorded journal transitions' }).getByRole('listitem')).toHaveCount(2);
  await journal.getByRole('button', { name: /^Captured logs/ }).click();
  const output = journal.getByLabel('Captured output for api-preview / api', { exact: true });
  await expect(output).toContainText('Preview fixture: readiness probe did not succeed before the deadline');
  await journal.getByText('Raw recorded journal', { exact: true }).click();
  const raw = JSON.parse(await journal.getByLabel('Raw recorded journal', { exact: true }).textContent());
  expect(raw.execution_id).toBe('preview-execution-failed');
  expect(raw.actions[2].state).toBe('applied');
  expect(raw.logs[0].lines).toContain('Preview fixture: readiness probe did not succeed before the deadline');
  await fits(page);
  await shot(page, testInfo, 'recorded-journal');
  expect(writes).toEqual([]);
});

test('deployment history navigation retains the chosen view and opens recorded logs directly', async ({ page }, testInfo) => {
  const writes = [];
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') writes.push(request.method()); });
  await page.goto('/composition/overview');
  const navigation = page.getByRole('navigation', { name: 'Main navigation', exact: true });
  await navigation.getByRole('link', { name: 'Deployment history', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Deployment history', exact: true })).toBeVisible();
  const application = page.getByRole('combobox', { name: 'Application history', exact: true });
  await expect(application).toHaveValue('shop');
  await expect(page.getByRole('region', { name: 'Recorded plan archive', exact: true })).toBeVisible();
  const views = page.getByRole('navigation', { name: 'Deployment history views', exact: true });
  await views.getByRole('button', { name: /^Runs & logs/ }).click();
  const failed = page.getByRole('article', { name: 'Run showcase-failed', exact: true });
  await expect(failed).toBeVisible();
  expect(query(page).get('application')).toBe('shop');
  expect(query(page).get('deliveryView')).toBe('runs');
  await page.reload();
  await expect(views.getByRole('button', { name: /^Runs & logs/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(application).toHaveValue('shop');
  await fits(page);
  await shot(page, testInfo, 'deployment-history-runs');
  await failed.getByRole('link', { name: 'Open logs', exact: true }).click();
  await expect(page).toHaveURL(/\/runs\/showcase-failed\?runView=logs#execution-journal$/);
  const journal = page.getByRole('region', { name: 'Execution journal and logs', exact: true });
  await expect(journal.getByRole('button', { name: /^Captured logs/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(journal.getByLabel('Captured output for api-preview / api', { exact: true })).toContainText('Preview fixture: readiness probe did not succeed before the deadline');
  await expect(journal).toBeFocused();
  await page.reload();
  await expect(journal.getByRole('button', { name: /^Captured logs/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(journal).toBeFocused();
  await fits(page);
  await shot(page, testInfo, 'direct-recorded-logs');
  await page.goto('/delivery?application=shop&deliveryView=revisions&compareFrom=showcase-plan-previous&compareTo=showcase-plan');
  await expect(views.getByRole('button', { name: /^Compare revisions/ })).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('combobox', { name: 'From revision', exact: true })).toHaveValue('showcase-plan-previous');
  await expect(page.getByRole('region', { name: 'Revision differences', exact: true }).getByRole('heading', { name: '3 resources differ', exact: true })).toBeVisible();
  await page.reload();
  await expect(views.getByRole('button', { name: /^Compare revisions/ })).toHaveAttribute('aria-pressed', 'true');
  await fits(page);
  expect(writes).toEqual([]);
});

test('the plan archive exposes unused expired reviews without inventing a deployment', async ({ page }, testInfo) => {
  const writes = [];
  page.on('request', request => { if (request.url().includes('/api/') && request.method() !== 'GET') writes.push(request.method()); });
  await page.goto('/delivery?application=shop');
  const unused = page.getByRole('row', { name: 'Plan showcase-plan-unused', exact: true });
  await expect(unused.getByText('No recorded run', { exact: true })).toBeVisible();
  await expect(unused.getByText('Expired', { exact: true })).toBeVisible();
  await expect(unused.getByRole('link', { name: 'Open run', exact: true })).toHaveCount(0);
  await expect(unused.getByRole('link', { name: 'Open logs', exact: true })).toHaveCount(0);
  await fits(page);
  await shot(page, testInfo, 'recorded-plan-archive');
  const filter = page.getByRole('combobox', { name: 'Filter plans', exact: true });
  await filter.selectOption('no-runs');
  await expect(page.getByRole('row', { name: 'Plan showcase-plan', exact: true })).toHaveCount(0);
  await expect(unused).toBeVisible();
  const search = page.getByRole('searchbox', { name: 'Search recorded plans', exact: true });
  await search.fill('unapplied-scale');
  expect(query(page).get('planFilter')).toBe('no-runs');
  await expect.poll(() => query(page).get('planSearch')).toBe('unapplied-scale');
  await page.reload();
  await expect(filter).toHaveValue('no-runs');
  await expect(search).toHaveValue('unapplied-scale');
  await unused.getByText('Full revision', { exact: true }).click();
  await expect(unused.getByText('d74e632dc981290bca241689fc0f6adeb114305a', { exact: true })).toBeVisible();
  await unused.getByRole('link', { name: 'Open plan', exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/shop\/changes\?plan=showcase-plan-unused$/);
  const changes = page.getByRole('region', { name: 'Resource change workbench', exact: true });
  await expect(changes.getByLabel('Before /spec/replicas', { exact: true })).toHaveText('3');
  await expect(changes.getByLabel('After /spec/replicas', { exact: true })).toHaveText('4');
  await expect(page.getByRole('button', { name: /^Deploy to / })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Prepare a new review', exact: true })).toHaveCount(0);
  await fits(page);
  await page.getByRole('navigation', { name: 'Application views', exact: true }).getByRole('link', { name: 'Plans', exact: true }).click();
  await expect(page).toHaveURL(/\/applications\/shop\/plans$/);
  await expect(unused.getByText('No recorded run', { exact: true })).toBeVisible();
  expect(writes).toEqual([]);
});
