"""Dockerfile rendering and pin checks for declarative builds.

Two modes produce the Dockerfile BuildKit receives:

* **Generated**: Piceli writes the whole file from the spec. The builder
  image is referenced by digest, each context is copied from a staged named
  context, dependency caches are BuildKit cache mounts, and one ``RUN`` runs
  the declared commands and copies the declared outputs out of the (possibly
  cache-mounted) tree in the same step.
* **User Dockerfile**: the file comes from a staged context. Every base image
  (``FROM``, ``COPY --from``, ``RUN --mount=from=``) must be a stage, a
  declared context, ``scratch``, an ``image@sha256:`` literal or a build
  argument bound to a pinned image. Frontend ``syntax`` directives and remote
  ``ADD`` are rejected because they fetch unpinned code or data. This is a
  guardrail against drift, not a sandbox.

Both modes append the same scratch export stage for file outputs. Importing
this module runs nothing.
"""

from __future__ import annotations

import json
import re
import shlex
from collections.abc import Iterable, Mapping
from dataclasses import dataclass

PICELI_ROOT = "/piceli"
OUTPUT_ROOT = "/piceli/out"
IMAGE_ROOT = "/piceli/image"
BUILD_STAGE = "piceli-build"
FILES_STAGE = "piceli-files"
IMAGE_STAGE_PREFIX = "piceli-image-"

_PINNED_REF = re.compile(r"[^\s@$]+@sha256:[a-f0-9]{64}")
_ARG_REF = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)\}?")
_DIRECTIVE = re.compile(r"#\s*([A-Za-z]+)\s*=")


class DockerfileError(ValueError):
    """A Dockerfile violates the pinning policy (fixed code ``dockerfile``)."""

    code = "dockerfile-unpinned"


def quote_json(values: Iterable[str]) -> str:
    return json.dumps(list(values), ensure_ascii=False)


@dataclass(frozen=True)
class CacheMount:
    id: str
    target: str
    sharing: str

    def flag(self) -> str:
        return (
            f"--mount=type=cache,id={self.id},target={self.target},"
            f"sharing={self.sharing}"
        )


@dataclass(frozen=True)
class FileCopy:
    """One declared file output: ``source`` in a stage, ``to`` in the outputs."""

    to: str
    source: str
    stage: str = BUILD_STAGE


@dataclass(frozen=True)
class ImageStage:
    name: str
    base: str
    files: tuple[tuple[str, str], ...]
    entrypoint: tuple[str, ...] | None = None
    cmd: tuple[str, ...] | None = None
    user: str | None = None
    workdir: str | None = None


def export_stage(files: tuple[FileCopy, ...]) -> list[str]:
    lines = [f"FROM scratch AS {FILES_STAGE}"]
    lines.extend(
        f"COPY --from={item.stage} {quote_json([item.source, '/' + item.to])}"
        for item in files
    )
    return lines


def render_generated(
    *,
    builder_ref: str,
    workdir: str,
    env: Mapping[str, str],
    contexts: Iterable[tuple[str, str]],
    caches: Iterable[CacheMount],
    commands: tuple[tuple[str, ...], ...],
    files: tuple[FileCopy, ...],
    images: tuple[ImageStage, ...],
    network: str,
    epoch: int = 0,
) -> str:
    """Render a complete Dockerfile. All values were validated by the spec.

    Collected outputs get the fixed ``epoch`` as modification time so an image
    layer that copies them does not depend on when the build ran.
    """
    lines = [
        "# Generated by piceli (piceli.build-spec.v1). Do not edit.",
        f"FROM {builder_ref} AS {BUILD_STAGE}",
        f"WORKDIR {workdir}",
    ]
    lines.extend(f'ENV {key}="{value}"' for key, value in sorted(env.items()))
    lines.extend(
        f"COPY --from={name} {quote_json(['/', target.rstrip('/') + '/'])}"
        for name, target in contexts
    )
    steps = [shlex.join(command) for command in commands]
    for item in files:
        destination = f"{OUTPUT_ROOT}/{item.to}"
        parent = destination.rsplit("/", 1)[0]
        steps.append(f"mkdir -p -- {shlex.quote(parent)}")
        steps.append(f"cp -- {shlex.quote(item.source)} {shlex.quote(destination)}")
    if not files:
        steps.append(f"mkdir -p -- {OUTPUT_ROOT}")
    # Each image's files are laid out at their final paths, then every entry
    # (directories included) gets the fixed epoch. Copying that tree into the
    # base keeps even the parent directories' times independent of the clock.
    for image in images:
        root = f"{IMAGE_ROOT}/{image.name}"
        steps.append(f"mkdir -p -- {shlex.quote(root)}")
        for source, target in image.files:
            destination = root + target
            parent = destination.rsplit("/", 1)[0]
            steps.append(f"mkdir -p -- {shlex.quote(parent)}")
            steps.append(
                f"cp -- {shlex.quote(f'{OUTPUT_ROOT}/{source}')} "
                f"{shlex.quote(destination)}"
            )
    steps.append(f"find {PICELI_ROOT} -exec touch -d @{int(epoch)} {{}} +")
    script = "\n".join(steps)
    flags = [f"--network={network}", *(cache.flag() for cache in caches)]
    lines.append(
        "RUN " + " ".join(flags) + " " + quote_json(["/bin/sh", "-euc", script])
    )
    lines.extend(
        export_stage(
            tuple(FileCopy(item.to, f"{OUTPUT_ROOT}/{item.to}") for item in files)
        )
    )
    for image in images:
        lines.append(f"FROM {image.base} AS {IMAGE_STAGE_PREFIX}{image.name}")
        if image.files:
            lines.append(
                f"COPY --from={BUILD_STAGE} "
                + quote_json([f"{IMAGE_ROOT}/{image.name}/", "/"])
            )
        if image.workdir:
            lines.append(f"WORKDIR {image.workdir}")
        if image.user:
            lines.append(f"USER {image.user}")
        if image.entrypoint is not None:
            lines.append(f"ENTRYPOINT {quote_json(image.entrypoint)}")
        if image.cmd is not None:
            lines.append(f"CMD {quote_json(image.cmd)}")
    return "\n".join(lines) + "\n"


def _logical_lines(text: str) -> list[str]:
    """Join continuation lines and drop comments (after parser directives)."""
    result: list[str] = []
    current = ""
    for raw in text.splitlines():
        stripped = raw.strip()
        if not current and (not stripped or stripped.startswith("#")):
            continue
        if stripped.endswith("\\"):
            current += stripped[:-1] + " "
            continue
        result.append(current + stripped)
        current = ""
    if current.strip():
        result.append(current)
    return result


def check_user_dockerfile(
    text: str,
    *,
    pinned_args: frozenset[str],
    contexts: frozenset[str],
    required_arg: str,
) -> tuple[str, ...]:
    """Validate base-image pinning and return the declared stage names."""
    for raw in text.splitlines():
        stripped = raw.strip()
        if not stripped.startswith("#"):
            break
        match = _DIRECTIVE.match(stripped)
        if match and match.group(1).lower() == "syntax":
            raise DockerfileError(
                "syntax directives fetch a frontend image; use the built-in one"
            )
    stages: list[str] = []
    uses_builder = False

    def allowed(reference: str) -> bool:
        nonlocal uses_builder
        argument = _ARG_REF.fullmatch(reference)
        if argument is not None:
            if argument.group(1) == required_arg:
                uses_builder = True
            return argument.group(1) in pinned_args
        return (
            reference.lower() in stages
            or reference in contexts
            or reference == "scratch"
            or _PINNED_REF.fullmatch(reference) is not None
            or reference.isdigit()
        )

    for line in _logical_lines(text):
        words = line.split()
        instruction = words[0].upper()
        if instruction == "FROM":
            rest = [word for word in words[1:] if not word.startswith("--")]
            if not rest or not allowed(rest[0]):
                raise DockerfileError("FROM must use a pinned image, stage or arg")
            if len(rest) >= 3 and rest[1].upper() == "AS":
                stages.append(rest[2].lower())
        elif instruction in {"COPY", "ADD"}:
            for word in words[1:]:
                if word.startswith("--from=") and not allowed(word[7:]):
                    raise DockerfileError("COPY --from must use a pinned source")
            if instruction == "ADD" and any(
                re.match(r"(https?|git)://|git@", word) for word in words[1:]
            ):
                raise DockerfileError("remote ADD sources are not pinned")
        elif instruction == "RUN":
            for word in words[1:]:
                if not word.startswith("--mount="):
                    continue
                for option in word[8:].split(","):
                    if option.startswith("from=") and not allowed(option[5:]):
                        raise DockerfileError("RUN --mount from must be pinned")
    if not uses_builder:
        raise DockerfileError(f"the Dockerfile must build FROM ${{{required_arg}}}")
    return tuple(stages)
