"""Models generated by ``piceli codegen crd`` from the CRDs in ``tests/fixtures/crds``.

Regenerate with::

    piceli codegen crd tests/fixtures/crds/cert-manager-certificate.yaml \
        --out examples/environments/crds/certificate.py
    piceli codegen crd tests/fixtures/crds/prometheus-servicemonitor.yaml \
        --out examples/environments/crds/service_monitor.py
"""
