"""Typed models for the ``ServiceMonitor`` custom resource (``monitoring.coreos.com/v1``).

Generated by ``piceli codegen crd``; do not edit. Source:
CustomResourceDefinition ``servicemonitors.monitoring.coreos.com``, version ``v1``.
The output depends only on the schema: the same CRD, from a file or
from a cluster, always generates this file.

Use with ``app.resource(API_VERSION, KIND, name, ServiceMonitorSpec(...))``.
"""

# ruff: noqa

from __future__ import annotations

from typing import Annotated, ClassVar, Literal

from pydantic import BaseModel, ConfigDict, Field

API_VERSION = "monitoring.coreos.com/v1"
KIND = "ServiceMonitor"
SCOPE = "namespaced"
CRD = "servicemonitors.monitoring.coreos.com"
SCHEMA_SHA256 = "sha256:baf1a063fd1ab060b2f4b80f1f0808c137fbbfeaea616eccf5d01d365a7a0744"
GENERATOR = "piceli-codegen-crd/1"


class _Model(BaseModel):
    """Frozen; accepts Kubernetes names and snake_case; refuses unknown fields."""

    model_config = ConfigDict(
        extra="forbid", frozen=True, populate_by_name=True, regex_engine="python-re"
    )


class ServiceMonitorSpecAttachMetadata(_Model):
    """`attachMetadata` defines additional metadata which is added to the
    discovered targets.
    """

    node: bool | None = None
    """When set to true, Prometheus attaches node metadata to the discovered
    targets.
    """


class ServiceMonitorSpecEndpointsItemAuthorizationCredentials(_Model):
    """Selects a key of a Secret in the namespace that contains the credentials
    for authentication.
    """

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemAuthorization(_Model):
    """`authorization` configures the Authorization header credentials to use when
    scraping the target.
    """

    credentials: ServiceMonitorSpecEndpointsItemAuthorizationCredentials | None = None
    """Selects a key of a Secret in the namespace that contains the credentials
    for authentication.
    """

    type: str | None = None
    """Defines the authentication type. The value is case-insensitive."""


class ServiceMonitorSpecEndpointsItemBasicAuthPassword(_Model):
    """`password` specifies a key of a Secret containing the password for
    authentication.
    """

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemBasicAuthUsername(_Model):
    """`username` specifies a key of a Secret containing the username for
    authentication.
    """

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemBasicAuth(_Model):
    """`basicAuth` configures the Basic Authentication credentials to use when
    scraping the target.
    """

    password: ServiceMonitorSpecEndpointsItemBasicAuthPassword | None = None
    """`password` specifies a key of a Secret containing the password for
    authentication.
    """

    username: ServiceMonitorSpecEndpointsItemBasicAuthUsername | None = None
    """`username` specifies a key of a Secret containing the username for
    authentication.
    """


class ServiceMonitorSpecEndpointsItemBearerTokenSecret(_Model):
    """`bearerTokenSecret` specifies a key of a Secret containing the bearer token
    for scraping targets. The secret needs to be in the same namespace as the
    ServiceMonitor object and readable by the Prometheus Operator.
    """

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemMetricRelabelingsItem(_Model):
    """RelabelConfig allows dynamic rewriting of the label set for targets,
    alerts, scraped samples and remote write samples.
    """

    action: Literal["replace", "Replace", "keep", "Keep", "drop", "Drop", "hashmod", "HashMod", "labelmap", "LabelMap", "labeldrop", "LabelDrop", "labelkeep", "LabelKeep", "lowercase", "Lowercase", "uppercase", "Uppercase", "keepequal", "KeepEqual", "dropequal", "DropEqual"] | None = None
    """Action to perform based on the regex matching."""

    modulus: int | None = None
    """Modulus to take of the hash of the source label values."""

    regex: str | None = None
    """Regular expression against which the extracted value is matched."""

    replacement: str | None = None
    """Replacement value against which a Replace action is performed if the
    regular expression matches.
    """

    separator: str | None = None
    """Separator is the string between concatenated SourceLabels."""

    source_labels: list[Annotated[str, Field(pattern="^[a-zA-Z_][a-zA-Z0-9_]*$")]] | None = Field(default=None, alias="sourceLabels")
    """The source labels select values from existing labels. Their content is
    concatenated using the configured Separator and matched against the
    configured regular expression.
    """

    target_label: str | None = Field(default=None, alias="targetLabel")
    """Label to which the resulting string is written in a replacement."""


class ServiceMonitorSpecEndpointsItemOauth2ClientIdConfigMap(_Model):
    """ConfigMap containing data to use for the targets."""

    key: str
    """The key to select."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the ConfigMap or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2ClientIdSecret(_Model):
    """Secret containing data to use for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2ClientId(_Model):
    """`clientId` specifies a key of a Secret or ConfigMap containing the OAuth2
    client's ID.
    """

    config_map: ServiceMonitorSpecEndpointsItemOauth2ClientIdConfigMap | None = Field(default=None, alias="configMap")
    """ConfigMap containing data to use for the targets."""

    secret: ServiceMonitorSpecEndpointsItemOauth2ClientIdSecret | None = None
    """Secret containing data to use for the targets."""


class ServiceMonitorSpecEndpointsItemOauth2ClientSecret(_Model):
    """`clientSecret` specifies a key of a Secret containing the OAuth2 client's
    secret.
    """

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2ProxyConnectHeaderValueItem(_Model):
    """SecretKeySelector selects a key of a Secret."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCaConfigMap(_Model):
    """ConfigMap containing data to use for the targets."""

    key: str
    """The key to select."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the ConfigMap or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCaSecret(_Model):
    """Secret containing data to use for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCa(_Model):
    """Certificate authority used when verifying server certificates."""

    config_map: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCaConfigMap | None = Field(default=None, alias="configMap")
    """ConfigMap containing data to use for the targets."""

    secret: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCaSecret | None = None
    """Secret containing data to use for the targets."""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCertConfigMap(_Model):
    """ConfigMap containing data to use for the targets."""

    key: str
    """The key to select."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the ConfigMap or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCertSecret(_Model):
    """Secret containing data to use for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigCert(_Model):
    """Client certificate to present when doing client-authentication."""

    config_map: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCertConfigMap | None = Field(default=None, alias="configMap")
    """ConfigMap containing data to use for the targets."""

    secret: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCertSecret | None = None
    """Secret containing data to use for the targets."""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfigKeySecret(_Model):
    """Secret containing the client key file for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemOauth2TlsConfig(_Model):
    """TLS configuration to use when connecting to the OAuth2 server. It requires
    Prometheus >= v2.43.0.
    """

    ca: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCa | None = None
    """Certificate authority used when verifying server certificates."""

    cert: ServiceMonitorSpecEndpointsItemOauth2TlsConfigCert | None = None
    """Client certificate to present when doing client-authentication."""

    insecure_skip_verify: bool | None = Field(default=None, alias="insecureSkipVerify")
    """Disable target certificate validation."""

    key_secret: ServiceMonitorSpecEndpointsItemOauth2TlsConfigKeySecret | None = Field(default=None, alias="keySecret")
    """Secret containing the client key file for the targets."""

    max_version: Literal["TLS10", "TLS11", "TLS12", "TLS13"] | None = Field(default=None, alias="maxVersion")
    """Maximum acceptable TLS version."""

    min_version: Literal["TLS10", "TLS11", "TLS12", "TLS13"] | None = Field(default=None, alias="minVersion")
    """Minimum acceptable TLS version."""

    server_name: str | None = Field(default=None, alias="serverName")
    """Used to verify the hostname for the targets."""


class ServiceMonitorSpecEndpointsItemOauth2(_Model):
    """`oauth2` configures the OAuth2 settings to use when scraping the target."""

    client_id: ServiceMonitorSpecEndpointsItemOauth2ClientId = Field(alias="clientId")
    """`clientId` specifies a key of a Secret or ConfigMap containing the OAuth2
    client's ID.
    """

    client_secret: ServiceMonitorSpecEndpointsItemOauth2ClientSecret = Field(alias="clientSecret")
    """`clientSecret` specifies a key of a Secret containing the OAuth2 client's
    secret.
    """

    endpoint_params: dict[str, str] | None = Field(default=None, alias="endpointParams")
    """`endpointParams` configures the HTTP parameters to append to the token URL."""

    no_proxy: str | None = Field(default=None, alias="noProxy")
    """`noProxy` is a comma-separated string that can contain IPs, CIDR notation,
    domain names that should be excluded from proxying. IP and domain names can
    contain port numbers.
    """

    proxy_connect_header: dict[str, list[ServiceMonitorSpecEndpointsItemOauth2ProxyConnectHeaderValueItem]] | None = Field(default=None, alias="proxyConnectHeader")
    """ProxyConnectHeader optionally specifies headers to send to proxies during
    CONNECT requests.
    """

    proxy_from_environment: bool | None = Field(default=None, alias="proxyFromEnvironment")
    """Whether to use the proxy configuration defined by environment variables
    (HTTP_PROXY, HTTPS_PROXY, and NO_PROXY).
    """

    proxy_url: Annotated[str, Field(pattern="^http(s)?://.+$")] | None = Field(default=None, alias="proxyUrl")
    """`proxyURL` defines the HTTP proxy server to use."""

    scopes: list[str] | None = None
    """`scopes` defines the OAuth2 scopes used for the token request."""

    tls_config: ServiceMonitorSpecEndpointsItemOauth2TlsConfig | None = Field(default=None, alias="tlsConfig")
    """TLS configuration to use when connecting to the OAuth2 server. It requires
    Prometheus >= v2.43.0.
    """

    token_url: Annotated[str, Field(min_length=1)] = Field(alias="tokenUrl")
    """`tokenURL` configures the URL to fetch the token from."""


class ServiceMonitorSpecEndpointsItemRelabelingsItem(_Model):
    """RelabelConfig allows dynamic rewriting of the label set for targets,
    alerts, scraped samples and remote write samples.
    """

    action: Literal["replace", "Replace", "keep", "Keep", "drop", "Drop", "hashmod", "HashMod", "labelmap", "LabelMap", "labeldrop", "LabelDrop", "labelkeep", "LabelKeep", "lowercase", "Lowercase", "uppercase", "Uppercase", "keepequal", "KeepEqual", "dropequal", "DropEqual"] | None = None
    """Action to perform based on the regex matching."""

    modulus: int | None = None
    """Modulus to take of the hash of the source label values."""

    regex: str | None = None
    """Regular expression against which the extracted value is matched."""

    replacement: str | None = None
    """Replacement value against which a Replace action is performed if the
    regular expression matches.
    """

    separator: str | None = None
    """Separator is the string between concatenated SourceLabels."""

    source_labels: list[Annotated[str, Field(pattern="^[a-zA-Z_][a-zA-Z0-9_]*$")]] | None = Field(default=None, alias="sourceLabels")
    """The source labels select values from existing labels. Their content is
    concatenated using the configured Separator and matched against the
    configured regular expression.
    """

    target_label: str | None = Field(default=None, alias="targetLabel")
    """Label to which the resulting string is written in a replacement."""


class ServiceMonitorSpecEndpointsItemTlsConfigCaConfigMap(_Model):
    """ConfigMap containing data to use for the targets."""

    key: str
    """The key to select."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the ConfigMap or its key must be defined"""


class ServiceMonitorSpecEndpointsItemTlsConfigCaSecret(_Model):
    """Secret containing data to use for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemTlsConfigCa(_Model):
    """Certificate authority used when verifying server certificates."""

    config_map: ServiceMonitorSpecEndpointsItemTlsConfigCaConfigMap | None = Field(default=None, alias="configMap")
    """ConfigMap containing data to use for the targets."""

    secret: ServiceMonitorSpecEndpointsItemTlsConfigCaSecret | None = None
    """Secret containing data to use for the targets."""


class ServiceMonitorSpecEndpointsItemTlsConfigCertConfigMap(_Model):
    """ConfigMap containing data to use for the targets."""

    key: str
    """The key to select."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the ConfigMap or its key must be defined"""


class ServiceMonitorSpecEndpointsItemTlsConfigCertSecret(_Model):
    """Secret containing data to use for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemTlsConfigCert(_Model):
    """Client certificate to present when doing client-authentication."""

    config_map: ServiceMonitorSpecEndpointsItemTlsConfigCertConfigMap | None = Field(default=None, alias="configMap")
    """ConfigMap containing data to use for the targets."""

    secret: ServiceMonitorSpecEndpointsItemTlsConfigCertSecret | None = None
    """Secret containing data to use for the targets."""


class ServiceMonitorSpecEndpointsItemTlsConfigKeySecret(_Model):
    """Secret containing the client key file for the targets."""

    key: str
    """The key of the secret to select from. Must be a valid secret key."""

    name: str | None = None
    """Name of the referent. This field is effectively required, but due to
    backwards compatibility is allowed to be empty. Instances of this type with
    an empty value here are almost certainly wrong. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """

    optional: bool | None = None
    """Specify whether the Secret or its key must be defined"""


class ServiceMonitorSpecEndpointsItemTlsConfig(_Model):
    """TLS configuration to use when scraping the target."""

    ca: ServiceMonitorSpecEndpointsItemTlsConfigCa | None = None
    """Certificate authority used when verifying server certificates."""

    ca_file: str | None = Field(default=None, alias="caFile")
    """Path to the CA cert in the Prometheus container to use for the targets."""

    cert: ServiceMonitorSpecEndpointsItemTlsConfigCert | None = None
    """Client certificate to present when doing client-authentication."""

    cert_file: str | None = Field(default=None, alias="certFile")
    """Path to the client cert file in the Prometheus container for the targets."""

    insecure_skip_verify: bool | None = Field(default=None, alias="insecureSkipVerify")
    """Disable target certificate validation."""

    key_file: str | None = Field(default=None, alias="keyFile")
    """Path to the client key file in the Prometheus container for the targets."""

    key_secret: ServiceMonitorSpecEndpointsItemTlsConfigKeySecret | None = Field(default=None, alias="keySecret")
    """Secret containing the client key file for the targets."""

    max_version: Literal["TLS10", "TLS11", "TLS12", "TLS13"] | None = Field(default=None, alias="maxVersion")
    """Maximum acceptable TLS version."""

    min_version: Literal["TLS10", "TLS11", "TLS12", "TLS13"] | None = Field(default=None, alias="minVersion")
    """Minimum acceptable TLS version."""

    server_name: str | None = Field(default=None, alias="serverName")
    """Used to verify the hostname for the targets."""


class ServiceMonitorSpecEndpointsItem(_Model):
    """Endpoint defines an endpoint serving Prometheus metrics to be scraped by
    Prometheus.
    """

    authorization: ServiceMonitorSpecEndpointsItemAuthorization | None = None
    """`authorization` configures the Authorization header credentials to use when
    scraping the target.
    """

    basic_auth: ServiceMonitorSpecEndpointsItemBasicAuth | None = Field(default=None, alias="basicAuth")
    """`basicAuth` configures the Basic Authentication credentials to use when
    scraping the target.
    """

    bearer_token_file: str | None = Field(default=None, alias="bearerTokenFile")
    """File to read bearer token for scraping the target."""

    bearer_token_secret: ServiceMonitorSpecEndpointsItemBearerTokenSecret | None = Field(default=None, alias="bearerTokenSecret")
    """`bearerTokenSecret` specifies a key of a Secret containing the bearer token
    for scraping targets. The secret needs to be in the same namespace as the
    ServiceMonitor object and readable by the Prometheus Operator.
    """

    enable_http2: bool | None = Field(default=None, alias="enableHttp2")
    """`enableHttp2` can be used to disable HTTP2 when scraping the target."""

    filter_running: bool | None = Field(default=None, alias="filterRunning")
    """When true, the pods which are not running (e.g. either in Failed or
    Succeeded state) are dropped during the target discovery.
    """

    follow_redirects: bool | None = Field(default=None, alias="followRedirects")
    """`followRedirects` defines whether the scrape requests should follow HTTP
    3xx redirects.
    """

    honor_labels: bool | None = Field(default=None, alias="honorLabels")
    """When true, `honorLabels` preserves the metric's labels when they collide
    with the target's labels.
    """

    honor_timestamps: bool | None = Field(default=None, alias="honorTimestamps")
    """`honorTimestamps` controls whether Prometheus preserves the timestamps when
    exposed by the target.
    """

    interval: Annotated[str, Field(pattern="^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$")] | None = None
    """Interval at which Prometheus scrapes the metrics from the target."""

    metric_relabelings: list[ServiceMonitorSpecEndpointsItemMetricRelabelingsItem] | None = Field(default=None, alias="metricRelabelings")
    """`metricRelabelings` configures the relabeling rules to apply to the samples
    before ingestion.
    """

    oauth2: ServiceMonitorSpecEndpointsItemOauth2 | None = None
    """`oauth2` configures the OAuth2 settings to use when scraping the target."""

    params: dict[str, list[str]] | None = None
    """params define optional HTTP URL parameters."""

    path: str | None = None
    """HTTP path from which to scrape for metrics."""

    port: str | None = None
    """Name of the Service port which this endpoint refers to."""

    proxy_url: str | None = Field(default=None, alias="proxyUrl")
    """`proxyURL` configures the HTTP Proxy URL (e.g. "http://proxyserver:2195")
    to go through when scraping the target.
    """

    relabelings: list[ServiceMonitorSpecEndpointsItemRelabelingsItem] | None = None
    """`relabelings` configures the relabeling rules to apply the target's
    metadata labels.
    """

    scheme: Literal["http", "https"] | None = None
    """HTTP scheme to use for scraping."""

    scrape_timeout: Annotated[str, Field(pattern="^(0|(([0-9]+)y)?(([0-9]+)w)?(([0-9]+)d)?(([0-9]+)h)?(([0-9]+)m)?(([0-9]+)s)?(([0-9]+)ms)?)$")] | None = Field(default=None, alias="scrapeTimeout")
    """Timeout after which Prometheus considers the scrape to be failed."""

    target_port: int | str | None = Field(default=None, alias="targetPort")
    """Name or number of the target port of the `Pod` object behind the Service.
    The port must be specified with the container's port property.
    """

    tls_config: ServiceMonitorSpecEndpointsItemTlsConfig | None = Field(default=None, alias="tlsConfig")
    """TLS configuration to use when scraping the target."""

    track_timestamps_staleness: bool | None = Field(default=None, alias="trackTimestampsStaleness")
    """`trackTimestampsStaleness` defines whether Prometheus tracks staleness of
    the metrics that have an explicit timestamp present in scraped data. Has no
    effect if `honorTimestamps` is false.
    """


class ServiceMonitorSpecNamespaceSelector(_Model):
    """`namespaceSelector` defines in which namespace(s) Prometheus should
    discover the services. By default, the services are discovered in the same
    namespace as the `ServiceMonitor` object but it is possible to select pods
    across different/all namespaces.
    """

    any: bool | None = None
    """Boolean describing whether all namespaces are selected in contrast to a
    list restricting them.
    """

    match_names: list[str] | None = Field(default=None, alias="matchNames")
    """List of namespace names to select from."""


class ServiceMonitorSpecSelectorMatchExpressionsItem(_Model):
    """A label selector requirement is a selector that contains values, a key, and
    an operator that relates the key and values.
    """

    key: str
    """key is the label key that the selector applies to."""

    operator: str
    """operator represents a key's relationship to a set of values. Valid
    operators are In, NotIn, Exists and DoesNotExist.
    """

    values: list[str] | None = None
    """values is an array of string values. If the operator is In or NotIn, the
    values array must be non-empty. If the operator is Exists or DoesNotExist,
    the values array must be empty. This array is replaced during a strategic
    merge patch.
    """


class ServiceMonitorSpecSelector(_Model):
    """Label selector to select the Kubernetes `Endpoints` objects to scrape
    metrics from.
    """

    match_expressions: list[ServiceMonitorSpecSelectorMatchExpressionsItem] | None = Field(default=None, alias="matchExpressions")
    """matchExpressions is a list of label selector requirements. The requirements
    are ANDed.
    """

    match_labels: dict[str, str] | None = Field(default=None, alias="matchLabels")
    """matchLabels is a map of {key,value} pairs. A single {key,value} in the
    matchLabels map is equivalent to an element of matchExpressions, whose key
    field is "key", the operator is "In", and the values array contains only
    "value". The requirements are ANDed.
    """


class ServiceMonitorSpec(_Model):
    """Specification of desired Service selection for target discovery by
    Prometheus.
    """

    piceli_api_version: ClassVar[str] = API_VERSION
    piceli_kind: ClassVar[str] = KIND
    piceli_scope: ClassVar[str] = SCOPE

    attach_metadata: ServiceMonitorSpecAttachMetadata | None = Field(default=None, alias="attachMetadata")
    """`attachMetadata` defines additional metadata which is added to the
    discovered targets.
    """

    body_size_limit: Annotated[str, Field(pattern="(^0|([0-9]*[.])?[0-9]+((K|M|G|T|E|P)i?)?B)$")] | None = Field(default=None, alias="bodySizeLimit")
    """When defined, bodySizeLimit specifies a job level limit on the size of
    uncompressed response body that will be accepted by Prometheus.
    """

    endpoints: list[ServiceMonitorSpecEndpointsItem]
    """List of endpoints part of this ServiceMonitor. Defines how to scrape
    metrics from Kubernetes
    [Endpoints](https://kubernetes.io/docs/concepts/services-networking/service/#endpoints)
    objects. In most cases, an Endpoints object is backed by a Kubernetes
    [Service](https://kubernetes.io/docs/concepts/services-networking/service/)
    object with the same name and labels.
    """

    job_label: str | None = Field(default=None, alias="jobLabel")
    """`jobLabel` selects the label from the associated Kubernetes `Service`
    object which will be used as the `job` label for all metrics.
    """

    keep_dropped_targets: int | None = Field(default=None, alias="keepDroppedTargets")
    """Per-scrape limit on the number of targets dropped by relabeling that will
    be kept in memory. 0 means no limit.
    """

    label_limit: int | None = Field(default=None, alias="labelLimit")
    """Per-scrape limit on number of labels that will be accepted for a sample."""

    label_name_length_limit: int | None = Field(default=None, alias="labelNameLengthLimit")
    """Per-scrape limit on length of labels name that will be accepted for a
    sample.
    """

    label_value_length_limit: int | None = Field(default=None, alias="labelValueLengthLimit")
    """Per-scrape limit on length of labels value that will be accepted for a
    sample.
    """

    namespace_selector: ServiceMonitorSpecNamespaceSelector | None = Field(default=None, alias="namespaceSelector")
    """`namespaceSelector` defines in which namespace(s) Prometheus should
    discover the services. By default, the services are discovered in the same
    namespace as the `ServiceMonitor` object but it is possible to select pods
    across different/all namespaces.
    """

    native_histogram_bucket_limit: int | None = Field(default=None, alias="nativeHistogramBucketLimit")
    """If there are more than this many buckets in a native histogram, buckets
    will be merged to stay within the limit. It requires Prometheus >= v2.45.0.
    """

    native_histogram_min_bucket_factor: int | str | None = Field(default=None, alias="nativeHistogramMinBucketFactor")
    """If the growth factor of one bucket to the next is smaller than this,
    buckets will be merged to increase the factor sufficiently. It requires
    Prometheus >= v2.50.0.
    """

    pod_target_labels: list[str] | None = Field(default=None, alias="podTargetLabels")
    """`podTargetLabels` defines the labels which are transferred from the
    associated Kubernetes `Pod` object onto the ingested metrics.
    """

    sample_limit: int | None = Field(default=None, alias="sampleLimit")
    """`sampleLimit` defines a per-scrape limit on the number of scraped samples
    that will be accepted.
    """

    scrape_class: Annotated[str, Field(min_length=1)] | None = Field(default=None, alias="scrapeClass")
    """The scrape class to apply."""

    scrape_classic_histograms: bool | None = Field(default=None, alias="scrapeClassicHistograms")
    """Whether to scrape a classic histogram that is also exposed as a native
    histogram. It requires Prometheus >= v2.45.0.
    """

    scrape_protocols: list[Literal["PrometheusProto", "OpenMetricsText0.0.1", "OpenMetricsText1.0.0", "PrometheusText0.0.4"]] | None = Field(default=None, alias="scrapeProtocols")
    """`scrapeProtocols` defines the protocols to negotiate during a scrape. It
    tells clients the protocols supported by Prometheus in order of preference
    (from most to least preferred).
    """

    selector: ServiceMonitorSpecSelector
    """Label selector to select the Kubernetes `Endpoints` objects to scrape
    metrics from.
    """

    target_labels: list[str] | None = Field(default=None, alias="targetLabels")
    """`targetLabels` defines the labels which are transferred from the associated
    Kubernetes `Service` object onto the ingested metrics.
    """

    target_limit: int | None = Field(default=None, alias="targetLimit")
    """`targetLimit` defines a limit on the number of scraped targets that will be
    accepted.
    """
