import React from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { BrowserRouter } from 'react-router-dom';
import { basePath } from './api/client';
import { App } from './app/App';
import './styles/app.css';
import './styles/workspace.css';
const client = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: 10_000, refetchInterval: 15_000, refetchOnWindowFocus: true } } });
createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter basename={basePath() || '/'}><App /></BrowserRouter></QueryClientProvider></React.StrictMode>);
