"""``piceli codegen crd``: generate pydantic models from a CustomResourceDefinition.

Contract (see ``docs/crds.md``):

- Reads one CRD from a local YAML/JSON file, or with ``--from-cluster`` from a
  cluster through an explicit ``--kubeconfig`` and ``--context`` (one GET of
  the CRD; never writes to the cluster; exec credential plugins only with
  ``--allow-exec``).
- Without ``--out``, stdout carries the module source (or with ``--json`` one
  JSON object that includes it as ``module``). With ``--out FILE`` the module
  is written there and stdout carries one JSON summary object. An existing
  file is replaced only when Piceli generated it (or with ``--force``).
  Human text goes to stderr.
- Exit codes: ``0`` generated, ``2`` rejected (``{"state": "rejected",
  "reason": "<code>"}`` on stdout).
- Safe to retry: the output depends only on the CRD's schema.
"""

from __future__ import annotations

import json
import os
import tempfile
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any

import typer

from piceli.cli_contract import emit_json, reject, reject_error, say

app = typer.Typer(
    rich_markup_mode=None,
    help="Generate typed Python models from Kubernetes schemas.",
    no_args_is_help=True,
)

#: The first line every generated module starts with (``--out`` may replace it).
_MARKER = '"""Typed models for the '


class Transport(StrEnum):
    https = "https"
    loopback_http = "loopback-http"


def _read_cluster(
    kubeconfig: Path,
    context: str,
    name: str,
    transport: str,
    allow_exec: bool,
    exec_sha256: str | None,
) -> dict[str, Any]:
    """GET one CRD through an explicit kubeconfig and context (read-only)."""
    from kubernetes.client import ApiextensionsV1Api
    from kubernetes.client.exceptions import ApiException

    from piceli.k8s.ops.exec_credentials import ExecPolicy
    from piceli.k8s.ops.provider_factory import (
        ProviderFactoryError,
        api_client_from_kubeconfig,
    )

    try:
        policy = ExecPolicy(allow_exec, exec_sha256)
        client = api_client_from_kubeconfig(
            kubeconfig,
            context,
            transport=transport,  # type: ignore[arg-type]
            exec_policy=policy,
        )
    except ProviderFactoryError as error:
        reject_error(error, "target-refused")
    except ValueError as error:
        reject("target-refused", str(error))
    try:
        response = ApiextensionsV1Api(client).read_custom_resource_definition(
            name, _preload_content=False, _request_timeout=10
        )
        document = json.loads(response.data)
    except ApiException as error:
        if error.status == 404:
            reject("crd-not-found", f"the cluster has no CRD named {name!r}")
        reject(
            "codegen-cluster-read-failed",
            f"reading the CRD failed with HTTP {error.status}",
        )
    except Exception as error:  # transport details may hold credentials
        reject(
            "codegen-cluster-read-failed",
            f"reading the CRD failed: {type(error).__name__}",
        )
    finally:
        close = getattr(client, "close", None)
        if callable(close):
            close()
    if not isinstance(document, dict):
        reject("codegen-cluster-read-failed", "the CRD response is not an object")
    return document


def _write(path: Path, text: str, force: bool) -> None:
    if not path.parent.is_dir():
        say(f"directory {path.parent} does not exist")
        reject("codegen-output-refused")
    if path.exists() and not force:
        try:
            generated = path.read_text().startswith(_MARKER)
        except (OSError, UnicodeDecodeError):
            generated = False
        if not generated:
            say(f"{path} exists and was not generated by piceli; pass --force")
            reject("codegen-output-refused")
    handle, temporary = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    try:
        with os.fdopen(handle, "w") as stream:
            stream.write(text)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


@app.command("crd")
def crd(
    file: Annotated[
        Path | None,
        typer.Argument(
            help="CRD file (YAML or JSON; several documents or a List allowed)",
            dir_okay=False,
            show_default=False,
        ),
    ] = None,
    name: Annotated[
        str | None,
        typer.Option(
            "--crd",
            help="CRD name (plural.group) or kind; required with --from-cluster "
            "or when the file holds several CRDs",
            show_default=False,
        ),
    ] = None,
    version: Annotated[
        str | None,
        typer.Option(
            "--version",
            help="CRD version to generate (default: the storage version)",
            show_default=False,
        ),
    ] = None,
    from_cluster: Annotated[
        bool,
        typer.Option(
            "--from-cluster",
            help="Read the CRD from a cluster (--kubeconfig, --context, --crd)",
        ),
    ] = False,
    kubeconfig: Annotated[
        Path | None,
        typer.Option(
            "--kubeconfig",
            help="Explicit kubeconfig file (never ~/.kube/config or KUBECONFIG)",
            dir_okay=False,
            show_default=False,
        ),
    ] = None,
    context: Annotated[
        str | None,
        typer.Option(
            "--context",
            help="Explicit context (never current-context)",
            show_default=False,
        ),
    ] = None,
    transport: Annotated[
        Transport,
        typer.Option(
            "--transport",
            help="https, or loopback-http for a local test API server only",
        ),
    ] = Transport.https,
    allow_exec: Annotated[
        bool,
        typer.Option(
            "--allow-exec",
            help="Allow the context's exec credential plugin (GKE, EKS, AKS, OIDC)",
        ),
    ] = False,
    exec_sha256: Annotated[
        str | None,
        typer.Option(
            "--exec-sha256",
            help="Expected sha256:<hex> of the resolved exec plugin file",
            show_default=False,
        ),
    ] = None,
    out: Annotated[
        Path | None,
        typer.Option(
            "--out",
            help="Write the module here (stdout: a JSON summary)",
            dir_okay=False,
            show_default=False,
        ),
    ] = None,
    force: Annotated[
        bool,
        typer.Option(
            "--force", help="Overwrite an --out file that piceli did not generate"
        ),
    ] = False,
    as_json: Annotated[
        bool,
        typer.Option(
            "--json", help="Without --out: print one JSON object with the module"
        ),
    ] = False,
) -> None:
    """Generate pydantic models for one CRD version, from a file or a cluster."""
    from piceli.codegen.crd import CodegenError, generate, load_crds, select_crd

    if from_cluster == (file is not None):
        say("pass a CRD file, or --from-cluster with --kubeconfig, --context and --crd")
        reject("codegen-flags-conflict")
    if from_cluster and (kubeconfig is None or not context or not name):
        say("--from-cluster needs --kubeconfig, --context and --crd NAME")
        reject("codegen-flags-conflict")
    if not from_cluster and (
        kubeconfig is not None
        or context is not None
        or allow_exec
        or exec_sha256 is not None
    ):
        say("--kubeconfig, --context and exec options only apply with --from-cluster")
        reject("codegen-flags-conflict")
    try:
        if from_cluster:
            assert kubeconfig is not None and context is not None and name is not None
            document = _read_cluster(
                kubeconfig, context, name, transport.value, allow_exec, exec_sha256
            )
            chosen = select_crd(load_crds(json.dumps(document)), None)
        else:
            assert file is not None
            try:
                text = file.read_text()
            except (OSError, UnicodeDecodeError):
                reject("crd-invalid", "the CRD file cannot be read")
            chosen = select_crd(load_crds(text), name)
        module = generate(chosen, version=version)
    except CodegenError as error:
        say(str(error))
        reject(error.code, str(error))
    summary = module.summary()
    say(
        f"generated {len(module.classes)} models for {module.kind} "
        f"({module.api_version}, {module.scope}) from {module.crd}"
    )
    if out is not None:
        _write(out, module.source, force)
        say(f"wrote {out}")
        emit_json({"state": "generated", "out": str(out), **summary})
    elif as_json:
        emit_json(
            {"state": "generated", "out": None, "module": module.source, **summary}
        )
    else:
        typer.echo(module.source, nl=False)
