"""Typed models for the ``Certificate`` custom resource (``cert-manager.io/v1``).

Generated by ``piceli codegen crd``; do not edit. Source:
CustomResourceDefinition ``certificates.cert-manager.io``, version ``v1``.
The output depends only on the schema: the same CRD, from a file or
from a cluster, always generates this file.

Use with ``app.resource(API_VERSION, KIND, name, CertificateSpec(...))``.
"""

# ruff: noqa

from __future__ import annotations

from typing import ClassVar, Literal

from pydantic import BaseModel, ConfigDict, Field

API_VERSION = "cert-manager.io/v1"
KIND = "Certificate"
SCOPE = "namespaced"
CRD = "certificates.cert-manager.io"
SCHEMA_SHA256 = "sha256:cbf5535634739cda36f10d6c510991e3fadb1507d1e1ca4a41be4a0711aed2ac"
GENERATOR = "piceli-codegen-crd/1"


class _Model(BaseModel):
    """Frozen; accepts Kubernetes names and snake_case; refuses unknown fields."""

    model_config = ConfigDict(
        extra="forbid", frozen=True, populate_by_name=True, regex_engine="python-re"
    )


class CertificateSpecAdditionalOutputFormatsItem(_Model):
    """CertificateAdditionalOutputFormat defines an additional output format of a
    Certificate resource. These contain supplementary data formats of the
    signed certificate chain and paired private key.
    """

    type: Literal["DER", "CombinedPEM"]
    """Type is the name of the format type that should be written to the
    Certificate's target Secret.
    """


class CertificateSpecIssuerRef(_Model):
    """Reference to the issuer responsible for issuing the certificate. If the
    issuer is namespace-scoped, it must be in the same namespace as the
    Certificate. If the issuer is cluster-scoped, it can be used from any
    namespace.
    """

    group: str | None = None
    """Group of the resource being referred to."""

    kind: str | None = None
    """Kind of the resource being referred to."""

    name: str
    """Name of the resource being referred to."""


class CertificateSpecKeystoresJksPasswordSecretRef(_Model):
    """PasswordSecretRef is a reference to a key in a Secret resource containing
    the password used to encrypt the JKS keystore.
    """

    key: str | None = None
    """The key of the entry in the Secret resource's `data` field to be used. Some
    instances of this field may be defaulted, in others it may be required.
    """

    name: str
    """Name of the resource being referred to. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """


class CertificateSpecKeystoresJks(_Model):
    """JKS configures options for storing a JKS keystore in the `spec.secretName`
    Secret resource.
    """

    alias: str | None = None
    """Alias specifies the alias of the key in the keystore, required by the JKS
    format. If not provided, the default alias `certificate` will be used.
    """

    create: bool
    """Create enables JKS keystore creation for the Certificate. If true, a file
    named `keystore.jks` will be created in the target Secret resource,
    encrypted using the password stored in `passwordSecretRef`. The keystore
    file will be updated immediately. If the issuer provided a CA certificate,
    a file named `truststore.jks` will also be created in the target Secret
    resource, encrypted using the password stored in `passwordSecretRef`
    containing the issuing Certificate Authority
    """

    password_secret_ref: CertificateSpecKeystoresJksPasswordSecretRef = Field(alias="passwordSecretRef")
    """PasswordSecretRef is a reference to a key in a Secret resource containing
    the password used to encrypt the JKS keystore.
    """


class CertificateSpecKeystoresPkcs12PasswordSecretRef(_Model):
    """PasswordSecretRef is a reference to a key in a Secret resource containing
    the password used to encrypt the PKCS12 keystore.
    """

    key: str | None = None
    """The key of the entry in the Secret resource's `data` field to be used. Some
    instances of this field may be defaulted, in others it may be required.
    """

    name: str
    """Name of the resource being referred to. More info:
    https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
    """


class CertificateSpecKeystoresPkcs12(_Model):
    """PKCS12 configures options for storing a PKCS12 keystore in the
    `spec.secretName` Secret resource.
    """

    create: bool
    """Create enables PKCS12 keystore creation for the Certificate. If true, a
    file named `keystore.p12` will be created in the target Secret resource,
    encrypted using the password stored in `passwordSecretRef`. The keystore
    file will be updated immediately. If the issuer provided a CA certificate,
    a file named `truststore.p12` will also be created in the target Secret
    resource, encrypted using the password stored in `passwordSecretRef`
    containing the issuing Certificate Authority
    """

    password_secret_ref: CertificateSpecKeystoresPkcs12PasswordSecretRef = Field(alias="passwordSecretRef")
    """PasswordSecretRef is a reference to a key in a Secret resource containing
    the password used to encrypt the PKCS12 keystore.
    """

    profile: Literal["LegacyRC2", "LegacyDES", "Modern2023"] | None = None
    """Profile specifies the key and certificate encryption algorithms and the
    HMAC algorithm used to create the PKCS12 keystore. Default value is
    `LegacyRC2` for backward compatibility.
    """


class CertificateSpecKeystores(_Model):
    """Additional keystore output formats to be stored in the Certificate's
    Secret.
    """

    jks: CertificateSpecKeystoresJks | None = None
    """JKS configures options for storing a JKS keystore in the `spec.secretName`
    Secret resource.
    """

    pkcs12: CertificateSpecKeystoresPkcs12 | None = None
    """PKCS12 configures options for storing a PKCS12 keystore in the
    `spec.secretName` Secret resource.
    """


class CertificateSpecNameConstraintsExcluded(_Model):
    """Excluded contains the constraints which must be disallowed. Any name
    matching a restriction in the excluded field is invalid regardless of
    information appearing in the permitted
    """

    dns_domains: list[str] | None = Field(default=None, alias="dnsDomains")
    """DNSDomains is a list of DNS domains that are permitted or excluded."""

    email_addresses: list[str] | None = Field(default=None, alias="emailAddresses")
    """EmailAddresses is a list of Email Addresses that are permitted or excluded."""

    ip_ranges: list[str] | None = Field(default=None, alias="ipRanges")
    """IPRanges is a list of IP Ranges that are permitted or excluded. This should
    be a valid CIDR notation.
    """

    uri_domains: list[str] | None = Field(default=None, alias="uriDomains")
    """URIDomains is a list of URI domains that are permitted or excluded."""


class CertificateSpecNameConstraintsPermitted(_Model):
    """Permitted contains the constraints in which the names must be located."""

    dns_domains: list[str] | None = Field(default=None, alias="dnsDomains")
    """DNSDomains is a list of DNS domains that are permitted or excluded."""

    email_addresses: list[str] | None = Field(default=None, alias="emailAddresses")
    """EmailAddresses is a list of Email Addresses that are permitted or excluded."""

    ip_ranges: list[str] | None = Field(default=None, alias="ipRanges")
    """IPRanges is a list of IP Ranges that are permitted or excluded. This should
    be a valid CIDR notation.
    """

    uri_domains: list[str] | None = Field(default=None, alias="uriDomains")
    """URIDomains is a list of URI domains that are permitted or excluded."""


class CertificateSpecNameConstraints(_Model):
    """x.509 certificate NameConstraint extension which MUST NOT be used in a
    non-CA certificate. More Info:
    https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.10
    """

    critical: bool | None = None
    """if true then the name constraints are marked critical."""

    excluded: CertificateSpecNameConstraintsExcluded | None = None
    """Excluded contains the constraints which must be disallowed. Any name
    matching a restriction in the excluded field is invalid regardless of
    information appearing in the permitted
    """

    permitted: CertificateSpecNameConstraintsPermitted | None = None
    """Permitted contains the constraints in which the names must be located."""


class CertificateSpecOtherNamesItem(_Model):
    """(No description in the schema.)"""

    oid: str | None = None
    """OID is the object identifier for the otherName SAN. The object identifier
    must be expressed as a dotted string, for example,
    "1.2.840.113556.1.4.221".
    """

    utf8_value: str | None = Field(default=None, alias="utf8Value")
    """utf8Value is the string value of the otherName SAN. The utf8Value accepts
    any valid UTF8 string to set as value for the otherName SAN.
    """


class CertificateSpecPrivateKey(_Model):
    """Private key options. These include the key algorithm and size, the used
    encoding and the rotation policy.
    """

    algorithm: Literal["RSA", "ECDSA", "Ed25519"] | None = None
    """Algorithm is the private key algorithm of the corresponding private key for
    this certificate.
    """

    encoding: Literal["PKCS1", "PKCS8"] | None = None
    """The private key cryptography standards (PKCS) encoding for this
    certificate's private key to be encoded in.
    """

    rotation_policy: Literal["Never", "Always"] | None = Field(default=None, alias="rotationPolicy")
    """RotationPolicy controls how private keys should be regenerated when a
    re-issuance is being processed.
    """

    size: int | None = None
    """Size is the key bit size of the corresponding private key for this
    certificate.
    """


class CertificateSpecSecretTemplate(_Model):
    """Defines annotations and labels to be copied to the Certificate's Secret.
    Labels and annotations on the Secret will be changed as they appear on the
    SecretTemplate when added or removed. SecretTemplate annotations are added
    in conjunction with, and cannot overwrite, the base set of annotations
    cert-manager sets on the Certificate's Secret.
    """

    annotations: dict[str, str] | None = None
    """Annotations is a key value map to be copied to the target Kubernetes
    Secret.
    """

    labels: dict[str, str] | None = None
    """Labels is a key value map to be copied to the target Kubernetes Secret."""


class CertificateSpecSubject(_Model):
    """Requested set of X509 certificate subject attributes. More info:
    https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.6
    """

    countries: list[str] | None = None
    """Countries to be used on the Certificate."""

    localities: list[str] | None = None
    """Cities to be used on the Certificate."""

    organizational_units: list[str] | None = Field(default=None, alias="organizationalUnits")
    """Organizational Units to be used on the Certificate."""

    organizations: list[str] | None = None
    """Organizations to be used on the Certificate."""

    postal_codes: list[str] | None = Field(default=None, alias="postalCodes")
    """Postal codes to be used on the Certificate."""

    provinces: list[str] | None = None
    """State/Provinces to be used on the Certificate."""

    serial_number: str | None = Field(default=None, alias="serialNumber")
    """Serial number to be used on the Certificate."""

    street_addresses: list[str] | None = Field(default=None, alias="streetAddresses")
    """Street addresses to be used on the Certificate."""


class CertificateSpec(_Model):
    """Specification of the desired state of the Certificate resource.
    https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
    """

    piceli_api_version: ClassVar[str] = API_VERSION
    piceli_kind: ClassVar[str] = KIND
    piceli_scope: ClassVar[str] = SCOPE

    additional_output_formats: list[CertificateSpecAdditionalOutputFormatsItem] | None = Field(default=None, alias="additionalOutputFormats")
    """Defines extra output formats of the private key and signed certificate
    chain to be written to this Certificate's target Secret.
    """

    common_name: str | None = Field(default=None, alias="commonName")
    """Requested common name X509 certificate subject attribute. More info:
    https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.6 NOTE: TLS
    clients will ignore this value when any subject alternative name is set
    (see https://tools.ietf.org/html/rfc6125#section-6.4.4).
    """

    dns_names: list[str] | None = Field(default=None, alias="dnsNames")
    """Requested DNS subject alternative names."""

    duration: str | None = None
    """Requested 'duration' (i.e. lifetime) of the Certificate. Note that the
    issuer may choose to ignore the requested duration, just like any other
    requested attribute.
    """

    email_addresses: list[str] | None = Field(default=None, alias="emailAddresses")
    """Requested email subject alternative names."""

    encode_usages_in_request: bool | None = Field(default=None, alias="encodeUsagesInRequest")
    """Whether the KeyUsage and ExtKeyUsage extensions should be set in the
    encoded CSR.
    """

    ip_addresses: list[str] | None = Field(default=None, alias="ipAddresses")
    """Requested IP address subject alternative names."""

    is_ca: bool | None = Field(default=None, alias="isCA")
    """Requested basic constraints isCA value. The isCA value is used to set the
    `isCA` field on the created CertificateRequest resources. Note that the
    issuer may choose to ignore the requested isCA value, just like any other
    requested attribute.
    """

    issuer_ref: CertificateSpecIssuerRef = Field(alias="issuerRef")
    """Reference to the issuer responsible for issuing the certificate. If the
    issuer is namespace-scoped, it must be in the same namespace as the
    Certificate. If the issuer is cluster-scoped, it can be used from any
    namespace.
    """

    keystores: CertificateSpecKeystores | None = None
    """Additional keystore output formats to be stored in the Certificate's
    Secret.
    """

    literal_subject: str | None = Field(default=None, alias="literalSubject")
    """Requested X.509 certificate subject, represented using the LDAP "String
    Representation of a Distinguished Name" [1]. Important: the LDAP string
    format also specifies the order of the attributes in the subject, this is
    important when issuing certs for LDAP authentication. Example:
    `CN=foo,DC=corp,DC=example,DC=com` More info [1]:
    https://datatracker.ietf.org/doc/html/rfc4514 More info:
    https://github.com/cert-manager/cert-manager/issues/3203 More info:
    https://github.com/cert-manager/cert-manager/issues/4424
    """

    name_constraints: CertificateSpecNameConstraints | None = Field(default=None, alias="nameConstraints")
    """x.509 certificate NameConstraint extension which MUST NOT be used in a
    non-CA certificate. More Info:
    https://datatracker.ietf.org/doc/html/rfc5280#section-4.2.1.10
    """

    other_names: list[CertificateSpecOtherNamesItem] | None = Field(default=None, alias="otherNames")
    """`otherNames` is an escape hatch for SAN that allows any type. We currently
    restrict the support to string like otherNames, cf RFC 5280 p 37 Any UTF8
    String valued otherName can be passed with by setting the keys oid: x.x.x.x
    and UTF8Value: somevalue for `otherName`. Most commonly this would be UPN
    set with oid: 1.3.6.1.4.1.311.20.2.3 You should ensure that any OID passed
    is valid for the UTF8String type as we do not explicitly validate this.
    """

    private_key: CertificateSpecPrivateKey | None = Field(default=None, alias="privateKey")
    """Private key options. These include the key algorithm and size, the used
    encoding and the rotation policy.
    """

    renew_before: str | None = Field(default=None, alias="renewBefore")
    """How long before the currently issued certificate's expiry cert-manager
    should renew the certificate. For example, if a certificate is valid for 60
    minutes, and `renewBefore=10m`, cert-manager will begin to attempt to renew
    the certificate 50 minutes after it was issued (i.e. when there are 10
    minutes remaining until the certificate is no longer valid).
    """

    renew_before_percentage: int | None = Field(default=None, alias="renewBeforePercentage")
    """`renewBeforePercentage` is like `renewBefore`, except it is a relative
    percentage rather than an absolute duration. For example, if a certificate
    is valid for 60 minutes, and `renewBeforePercentage=25`, cert-manager will
    begin to attempt to renew the certificate 45 minutes after it was issued
    (i.e. when there are 15 minutes (25%) remaining until the certificate is no
    longer valid).
    """

    revision_history_limit: int | None = Field(default=None, alias="revisionHistoryLimit")
    """The maximum number of CertificateRequest revisions that are maintained in
    the Certificate's history. Each revision represents a single
    `CertificateRequest` created by this Certificate, either when it was
    created, renewed, or Spec was changed. Revisions will be removed by oldest
    first if the number of revisions exceeds this number.
    """

    secret_name: str = Field(alias="secretName")
    """Name of the Secret resource that will be automatically created and managed
    by this Certificate resource. It will be populated with a private key and
    certificate, signed by the denoted issuer. The Secret resource lives in the
    same namespace as the Certificate resource.
    """

    secret_template: CertificateSpecSecretTemplate | None = Field(default=None, alias="secretTemplate")
    """Defines annotations and labels to be copied to the Certificate's Secret.
    Labels and annotations on the Secret will be changed as they appear on the
    SecretTemplate when added or removed. SecretTemplate annotations are added
    in conjunction with, and cannot overwrite, the base set of annotations
    cert-manager sets on the Certificate's Secret.
    """

    subject: CertificateSpecSubject | None = None
    """Requested set of X509 certificate subject attributes. More info:
    https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.6
    """

    uris: list[str] | None = None
    """Requested URI subject alternative names."""

    usages: list[Literal["signing", "digital signature", "content commitment", "key encipherment", "key agreement", "data encipherment", "cert sign", "crl sign", "encipher only", "decipher only", "any", "server auth", "client auth", "code signing", "email protection", "s/mime", "ipsec end system", "ipsec tunnel", "ipsec user", "timestamping", "ocsp signing", "microsoft sgc", "netscape sgc"]] | None = None
    """Requested key usages and extended key usages. These usages are used to set
    the `usages` field on the created CertificateRequest resources. If
    `encodeUsagesInRequest` is unset or set to `true`, the usages will
    additionally be encoded in the `request` field which contains the CSR blob.
    """
