"""Building components and mirroring third-party images, one component at a time.

A component's ``build`` becomes a host build (:mod:`piceli.artifacts.host_build`,
no container VM) generated by :func:`host_build_document`:

- ``rust``: ``cargo zigbuild --release --locked`` of the crate's binary for
  the node's architecture (tools ``cargo``, ``cargo-zigbuild``, ``zig``),
  the binary at ``/usr/local/bin/<bin>`` and the entrypoint;
- ``python``: the package directory at ``/app/<dir>`` (byte-compiled with
  ``python3``), ``python3 -m <module>`` as the entrypoint;
- ``files``: the listed files and directories at their image paths (the
  tool ``true`` stands for "nothing to compile");
- ``dockerfile``: refused (``component-build-unsupported``): it needs a
  Docker engine, which neither the build Job nor the controller has.

Two builders run them and push each image by digest into the composition's
registry, returning the pull reference nodes use:

- :class:`LocalBuilder` builds on this machine (a laptop, a CI runner or a
  test) from a checkout of the source at its commit;
- :class:`JobBuilder` runs one Kubernetes Job on the builder node that
  fetches every source it needs at its resolved commit (one Git Secret for
  all) and builds every changed component (``piceli build job-run
  --component``), like the 0.13 cluster build.

Importing this module is side-effect free.
"""

from __future__ import annotations

import hashlib
import json
import re
import tempfile
import time
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Protocol

from piceli.infra import CompositionError
from piceli.infra.contract import ComponentContract

HOST_BUILD_REVISION = "piceli.host-build.v1"
_STAGE = "src"


def _unsupported(name: str, kind: str) -> CompositionError:
    return CompositionError(
        "component-build-unsupported",
        f"component {name!r}: a {kind} build needs a Docker engine; use a rust, "
        "python or files build",
    )


def host_build_document(
    name: str, contract: ComponentContract, source_root: Path, repository: str
) -> dict[str, Any]:
    """The ``host-build.toml`` (as a dict) that builds ``contract``'s image.

    :param source_root: The source's checkout (the build's paths are scanned
        in it to tell files from directories).
    :param repository: The image repository (``<prefix>/<component>``).
    """
    recipe = contract.build
    if recipe is None:
        raise CompositionError(
            "component-contract-invalid", f"component {name!r} has no build"
        )
    if recipe.kind == "dockerfile":
        raise _unsupported(name, recipe.kind)

    def include(path: str) -> list[str]:
        found = source_root.joinpath(*path.split("/"))
        return [f"{path}/**"] if found.is_dir() else [path]

    image = contract.image
    out: dict[str, Any] = {
        "name": name,
        "repository": repository,
        "user": f"{image.uid}:{image.gid}",
    }
    if image.base is not None:  # else ``scratch`` (a files build only)
        out["base"] = {"image": image.base, "digest": image.digest}
    if image.dirs:
        out["dirs"] = {
            path: f"{image.uid}:{image.gid}:{mode}" for path, mode in image.dirs
        }
    if image.workdir is not None:
        out["workdir"] = image.workdir
    globs = [glob for path in recipe.paths for glob in include(path)]
    build: dict[str, Any]
    if recipe.kind == "rust":
        command = [
            "cargo", "zigbuild", "--release", "--locked",
            "--target", "{rust_arch}-unknown-linux-gnu",
            "--manifest-path", f"{_STAGE}/{recipe.path}/Cargo.toml",
            "--bin", str(recipe.bin),
        ]  # fmt: skip
        if recipe.features:
            command += ["--features", ",".join(recipe.features)]
        build = {
            "tools": ["cargo", "cargo-zigbuild", "zig"],
            "commands": [command],
            "env": {"CARGO_TERM_COLOR": "never", "CARGO_INCREMENTAL": "0"},
        }
        binary = f"/usr/local/bin/{recipe.bin}"
        out["target_files"] = {
            f"{{rust_arch}}-unknown-linux-gnu/release/{recipe.bin}": binary
        }
        out["entrypoint"] = [binary]
    elif recipe.kind == "python":
        build = {
            "tools": ["python3"],
            "commands": [
                ["python3", "-m", "compileall", "-q", f"{_STAGE}/{recipe.path}"]
            ],
        }
        out["files"] = {f"{_STAGE}/{recipe.path}": f"/app/{recipe.path}"}
        out["entrypoint"] = ["python3", "-m", str(recipe.module)]
        out["env"] = {"PYTHONPATH": "/app"}
    else:
        build = {"tools": ["true"], "commands": [["true"]]}
        out["files"] = {f"{_STAGE}/{src}": dest for src, dest in recipe.files}
    if image.cmd is not None:
        out["cmd"] = list(image.cmd)
    return {
        "revision": HOST_BUILD_REVISION,
        "name": name,
        "build": {**build, "timeout_seconds": 1800},
        "context": {
            _STAGE: {
                "path": ".",
                "include": globs,
                "max_files": 100_000,
                "max_bytes": 1024 * 1024 * 1024,
            }
        },
        "output": {"image": [out]},
    }


@dataclass(frozen=True)
class BuildItem:
    """One component to build: its source at a commit and its digest."""

    component: str
    source: str
    commit: str
    digest: str
    contract: ComponentContract
    repository: str

    def describe(self) -> dict[str, Any]:
        return {
            "component": self.component,
            "source": self.source,
            "commit": self.commit,
            "digest": self.digest,
            "repository": self.repository,
        }


@dataclass(frozen=True)
class MirrorItem:
    """One third-party image to copy into the registry (``ref@pin``)."""

    component: str
    reference: str
    repository: str


@dataclass
class BuiltImage:
    """Where nodes pull a built or mirrored image from."""

    pull_ref: str
    manifest_digest: str
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "pull_ref": self.pull_ref,
            "manifest_digest": self.manifest_digest,
            **self.extra,
        }


class Builder(Protocol):
    """Builds components and mirrors images into the composition's registry."""

    def build(
        self, items: Sequence[BuildItem], checkout: Callable[[str, str, Path], Any]
    ) -> dict[str, BuiltImage]: ...

    def mirror(self, items: Sequence[MirrorItem]) -> dict[str, BuiltImage]: ...


def _pinned(receipt: Mapping[str, Any], what: str) -> BuiltImage:
    if receipt.get("state") != "succeeded" or not receipt.get("pull_ref"):
        raise CompositionError(
            "component-build-failed",
            f"{what}: delivery ended {receipt.get('result') or receipt.get('state')} "
            f"({receipt.get('reason')})",
        )
    ref = str(receipt["pull_ref"])
    return BuiltImage(ref, ref.rsplit("@", 1)[-1])


class LocalBuilder:
    """Build on this machine; push through a route to the registry.

    :param route: How this machine reaches the registry
        (:class:`piceli.pipeline.backend.RegistryRoute`).
    :param platform: The nodes' platform (``linux/amd64`` or ``linux/arm64``).
    :param cache_dir: The host build cache (stage, target, blobs).
    :param work_dir: Where checkouts and archives go (removed after each build).
    :param backend: :class:`piceli.pipeline.backend.Backend` (tests: a fake).
    """

    def __init__(
        self,
        route: Any,
        *,
        platform: str,
        cache_dir: Path,
        work_dir: Path,
        backend: Any = None,
        say: Callable[[str], None] = lambda _: None,
    ) -> None:
        self.route = route
        self.platform = platform
        self.cache_dir = cache_dir
        self.work_dir = work_dir
        self.backend = backend
        self.say = say

    def _backend(self) -> Any:
        if self.backend is None:
            from piceli.pipeline.backend import Backend

            self.backend = Backend()
        return self.backend

    def build(
        self, items: Sequence[BuildItem], checkout: Callable[[str, str, Path], Any]
    ) -> dict[str, BuiltImage]:
        from piceli.artifacts.build_spec import BuildSpecError
        from piceli.artifacts.host_build import HostBuildGrant, HostBuildSpec
        from piceli.artifacts.node_facts import NodeFacts

        built: dict[str, BuiltImage] = {}
        facts = NodeFacts.for_platform(self.platform)
        self.work_dir.mkdir(parents=True, exist_ok=True)
        for item in items:
            self.say(f"[build] {item.component} from {item.source}@{item.commit[:12]}")
            with (
                checkout(item.source, item.commit, self.work_dir) as tree,
                tempfile.TemporaryDirectory(prefix="out-", dir=self.work_dir) as out,
            ):
                document = host_build_document(
                    item.component, item.contract, Path(tree), item.repository
                )
                try:
                    spec = HostBuildSpec.from_dict(document, Path(tree))
                    spec = spec.for_node(facts).with_cache_dir(self.cache_dir)
                    plan = spec.plan()
                    grant = HostBuildGrant(plan.plan_hash, time.time() + 3600)
                    receipt = spec.run(grant, Path(out), progress=self.say).to_dict()
                except BuildSpecError as error:
                    raise CompositionError(
                        "component-build-failed",
                        f"component {item.component!r}: host build failed ({error.code})",
                    ) from None
                entry = receipt["outputs"]["images"][item.component]
                delivered = self._backend().registry_deliver(
                    self.route,
                    entry["image_id"],
                    item.repository,
                    archive=Path(out) / entry["archive"],
                )
                built[item.component] = _pinned(delivered, item.component)
        return built

    def mirror(self, items: Sequence[MirrorItem]) -> dict[str, BuiltImage]:
        done: dict[str, BuiltImage] = {}
        for item in items:
            self.say(f"[mirror] {item.component}: {item.reference}")
            receipt = self._backend().mirror_deliver(
                self.route,
                item.reference,
                item.repository,
                platform=None,  # the whole index: pulled by its digest
                credentials=None,
            )
            done[item.component] = _pinned(receipt, item.component)
        return done

    def build_spec(
        self, request: Any, checkout: Callable[[str, str, Path], Any]
    ) -> dict[str, BuiltImage]:
        """Build a pipeline's host spec from checkouts of its sources; push the changed images.

        ``request`` is a :class:`piceli.infra.pipelines.SpecBuildRequest`.
        """
        from contextlib import ExitStack

        from piceli.infra.pipelines import run_spec_build

        self.work_dir.mkdir(parents=True, exist_ok=True)

        def deliver(name: str, archive: Path, image_id: str, repository: str) -> Any:
            return self._backend().registry_deliver(
                self.route, image_id, repository, archive=archive
            )

        with (
            ExitStack() as stack,
            tempfile.TemporaryDirectory(prefix="out-", dir=self.work_dir) as out,
        ):
            roots = {
                name: Path(stack.enter_context(checkout(name, commit, self.work_dir)))
                for name, commit in sorted(request.commits.items())
            }
            self.say(f"[build] {request.spec}: " + ", ".join(sorted(request.images)))
            receipt = run_spec_build(
                request,
                roots,
                platforms=(self.platform,),
                cache=self.cache_dir,
                out=Path(out),
                deliver=deliver,
                say=self.say,
            )
        return {
            name: BuiltImage(str(entry["pull_ref"]), str(entry["manifest_digest"]))
            for name, entry in receipt["images"].items()
        }


# ------------------------------------------------------------------ in a Job


#: Fetches each source at its commit with the one Git Secret; the token
#: reaches Git only through ``GIT_ASKPASS`` (never a URL, argument or log).
_SCRIPT = """set -eu
export HOME=/work/home GIT_TERMINAL_PROMPT=0
mkdir -p "$HOME" /work/src /work/out
cat > /work/askpass <<'ASK'
#!/bin/sh
case "$1" in Username*) printf %s "$GIT_USERNAME" ;; *) printf %s "$GIT_PASSWORD" ;; esac
ASK
chmod 700 /work/askpass
export GIT_ASKPASS=/work/askpass
printf '%s\\n' "$PICELI_BUILD_SOURCES" | while read -r name url commit; do
  [ -n "$name" ] || continue
  mkdir -p "/work/src/$name"
  git -C "/work/src/$name" init -q .
  git -C "/work/src/$name" remote add origin "$url"
  git -C "/work/src/$name" fetch -q --depth 1 origin "$commit"
  git -C "/work/src/$name" checkout -q --detach FETCH_HEAD
done
unset GIT_USERNAME GIT_PASSWORD
exec piceli build job-run --sources /work/src --cache /cache --out /work/out \\
  --registry-url "$PICELI_BUILD_REGISTRY" --node-registry "$PICELI_BUILD_NODE_REGISTRY" \\
  --timeout "$PICELI_BUILD_TIMEOUT" "$@"
"""


@dataclass(frozen=True)
class JobSettings:
    """Where the component build Job runs (the controller's build settings)."""

    image: str
    namespace: str
    registry_url: str
    node_registry: str
    git_secret: str = "piceli-build-git"
    selector: Mapping[str, str] = field(
        default_factory=lambda: {"piceli.io/builder": "true"}
    )
    storage: str = "20Gi"
    platforms: tuple[str, ...] = ("linux/amd64",)
    timeout_seconds: int = 3600
    cache_claim: str = "piceli-component-cache"


def component_job(
    settings: JobSettings,
    items: Sequence[BuildItem],
    urls: Mapping[str, str],
) -> dict[str, Any]:
    """The Job that fetches every needed source and builds ``items``.

    ``urls`` maps each source name to its URL; only the sources of
    ``items`` are fetched, each once, at its commit.
    """
    sources: dict[str, str] = {}
    for item in items:
        if sources.setdefault(item.source, item.commit) != item.commit:
            raise CompositionError(
                "composition-invalid",
                f"source {item.source!r} is needed at two commits in one build",
            )
    lines = "\n".join(
        f"{name} {urls[name]} {sha}" for name, sha in sorted(sources.items())
    )
    arguments: list[str] = []
    for item in items:
        arguments += ["--component", json.dumps(_job_item(item), sort_keys=True)]
    for platform in settings.platforms:
        arguments += ["--platform", platform]
    key = hashlib.sha256(
        json.dumps([lines, arguments], sort_keys=True).encode()
    ).hexdigest()[:10]
    secret = settings.git_secret
    labels = {
        "app.kubernetes.io/managed-by": "piceli",
        "piceli.io/build": "true",
        "piceli.io/component-build": key,
    }
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": f"piceli-component-build-{key}",
            "namespace": settings.namespace,
            "labels": labels,
        },
        "spec": {
            "backoffLimit": 0,
            "activeDeadlineSeconds": settings.timeout_seconds,
            "template": {
                "metadata": {"labels": labels},
                "spec": {
                    "restartPolicy": "Never",
                    "nodeSelector": dict(settings.selector),
                    "automountServiceAccountToken": False,
                    "securityContext": {
                        "runAsNonRoot": True,
                        "runAsUser": 10001,
                        "runAsGroup": 10001,
                        "fsGroup": 10001,
                        "seccompProfile": {"type": "RuntimeDefault"},
                    },
                    "containers": [
                        {
                            "name": "build",
                            "image": settings.image,
                            "command": ["sh", "-c", _SCRIPT, "piceli-build", *arguments],
                            "env": [
                                {"name": "PICELI_BUILD_SOURCES", "value": lines},
                                {"name": "PICELI_BUILD_REGISTRY", "value": settings.registry_url},
                                {"name": "PICELI_BUILD_NODE_REGISTRY", "value": settings.node_registry},
                                {"name": "PICELI_BUILD_TIMEOUT", "value": str(settings.timeout_seconds)},
                                {
                                    "name": "GIT_USERNAME",
                                    "valueFrom": {"secretKeyRef": {"name": secret, "key": "username"}},
                                },
                                {
                                    "name": "GIT_PASSWORD",
                                    "valueFrom": {"secretKeyRef": {"name": secret, "key": "password"}},
                                },
                            ],
                            "volumeMounts": [
                                {"name": "cache", "mountPath": "/cache"},
                                {"name": "work", "mountPath": "/work"},
                            ],
                            "securityContext": {
                                "allowPrivilegeEscalation": False,
                                "capabilities": {"drop": ["ALL"]},
                            },
                        }
                    ],
                    "volumes": [
                        {
                            "name": "cache",
                            "persistentVolumeClaim": {"claimName": settings.cache_claim},
                        },
                        {"name": "work", "emptyDir": {}},
                    ],
                },
            },
        },
    }  # fmt: skip


def _job_item(item: BuildItem) -> dict[str, Any]:
    return {
        "component": item.component,
        "source": item.source,
        "digest": item.digest,
        "repository": item.repository,
    }


def job_run_components(
    *,
    sources: Path,
    items: Sequence[Mapping[str, Any]],
    platforms: Sequence[str],
    cache: Path,
    out: Path,
    registry_url: str,
    node_registry: str | None,
    say: Callable[[str], None] = lambda _: None,
    deliver: Any = None,
) -> dict[str, Any]:
    """What the Job runs: build each component from ``sources/<source>``; a receipt.

    Each item is ``{"component", "source", "digest", "repository"}``; the
    contract is read again from the fetched ``piceli.toml`` (the digest is
    checked against it, so the Job never builds something else than what was
    planned). Returns ``{"components": {name: {"pull_ref",
    "manifest_digest", "platform"}}}`` for the first platform.
    """
    from piceli.artifacts.delivery import ArchiveSource, DeliveryGrant
    from piceli.artifacts.host_build import HostBuildGrant, HostBuildSpec
    from piceli.artifacts.node_facts import NodeFacts
    from piceli.artifacts.registry import RegistryTarget
    from piceli.artifacts.registry_delivery import RegistryDelivery
    from piceli.infra.contract import CONTRACT_FILE, parse_contracts

    if deliver is None:
        deliver = RegistryDelivery().deliver
    results: dict[str, Any] = {}
    prefix = registry_url.rstrip("/")
    for item in items:
        name, source = str(item["component"]), str(item["source"])
        if not re.fullmatch(r"[a-z0-9][-a-z0-9]{0,62}", source):
            raise CompositionError("composition-invalid", "invalid source name")
        root = sources / source
        contract = parse_contracts((root / CONTRACT_FILE).read_bytes()).get(name)
        if contract is None:
            raise CompositionError(
                "component-contract-missing", f"no [component.{name}] in {source}"
            )
        for platform in platforms:
            facts = NodeFacts.for_platform(platform)
            document = host_build_document(
                name, contract, root, str(item["repository"])
            )
            spec = HostBuildSpec.from_dict(document, root).for_node(facts)
            spec = spec.with_cache_dir(cache)
            plan = spec.plan()
            grant = HostBuildGrant(plan.plan_hash, time.time() + 3600)
            directory = out / platform.replace("/", "-") / name
            say(f"[build] {name} for {platform}")
            receipt = spec.run(grant, directory, progress=say).to_dict()
            entry = receipt["outputs"]["images"][name]
            url = f"{prefix}/{item['repository']}"
            delivered = deliver(
                ArchiveSource((directory / entry["archive"]).absolute()),
                RegistryTarget.parse(url),
                DeliveryGrant(entry["image_id"], url, time.time() + 3600),
                node_registry=node_registry,
            )
            image = _pinned(delivered, name)
            results.setdefault(
                name,
                {**image.to_dict(), "platform": platform, "digest": item["digest"]},
            )
    return {"components": results}


def spec_job(
    settings: JobSettings, request: Any, urls: Mapping[str, str]
) -> dict[str, Any]:
    """The Job that fetches every source a pipeline's host spec reads and builds it.

    ``request`` is a :class:`piceli.infra.pipelines.SpecBuildRequest`: each
    source is fetched once at its commit with the one Git Secret, the spec is
    read from the composition repository's checkout, and only the images
    whose change key changed are pushed.
    """
    urls = {**dict(urls), **dict(request.urls)}
    missing = sorted(set(request.commits) - set(urls))
    if missing:
        raise CompositionError(
            "composition-invalid", f"no URL of source {missing[0]!r}"
        )
    lines = "\n".join(
        f"{name} {urls[name]} {sha}" for name, sha in sorted(request.commits.items())
    )
    arguments = ["--spec", f"{request.repo}/{request.spec}"]
    for name, wanted in sorted(request.images.items()):
        arguments += [
            "--image",
            json.dumps({"image": name, **dict(wanted)}, sort_keys=True),
        ]
    for platform in settings.platforms:
        arguments += ["--platform", platform]
    if request.facts:
        arguments += ["--facts", json.dumps(dict(request.facts), sort_keys=True)]
    job = component_job(settings, [], {})
    key = hashlib.sha256(
        json.dumps([lines, arguments], sort_keys=True).encode()
    ).hexdigest()[:10]
    job["metadata"]["name"] = f"piceli-image-build-{key}"
    labels = {**job["metadata"]["labels"], "piceli.io/component-build": key}
    job["metadata"]["labels"] = labels
    job["spec"]["template"]["metadata"]["labels"] = labels
    container = job["spec"]["template"]["spec"]["containers"][0]
    container["command"] = ["sh", "-c", _SCRIPT, "piceli-build", *arguments]
    for entry in container["env"]:
        if entry["name"] == "PICELI_BUILD_SOURCES":
            entry["value"] = lines
        elif entry["name"] == "PICELI_BUILD_REGISTRY":
            # Images go to <registry host>/<repository>: the request names them.
            entry["value"] = f"oci://{settings.node_registry}"
    return job


def job_run_spec(
    *,
    sources: Path,
    spec: str,
    images: Sequence[Mapping[str, Any]],
    platforms: Sequence[str],
    cache: Path,
    out: Path,
    registry_url: str,
    node_registry: str | None,
    facts: Mapping[str, Any] | None = None,
    say: Callable[[str], None] = lambda _: None,
    deliver: Any = None,
) -> dict[str, Any]:
    """What a pipeline image build Job runs: the spec at ``sources/<repo>/<path>``.

    ``spec`` is ``<repo source>/<path>``; each fetched source is
    ``sources/<name>``. Pushes each of ``images`` (``{"image",
    "repository", "key"}``) and returns ``{"images": {name: {"pull_ref",
    "manifest_digest", "key", "platform"}}}``.
    """
    from piceli.artifacts.delivery import ArchiveSource, DeliveryGrant
    from piceli.artifacts.registry import RegistryTarget
    from piceli.artifacts.registry_delivery import RegistryDelivery
    from piceli.infra.pipelines import SpecBuildRequest, run_spec_build

    if deliver is None:
        deliver = RegistryDelivery().deliver
    repo, _, path = spec.partition("/")
    names = sorted(item.name for item in sources.iterdir() if item.is_dir())
    for name in [repo, *names]:
        if not re.fullmatch(r"[a-z0-9][-a-z0-9]{0,62}", name):
            raise CompositionError("composition-invalid", "invalid source name")
    request = SpecBuildRequest(
        spec=path,
        repo=repo,
        commits=dict.fromkeys(names, ""),
        images={
            str(item["image"]): {
                "repository": str(item["repository"]),
                "key": str(item["key"]),
            }
            for item in images
        },
        facts=facts,
    )
    prefix = registry_url.rstrip("/")

    def push(name: str, archive: Path, image_id: str, repository: str) -> Any:
        url = f"{prefix}/{repository}"
        return deliver(
            ArchiveSource(archive),
            RegistryTarget.parse(url),
            DeliveryGrant(image_id, url, time.time() + 3600),
            node_registry=node_registry,
        )

    return run_spec_build(
        request,
        {name: sources / name for name in names},
        platforms=platforms,
        cache=cache,
        out=out,
        deliver=push,
        say=say,
    )


class JobBuilder:
    """Build in the cluster: one Job per batch of changed components.

    :param settings: Where the Job runs and pushes.
    :param urls: Each source's URL.
    :param cluster: A :class:`piceli.artifacts.cluster_build.BuildCluster`
        (the Job runner that reads the receipt line).
    :param mirror_route: How the controller reaches the registry to mirror
        third-party images (in the cluster: by the Service name).
    """

    def __init__(
        self,
        settings: JobSettings,
        urls: Mapping[str, str],
        cluster: Any,
        *,
        mirror_route: Any,
        backend: Any = None,
        say: Callable[[str], None] = lambda _: None,
    ) -> None:
        self.settings = settings
        self.urls = dict(urls)
        self.cluster = cluster
        self.mirror_route = mirror_route
        self.backend = backend
        self.say = say

    def build(
        self, items: Sequence[BuildItem], checkout: Callable[[str, str, Path], Any]
    ) -> dict[str, BuiltImage]:
        from piceli.artifacts.cluster_build import decode_receipt

        for item in items:
            if (
                item.contract.build is not None
                and item.contract.build.kind == "dockerfile"
            ):
                raise _unsupported(item.component, "dockerfile")
        if not items:
            return {}
        job = component_job(self.settings, items, self.urls)
        claim = {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "metadata": {
                "name": self.settings.cache_claim,
                "namespace": self.settings.namespace,
                "labels": {"app.kubernetes.io/managed-by": "piceli"},
            },
            "spec": {
                "accessModes": ["ReadWriteOnce"],
                "resources": {"requests": {"storage": self.settings.storage}},
            },
        }
        self.cluster.ensure_claim(claim)
        self.say(
            f"[build] Job {job['metadata']['name']}: "
            + ", ".join(item.component for item in items)
        )
        outcome = self.cluster.run_job(job)
        if outcome.state != "passed" or self.cluster.receipt_text is None:
            raise CompositionError(
                "component-build-failed",
                f"the component build Job ended {outcome.state}",
            )
        try:
            receipt = decode_receipt(self.cluster.receipt_text)
        except (ValueError, OSError):
            raise CompositionError(
                "component-build-failed", "the build Job printed no readable receipt"
            ) from None
        found = receipt.get("components") or {}
        built: dict[str, BuiltImage] = {}
        for item in items:
            entry = found.get(item.component)
            if not isinstance(entry, Mapping) or entry.get("digest") != item.digest:
                raise CompositionError(
                    "component-build-failed",
                    f"the build Job returned no image of {item.component!r}",
                )
            built[item.component] = BuiltImage(
                str(entry["pull_ref"]), str(entry["manifest_digest"])
            )
        return built

    def build_spec(
        self, request: Any, checkout: Callable[[str, str, Path], Any]
    ) -> dict[str, BuiltImage]:
        """One Job that fetches every source of a pipeline's host spec and builds it."""
        from piceli.artifacts.cluster_build import decode_receipt

        if not request.images:
            return {}
        job = spec_job(self.settings, request, self.urls)
        self.cluster.ensure_claim(self._claim())
        self.say(
            f"[build] Job {job['metadata']['name']}: "
            + ", ".join(sorted(request.images))
        )
        outcome = self.cluster.run_job(job)
        if outcome.state != "passed" or self.cluster.receipt_text is None:
            raise CompositionError(
                "component-build-failed", f"the image build Job ended {outcome.state}"
            )
        try:
            receipt = decode_receipt(self.cluster.receipt_text)
        except (ValueError, OSError):
            raise CompositionError(
                "component-build-failed", "the build Job printed no readable receipt"
            ) from None
        found = receipt.get("images") or {}
        built: dict[str, BuiltImage] = {}
        for name, wanted in request.images.items():
            entry = found.get(name)
            if not isinstance(entry, Mapping) or entry.get("key") != wanted["key"]:
                raise CompositionError(
                    "component-build-failed",
                    f"the build Job returned no image {name!r}",
                )
            built[name] = BuiltImage(
                str(entry["pull_ref"]), str(entry["manifest_digest"])
            )
        return built

    def _claim(self) -> dict[str, Any]:
        return {
            "apiVersion": "v1",
            "kind": "PersistentVolumeClaim",
            "metadata": {
                "name": self.settings.cache_claim,
                "namespace": self.settings.namespace,
                "labels": {"app.kubernetes.io/managed-by": "piceli"},
            },
            "spec": {
                "accessModes": ["ReadWriteOnce"],
                "resources": {"requests": {"storage": self.settings.storage}},
            },
        }

    def mirror(self, items: Sequence[MirrorItem]) -> dict[str, BuiltImage]:
        if self.backend is None:
            from piceli.pipeline.backend import Backend

            self.backend = Backend()
        done: dict[str, BuiltImage] = {}
        for item in items:
            receipt = self.backend.mirror_deliver(
                self.mirror_route,
                item.reference,
                item.repository,
                platform=None,  # the whole index: pulled by its digest
                credentials=None,
            )
            done[item.component] = _pinned(receipt, item.component)
        return done
