"""The registry of fixed error codes that Piceli prints when it refuses or fails.

Every refusal a command prints has the shape
``{"state": "rejected", "reason": "<code>"}``; failures recorded in receipts or
execution results use the same codes. This module is the single place where each
code is explained: its cause, the fix, and whether retrying the same command
unchanged can succeed. ``piceli explain <code>`` prints an entry and
``docs/reference/errors.md`` is generated from it.

Importing this module is side-effect free: it only defines constant data.

Example::

    from piceli.errors import lookup

    entry = lookup("tool-pin-mismatch")
    assert entry is not None and not entry.retry_safe
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import asdict, dataclass
from types import MappingProxyType
from typing import Any

#: Areas group codes by the component that emits them.
AREAS: Mapping[str, str] = MappingProxyType(
    {
        "cli": "Command-line contract (any command)",
        "artifacts-input": "Artifact delivery inputs (`piceli artifacts deliver`)",
        "artifacts-delivery": "Artifact delivery outcomes (delivery receipts)",
        "artifacts-registry": "OCI registry transfers (`piceli artifacts deliver --to oci://…`)",
        "build-spec": "Containerized builds (`piceli artifacts build-spec`)",
        "kubernetes": "Kubernetes API access (release plan/apply, discovery)",
        "execution": "Plan execution preconditions (release apply/resume/rollback)",
        "inputs": "Source identities (`piceli inputs record|verify`)",
        "secrets": "Release secret generators and `piceli release secret show`",
        "render": "Typed apps and `piceli render`",
        "images": "Image references in releases (`[images]`, `images_from`, receipts)",
        "release": "Release commands (`piceli release plan|apply|rollback|resume|stop|status`)",
        "observe": "Operations commands (`piceli observe …`, `piceli operator …`)",
        "checks": "Post-deploy checks and automatic rollback (`[[checks]]`, `piceli.checks`)",
        "access": "Access and status from the model (`piceli access`, `piceli status`)",
        "target": "Release target credentials (`[target]`, kubeconfig exec plugins)",
        "import": "Migration kit (`piceli import live`, `piceli import yaml`)",
        # --- P5 pipeline ---
        "pipeline": "Deploying a pipeline from source (`piceli deploy`)",
    }
)


@dataclass(frozen=True)
class ErrorCode:
    """One fixed error code.

    :param code: The stable, lowercase, dash-separated code printed as ``reason``.
    :param title: A short noun phrase naming the problem.
    :param cause: What made Piceli refuse or fail.
    :param fix: The next step, as concrete as possible (a command or a flag).
    :param retry_safe: ``True`` when re-running the same command unchanged is
        safe and can succeed (a transient condition). ``False`` means something
        must change first (an input, a flag, the cluster, a new plan).
    :param area: The component that emits it; a key of :data:`AREAS`.

    Codes never contain paths, secret values or server messages, so an entry
    is always safe to print and to paste into an issue.
    """

    code: str
    title: str
    cause: str
    fix: str
    retry_safe: bool
    area: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def _entries(*items: ErrorCode) -> Mapping[str, ErrorCode]:
    table: dict[str, ErrorCode] = {}
    for item in items:
        if item.code in table:
            raise ValueError(f"duplicate error code {item.code!r}")
        table[item.code] = item
    return MappingProxyType(dict(sorted(table.items())))


_E = ErrorCode
_REPLAN = "Run `piceli release plan` again and approve the new plan hash."
_RESUME = (
    "Inspect the object with a read-only tool; when it matches the release, run "
    "`piceli release resume --spec release.toml`, otherwise plan again."
)

ERRORS: Mapping[str, ErrorCode] = _entries(
    # ------------------------------------------------------------------ cli
    _E(
        "unknown-error-code",
        "Unknown error code",
        "`piceli explain` was given a code that is not in the registry.",
        "Check the spelling; `piceli help-json` and docs/reference/errors.md list every code.",
        False,
        "cli",
    ),
    _E(
        "invalid-or-unavailable-artifact-input",
        "Invalid or unavailable artifact input",
        "An `artifacts` command could not read or validate one of its inputs "
        "(a plan, layout, spec or source file). The detail is withheld because "
        "it could contain private paths.",
        "Check that every path passed to the command exists, is readable and "
        "holds the documented format; run the matching `preview` command first.",
        False,
        "cli",
    ),
    # ------------------------------------------------------ artifacts-input
    _E(
        "invalid-approved-digest",
        "Invalid approved digest",
        "`--approve-digest` is not `sha256:` followed by 64 lowercase hex characters.",
        "Pass the image config digest, e.g. from `docker image inspect --format '{{.Id}}'`.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-timeout",
        "Invalid timeout",
        "`--timeout` is not a positive number within the allowed bounds.",
        "Pass a positive number of seconds.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-source",
        "Invalid delivery source",
        "`--image` is not a valid local image reference, or `--archive` is not a usable file.",
        "Pass exactly one of `--image NAME[:TAG]` or `--archive PATH` (an OCI or docker-save tar).",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-target",
        "Invalid delivery target",
        "`--to` is not a supported target (`oci://host[:port]/repo[:tag]`, "
        "`ssh://user@host`, `docker://container`), or the grant for it could not be built.",
        "Fix `--to`; see docs/node_delivery.md for the accepted forms.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-reference",
        "Invalid image reference",
        "`--ref` is not a tagged image name (digests and option-like values are refused).",
        "Pass a tagged name such as `my-app:1.0`.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-delivery-input",
        "Invalid delivery input",
        "The delivery could not be set up or failed on an input it could not "
        "validate (the detail is withheld because it could contain private paths).",
        "Re-check every delivery option; run with the same inputs against a "
        "local target first to isolate the problem.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-credentials-file",
        "Invalid registry credentials file",
        "`--credentials` is not a small regular JSON file holding "
        '`{"username": …, "password": …}` or `{"token": …}`.',
        "Write the credentials file in one of the documented shapes.",
        False,
        "artifacts-input",
    ),
    _E(
        "credentials-file-not-private",
        "Credentials file is readable by others",
        "The registry credentials file grants permissions to group or others.",
        "Run `chmod 600` on the credentials file.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-forward",
        "Invalid port-forward settings",
        "A `--via-forward` setting (namespace, target, remote port or context) is invalid.",
        "Pass `--via-forward deployment/NAME` with a valid `--namespace`, "
        "`--forward-remote-port` and optional `--context`.",
        False,
        "artifacts-input",
    ),
    _E(
        "forward-options-incomplete",
        "Port-forward options incomplete",
        "`--via-forward` needs an explicit `--kubeconfig` (absolute), `--context` and `--namespace`.",
        "Add `--kubeconfig PATH --context NAME --namespace NAME`; Piceli never uses an ambient kube context or the file's current-context.",
        False,
        "artifacts-input",
    ),
    _E(
        "forward-options-without-forward",
        "Port-forward options without --via-forward",
        "`--namespace`, `--kubeconfig`, `--context` or `--kubectl*` were given without `--via-forward`.",
        "Add `--via-forward deployment/NAME` or remove those options.",
        False,
        "artifacts-input",
    ),
    _E(
        "forward-target-not-loopback",
        "Forwarded target is not loopback",
        "With `--via-forward`, the `oci://` target must be a loopback address with an explicit port.",
        "Use `--to oci://127.0.0.1:PORT/repository`.",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-node-registry",
        "Invalid node registry address",
        "`--node-registry` is not `host[:port]`.",
        "Pass the address the node pulls from, e.g. `127.0.0.1:5000`.",
        False,
        "artifacts-input",
    ),
    _E(
        "node-registry-required",
        "Node registry address required",
        "A delivery through `--via-forward` cannot derive the address nodes pull from.",
        "Add `--node-registry host[:port]` (the address as seen from the node).",
        False,
        "artifacts-input",
    ),
    _E(
        "invalid-ca-file",
        "Invalid CA file",
        "`--ca-file` is not a readable PEM file.",
        "Pass the registry's CA certificate bundle as a PEM file.",
        False,
        "artifacts-input",
    ),
    _E(
        "plain-http-not-loopback",
        "Plain HTTP to a non-loopback registry",
        "The registry target asks for plain HTTP but its host is not a loopback address.",
        "Use TLS for remote registries, or reach the registry through `--via-forward`.",
        False,
        "artifacts-input",
    ),
    _E(
        "node-options-on-registry-target",
        "Node options on a registry target",
        "`--ref`, `--ssh*` or `--ssh-agent-socket` were given with an `oci://` target.",
        "Remove the node-import options, or deliver to an `ssh://` / `docker://` target.",
        False,
        "artifacts-input",
    ),
    _E(
        "registry-options-on-node-target",
        "Registry options on a node target",
        "Registry or forward options were given with an `ssh://` or `docker://` target.",
        "Remove the registry options, or deliver to an `oci://` target.",
        False,
        "artifacts-input",
    ),
    _E(
        "docker-tool-required",
        "docker CLI required",
        "The delivery needs the docker CLI and none was found or it is not executable.",
        "Install docker or pass `--docker PATH` (and `--docker-sha256` to pin it).",
        False,
        "artifacts-input",
    ),
    _E(
        "ssh-tool-required",
        "ssh CLI required",
        "An `ssh://` delivery needs the ssh client and none was found or it is not executable.",
        "Install OpenSSH or pass `--ssh PATH` (and `--ssh-sha256` to pin it).",
        False,
        "artifacts-input",
    ),
    _E(
        "kubectl-tool-required",
        "kubectl CLI required",
        "`--via-forward` needs kubectl and none was found or it is not executable.",
        "Install kubectl or pass `--kubectl PATH` (and `--kubectl-sha256` to pin it).",
        False,
        "artifacts-input",
    ),
    _E(
        "tool-pin-mismatch",
        "Tool differs from its pin",
        "A pinned tool binary (docker, ssh, kubectl) does not match the given "
        "SHA-256, or changed during the operation.",
        "Check which binary is on PATH; update the `--*-sha256` pin only if the change is expected.",
        False,
        "artifacts-input",
    ),
    _E(
        "docker-socket-required",
        "Local Docker socket required",
        "The Docker endpoint is not an absolute `unix://` socket (TCP and SSH endpoints are refused).",
        "Pass `--docker-socket /absolute/path/docker.sock` or point `DOCKER_HOST` at a unix socket.",
        False,
        "artifacts-input",
    ),
    _E(
        "grant-mismatch",
        "Delivery grant mismatch",
        "The delivery grant does not name this exact target, or it expired before the delivery started.",
        "Run the delivery again (a fresh grant is created per run); raise `--timeout` if it expired.",
        True,
        "artifacts-input",
    ),
    _E(
        "invalid-ssh-agent-socket",
        "Invalid ssh-agent socket",
        "`--ssh-agent-socket` is not an absolute path.",
        "Pass the absolute path of the agent socket (`$SSH_AUTH_SOCK`).",
        False,
        "artifacts-input",
    ),
    _E(
        "reference-required",
        "Image reference required",
        "The archive has no single image name, so the node cannot name the import.",
        "Add `--ref my-app:TAG`.",
        False,
        "artifacts-input",
    ),
    # --------------------------------------------------- artifacts-delivery
    _E(
        "digest-mismatch",
        "Image does not match the approved digest",
        "The streamed or stored image's config digest differs from `--approve-digest`.",
        "Re-inspect the image and approve its actual config digest, or rebuild the image you meant.",
        False,
        "artifacts-delivery",
    ),
    _E(
        "invalid-archive",
        "Invalid image archive",
        "The `--archive` file is not a valid OCI layout or docker-save tar within the size bounds.",
        "Recreate it with `docker save` or an OCI build and check it with `piceli artifacts inspect`.",
        False,
        "artifacts-delivery",
    ),
    _E(
        "invalid-image-stream",
        "Invalid image stream",
        "The image streamed by `docker save` could not be parsed or exceeded its bounds.",
        "Check that the image exists locally and that docker works; then retry.",
        False,
        "artifacts-delivery",
    ),
    _E(
        "source-unavailable",
        "Image source unavailable",
        "The local image or archive could not be read (for example docker failed to save it).",
        "Check that the image exists (`docker image ls`) and the daemon is running, then retry.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "source-changed",
        "Image source changed during delivery",
        "The image was read twice (plan, then upload) and the second read differed.",
        "Make sure nothing retags or rebuilds the image during delivery, then retry.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "node-query-failed",
        "Node query failed",
        "Listing or inspecting images on the node (`ctr`) failed.",
        "Check SSH/docker access to the node and that containerd runs; then retry.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "cancelled",
        "Cancelled",
        "The operation was cancelled (interrupt, stop request or cancelled execution).",
        "Re-run the command when ready; recoverable executions can be resumed with `piceli release resume`.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "timed-out",
        "Timed out",
        "The operation did not finish within `--timeout`.",
        "Retry with a larger `--timeout`; only missing layers are resent.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "verification-failed",
        "Post-delivery verification failed",
        "After the transfer, the node or registry did not report the approved image under the expected name.",
        "Inspect the target (`crictl images` or the registry) and retry the delivery.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "forward-port-in-use",
        "Local forward port in use",
        "The local port for `kubectl port-forward` is already taken.",
        "Free the port or pick another one in the `oci://127.0.0.1:PORT/…` target.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "forward-unavailable",
        "Port-forward unavailable",
        "`kubectl port-forward` to the registry did not become ready.",
        "Check that the registry Deployment is ready and that you may `pods/portforward`; then retry.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "import-failed",
        "Node import failed",
        "`ctr images import` on the node exited with an error.",
        "Check free disk space and containerd on the node; then retry.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "import-timed-out",
        "Node import timed out",
        "`ctr images import` did not finish within `--timeout`.",
        "Retry with a larger `--timeout`, or prefer registry delivery for large images.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "import-cancelled",
        "Node import cancelled",
        "The node import was interrupted.",
        "Re-run the delivery.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "import-output-limit",
        "Node import output too large",
        "`ctr images import` wrote more output than allowed.",
        "Check the node's containerd; report the problem if it persists.",
        False,
        "artifacts-delivery",
    ),
    # --------------------------------------------------- artifacts-registry
    _E(
        "registry-unreachable",
        "Registry unreachable",
        "The registry could not be contacted (DNS, TCP or TLS failure).",
        "Check the address, network and TLS settings (`--ca-file`), then retry.",
        True,
        "artifacts-registry",
    ),
    _E(
        "registry-unauthorized",
        "Registry authentication failed",
        "The registry answered 401: credentials are missing or wrong.",
        "Pass `--credentials FILE` with valid credentials.",
        False,
        "artifacts-registry",
    ),
    _E(
        "registry-forbidden",
        "Registry access forbidden",
        "The registry answered 403: the credentials may not push to this repository.",
        "Use credentials with push rights on the repository.",
        False,
        "artifacts-registry",
    ),
    _E(
        "registry-not-oci-v2",
        "Not an OCI distribution registry",
        "The endpoint does not implement the OCI distribution `/v2/` API.",
        "Point `--to` at a registry (host, port and scheme).",
        False,
        "artifacts-registry",
    ),
    _E(
        "registry-error",
        "Registry error",
        "The registry answered with an unexpected HTTP status.",
        "Check the registry's health and logs, then retry.",
        True,
        "artifacts-registry",
    ),
    _E(
        "registry-response-too-large",
        "Registry response too large",
        "A registry response exceeded Piceli's size bound.",
        "Check that `--to` points at a real registry.",
        False,
        "artifacts-registry",
    ),
    _E(
        "plain-http-refused",
        "Plain HTTP refused",
        "The registry tried to move the transfer to plain HTTP on a non-loopback host.",
        "Use TLS on the registry.",
        False,
        "artifacts-registry",
    ),
    _E(
        "cross-origin-location-refused",
        "Cross-origin redirect refused",
        "The registry redirected an upload to another origin.",
        "Configure the registry to accept uploads on its own address.",
        False,
        "artifacts-registry",
    ),
    _E(
        "invalid-token-realm",
        "Invalid token realm",
        "The registry's bearer-token challenge names an unusable realm.",
        "Check the registry's authentication configuration.",
        False,
        "artifacts-registry",
    ),
    _E(
        "upload-rejected",
        "Upload rejected",
        "The registry refused a blob upload.",
        "Check the registry's storage and quota, then retry.",
        True,
        "artifacts-registry",
    ),
    _E(
        "blob-digest-mismatch",
        "Uploaded blob digest mismatch",
        "The registry stored a blob whose digest differs from what was sent.",
        "Retry; if it persists, the registry or a proxy is altering content.",
        True,
        "artifacts-registry",
    ),
    _E(
        "blob-source-truncated",
        "Blob source truncated",
        "A layer ended before its declared size while it was uploaded.",
        "Make sure nothing changes the image during delivery, then retry.",
        True,
        "artifacts-registry",
    ),
    _E(
        "manifest-not-found",
        "Manifest not found",
        "The registry has no manifest for the expected digest after the push.",
        "Retry the delivery; check that the registry keeps pushed manifests.",
        True,
        "artifacts-registry",
    ),
    _E(
        "manifest-rejected",
        "Manifest rejected",
        "The registry refused the image manifest.",
        "Check that the registry accepts OCI or Docker v2 manifests of this type.",
        False,
        "artifacts-registry",
    ),
    _E(
        "registry-digest-mismatch",
        "Registry manifest digest mismatch",
        "The digest the registry reports for the pushed manifest differs from the one computed locally.",
        "Retry; if it persists, the registry is rewriting manifests and cannot be used.",
        False,
        "artifacts-registry",
    ),
    # ------------------------------------------------------------ build-spec
    _E(
        "spec-unreadable",
        "Build spec unreadable",
        "`--spec` could not be read.",
        "Check the path and its permissions.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-spec",
        "Invalid build spec",
        "The build spec (or a build context in it) is invalid: unknown keys, bad "
        "patterns, budgets or paths.",
        "Run `piceli artifacts build-spec preview --spec build.toml` and fix the spec; see docs/containerized_builds.md.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-inputs",
        "Invalid inputs spec or lock",
        "The `inputs.toml` or inputs lock referenced by the build could not be read or verified.",
        "Run `piceli inputs verify --spec inputs.toml --lock inputs.lock` to see the problem.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-or-unavailable-build-input",
        "Invalid or unavailable build input",
        "A build input could not be read or validated (the detail is withheld because it could contain private paths).",
        "Run `build-spec preview` with the same arguments and check every path it names.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-grant",
        "Invalid build grant",
        "The approval arguments (`--approve-builder`, `--approve-plan`, `--max-seconds`) are malformed.",
        "Copy the builder digest and plan hash from `build-spec preview`; use a positive `--max-seconds`.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-tool",
        "Invalid docker pin",
        "Only one of `--docker` and `--docker-sha256` was given.",
        "Pass both, or neither to use docker from PATH.",
        False,
        "build-spec",
    ),
    _E(
        "invalid-receipt",
        "Invalid build receipt",
        "The file is not a complete `piceli.build-receipt.v1` receipt.",
        "Re-run the build to produce a new receipt.",
        False,
        "build-spec",
    ),
    _E(
        "builder-not-approved",
        "Builder not approved",
        "`--approve-builder` does not match the builder image digest in the spec.",
        "Review the builder in `build-spec preview` and approve its exact digest.",
        False,
        "build-spec",
    ),
    _E(
        "plan-not-approved",
        "Build plan not approved",
        "`--approve-plan` does not match the current build plan hash (the spec or inputs changed).",
        "Run `build-spec preview` again and approve the new plan hash.",
        False,
        "build-spec",
    ),
    _E(
        "network-not-granted",
        "Network not granted",
        "The spec declares network access but `--allow-network` was not given.",
        "Add `--allow-network` if the build may use the network.",
        False,
        "build-spec",
    ),
    _E(
        "grant-expired",
        "Build grant expired",
        "The build ran past `--max-seconds`.",
        "Retry with a larger `--max-seconds`.",
        True,
        "build-spec",
    ),
    _E(
        "docker-unavailable",
        "Docker unavailable",
        "The docker CLI, daemon, buildx or context is not usable.",
        "Check `docker buildx version` and `docker context show`, then retry.",
        True,
        "build-spec",
    ),
    _E(
        "build-failed",
        "Build step failed",
        "A docker build step exited with an error (exit 1; the failing steps are listed, never their output).",
        "Re-run with `--log FILE` and read the step output there.",
        False,
        "build-spec",
    ),
    _E(
        "build-timed-out",
        "Build step timed out",
        "A docker build step exceeded its time budget (exit 1).",
        "Retry with a larger `--max-seconds`.",
        True,
        "build-spec",
    ),
    _E(
        "source-drift",
        "Source changed",
        "A declared source differs from its lock, or changed during the build. "
        "Drift is currently checked over the whole repository, not only the build context.",
        "Commit or stash the changes and record a new lock with `piceli inputs record`.",
        False,
        "build-spec",
    ),
    _E(
        "source-identity",
        "Source identity unavailable",
        "A declared source could not be identified with git (not a work tree, git failed).",
        "Run `piceli inputs record --spec inputs.toml` to see which source fails.",
        False,
        "build-spec",
    ),
    _E(
        "context-missing",
        "Build context missing",
        "A build context root is not a readable real directory.",
        "Fix the context path in the spec.",
        False,
        "build-spec",
    ),
    _E(
        "context-empty",
        "Build context empty",
        "A context's include patterns matched no files.",
        "Fix the `include` patterns.",
        False,
        "build-spec",
    ),
    _E(
        "context-symlink",
        "Symbolic link in build context",
        "A context include pattern matches a symbolic link.",
        "Exclude the link or replace it with the real file.",
        False,
        "build-spec",
    ),
    _E(
        "context-budget-exceeded",
        "Build context over budget",
        "A context has more files or bytes than its budget.",
        "Narrow the `include` patterns or raise the context budget in the spec.",
        False,
        "build-spec",
    ),
    _E(
        "context-changed",
        "Build context changed",
        "A context file (or the Dockerfile) changed between scanning and staging.",
        "Stop editing the sources during the build, then retry.",
        True,
        "build-spec",
    ),
    _E(
        "dockerfile-unpinned",
        "Dockerfile not pinned",
        "A Dockerfile uses an unpinned base image, `COPY --from`, remote `ADD` "
        "or `RUN --mount` source, or does not build `FROM` the builder argument.",
        "Pin every image by digest (`image@sha256:…`) and build `FROM` the "
        "builder argument; see docs/containerized_builds.md.",
        False,
        "build-spec",
    ),
    _E(
        "output-invalid",
        "Build output invalid",
        "The build produced a missing, undeclared, oversized or symlinked output, or the output directory is unusable.",
        "Make the build produce exactly the declared outputs into a clean `--output-dir`.",
        False,
        "build-spec",
    ),
    _E(
        "image-invalid",
        "Built image invalid",
        "The built image could not be inspected or has an invalid ID.",
        "Check the build log (`--log`).",
        False,
        "build-spec",
    ),
    _E(
        "image-mismatch",
        "Built image mismatch",
        "The loaded image differs from the build result or has another platform.",
        "Check the declared platform and that nothing else loads images concurrently.",
        False,
        "build-spec",
    ),
    # ------------------------------------------------------------ kubernetes
    _E(
        "rbac-denied",
        "Kubernetes access denied",
        "The API server answered 401 or 403 for a request the plan or apply needs.",
        "Grant the identity in the spec's kubeconfig the needed verbs in the namespace, then plan again.",
        False,
        "kubernetes",
    ),
    _E(
        "not-found",
        "Kubernetes object not found",
        "The API server answered 404.",
        _REPLAN,
        False,
        "kubernetes",
    ),
    _E(
        "conflict",
        "Kubernetes write conflict",
        "The API server answered 409: the object changed since it was observed.",
        _REPLAN,
        False,
        "kubernetes",
    ),
    _E(
        "invalid-request",
        "Kubernetes rejected the object",
        "The API server answered 422: the manifest is invalid for this cluster.",
        "Fix the composition (field names, API versions); admission dry-run in `plan` shows the object.",
        False,
        "kubernetes",
    ),
    _E(
        "api-unavailable",
        "Kubernetes API unavailable",
        "The API server answered 429 or 5xx, or an API group could not be discovered.",
        "Wait for the API server to recover, then retry.",
        True,
        "kubernetes",
    ),
    _E(
        "transport-error",
        "Kubernetes transport error",
        "The connection to the API server failed.",
        "Check network access to the cluster, then retry (a write may be ambiguous: use `release resume`).",
        True,
        "kubernetes",
    ),
    _E(
        "deadline-exceeded",
        "Deadline exceeded",
        "A request or the whole execution ran past its time limit.",
        "Retry; for an interrupted apply use `piceli release resume`, or raise `[execution] max_seconds`.",
        True,
        "kubernetes",
    ),
    _E(
        "limit-exceeded",
        "Discovery limit exceeded",
        "Discovery found more objects or bytes than `[discovery]` allows.",
        "Raise the `[discovery]` limits in the spec, then plan again.",
        False,
        "kubernetes",
    ),
    _E(
        "invalid-page",
        "Invalid discovery page",
        "The API server returned an inconsistent list page.",
        "Plan again; if it persists, report the API server version.",
        True,
        "kubernetes",
    ),
    _E(
        "provider-error",
        "Provider error",
        "The Kubernetes provider failed in an unclassified way during discovery.",
        "Plan again; if it persists, report it.",
        True,
        "kubernetes",
    ),
    _E(
        "request-byte-limit",
        "Request too large",
        "An object is larger than Piceli's request bound.",
        "Reduce the object's size (for example move data out of a ConfigMap).",
        False,
        "kubernetes",
    ),
    _E(
        "response-byte-limit",
        "Response too large",
        "An API response exceeded Piceli's response bound.",
        "Reduce the objects' size; if a write was in flight, use `piceli release resume`.",
        False,
        "kubernetes",
    ),
    _E(
        "target-mismatch",
        "Target mismatch",
        "A request named a cluster or namespace other than the provider's configured target.",
        "Check `[target]` in the spec; plan again.",
        False,
        "kubernetes",
    ),
    _E(
        "server-target-identity-mismatch",
        "Cluster identity mismatch",
        "The cluster or namespace UID differs from the one pinned in the spec, or the namespace is being deleted.",
        "Check that the kubeconfig and context point at the intended cluster; update `cluster_uid`/`namespace_uid` only if the cluster was rebuilt.",
        False,
        "kubernetes",
    ),
    _E(
        "identity-mismatch",
        "Object identity mismatch",
        "The API server returned an object whose kind, name or namespace differs from the request.",
        "Plan again; if it persists, report it.",
        False,
        "kubernetes",
    ),
    _E(
        "scope-mismatch",
        "Scope mismatch",
        "A namespaced object was declared without the target namespace, or a cluster-scoped one with a namespace.",
        "Fix the object's namespace in the composition.",
        False,
        "kubernetes",
    ),
    _E(
        "undiscovered-api",
        "API not discovered",
        "A list request used an API resource that discovery did not return.",
        "Check that the CRD or API group is installed; plan again.",
        False,
        "kubernetes",
    ),
    _E(
        "invalid-force",
        "Invalid force flag",
        "A create was requested with force ownership, which is never allowed.",
        "This is an internal contract violation; report it.",
        False,
        "kubernetes",
    ),
    _E(
        "missing-precondition",
        "Missing write precondition",
        "An update was requested without the object's UID and resourceVersion.",
        "This is an internal contract violation; report it.",
        False,
        "kubernetes",
    ),
    _E(
        "invalid-write-response",
        "Invalid write response",
        "The API server's answer to a write did not confirm the requested object and ownership.",
        _RESUME,
        False,
        "kubernetes",
    ),
    _E(
        "takeover-conflict",
        "Takeover conflict",
        "Adopting an object by takeover kept conflicting with another field manager.",
        "Stop the other writer (controller, script) or plan the adoption again.",
        False,
        "kubernetes",
    ),
    _E(
        "not-retained",
        "Object is not retained",
        "A metadata-only adoption was requested for a kind that is not retained (only PVCs and Secrets are).",
        _REPLAN,
        False,
        "kubernetes",
    ),
    # ------------------------------------------------------------- execution
    _E(
        "authorization-expired",
        "Authorization expired",
        "The approved plan's authorization expired before the execution finished.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "absence-precondition-failed",
        "Object appeared",
        "The plan creates an object that now exists (someone created it after planning).",
        _REPLAN + " Add `--adopt Kind/name` if the release should take it over.",
        False,
        "execution",
    ),
    _E(
        "uid-version-precondition-failed",
        "Object changed since planning",
        "The object's UID or resourceVersion differs from the planned one.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "field-owner-precondition-failed",
        "Field owners changed",
        "The set of field managers on the object changed since planning.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "generation-precondition-failed",
        "Object generation changed",
        "The object's spec changed since planning.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "resource-content-precondition-failed",
        "Object content changed",
        "The object's content changed since planning.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "ownership-precondition-failed",
        "Ownership changed",
        "The object is not owned by this release (or another owner claimed it) and the plan does not adopt it.",
        _REPLAN + " Add `--adopt Kind/name` to take it over explicitly.",
        False,
        "execution",
    ),
    _E(
        "retained-resource",
        "Retained object not deleted",
        "The plan would delete a retained object (PersistentVolumeClaim or Secret); Piceli never deletes retained data.",
        "Delete it yourself after a backup if that is intended.",
        False,
        "execution",
    ),
    _E(
        "retained-content-precondition-failed",
        "Retained object content differs",
        "A retained object's live content differs from the declared content, so it cannot be adopted metadata-only.",
        "Make the declaration match the live object, then plan again.",
        False,
        "execution",
    ),
    _E(
        "retained-adoption-precondition-failed",
        "Not a retained object",
        "A metadata-only adoption was planned for an object that is not retained.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "no-op-content-mismatch",
        "No-op object drifted",
        "An object planned as unchanged no longer contains the declared content.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "invalid-field-ownership-evidence",
        "Invalid field-ownership evidence",
        "The object's managedFields could not be read.",
        "Plan again; if it persists, report the API server version.",
        False,
        "execution",
    ),
    _E(
        "ambiguous-write-blocked",
        "Ambiguous write blocked",
        "A previous write's result is unknown and the live object does not prove it was ours.",
        _RESUME,
        False,
        "execution",
    ),
    _E(
        "ambiguous-content-blocked",
        "Ambiguous write content differs",
        "A previous write's result is unknown and the live content differs from the plan.",
        _RESUME,
        False,
        "execution",
    ),
    _E(
        "ambiguous-delete-blocked",
        "Ambiguous delete blocked",
        "A previous delete's result is unknown and the object still exists.",
        _RESUME,
        False,
        "execution",
    ),
    _E(
        "recreated-object",
        "Object was recreated",
        "The object has another UID than planned: someone deleted and recreated it.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "deleted-resource-reappeared",
        "Deleted object reappeared",
        "An object the execution deleted exists again.",
        "Find the controller or script that recreates it, then plan again.",
        False,
        "execution",
    ),
    _E(
        "applied-resource-drift",
        "Applied object drifted",
        "An object changed after Piceli applied it (another writer is active).",
        "Stop the other writer, then plan again.",
        False,
        "execution",
    ),
    _E(
        "operation-identity-mismatch",
        "Operation identity mismatch",
        "The object carries another execution's operation annotation.",
        "Make sure only one apply runs at a time, then plan again.",
        False,
        "execution",
    ),
    _E(
        "compensation-already-started",
        "Compensation already started",
        "The execution is being compensated (undone) and cannot continue forward.",
        _REPLAN,
        False,
        "execution",
    ),
    _E(
        "readiness-timeout",
        "Readiness timeout",
        "An applied object did not become ready within `[execution] readiness_seconds`.",
        "Check the workload (`kubectl describe`, logs); fix it and plan again, or `piceli release rollback previous`.",
        False,
        "execution",
    ),
    _E(
        "readiness-unsupported",
        "Readiness unsupported",
        "Piceli cannot evaluate readiness for this kind.",
        "Report the kind; meanwhile verify it by hand.",
        False,
        "execution",
    ),
    _E(
        "spec-changed",
        "Build spec changed during the build",
        "build.toml's normalized declaration changed while the build ran.",
        "Stop editing the spec during a build, then run it again.",
        True,
        "build-spec",
    ),
    _E(
        "smoke-failed",
        "Smoke check failed",
        "An image's smoke command exited with an unexpected code; no receipt was written.",
        "Inspect the build log (`--log`), fix the image or the smoke declaration, rebuild.",
        False,
        "build-spec",
    ),
    _E(
        "smoke-timed-out",
        "Smoke check timed out",
        "An image's smoke command exceeded timeout_seconds; the container was removed.",
        "Fix the image or raise timeout_seconds (max 600), rebuild.",
        False,
        "build-spec",
    ),
    _E(
        "smoke-output-mismatch",
        "Smoke output did not match",
        "An image's smoke command exited as expected, but expect_stdout or "
        "expect_stderr was not found in the first 256 KiB of that stream; no "
        "receipt was written. The failed step lists the streams under `unmatched`.",
        "Read the excerpt on stderr or the build log (`--log`), then fix the image "
        "or the smoke pattern (a Python regular expression, searched per line with "
        "re.MULTILINE), rebuild.",
        False,
        "build-spec",
    ),
    _E(
        "smoke-env-secret",
        "Smoke env looks like a secret reference",
        "A smoke env value looks like a reference to secret material (for example "
        "`secret://` or `vault://`). Smoke env is recorded in previews, plans and "
        "receipts, so it may hold plain, non-secret values only.",
        "Give the smoke check a plain value (or a self-test mode that needs no "
        "secret); keep secrets in the release's secret store.",
        False,
        "build-spec",
    ),
    _E(
        "unknown-source",
        "Unknown source name",
        "`--only NAME` named a source that inputs.toml does not declare.",
        "Use a name declared as [[source]] name in inputs.toml.",
        False,
        "inputs",
    ),
    _E(
        "secret-key-missing",
        "Secret key missing",
        "An imported live Secret does not contain the requested key.",
        "Check the Secret's keys or fix `secret = { name, key }` in the spec.",
        False,
        "secrets",
    ),
    _E(
        "invalid-secret-data",
        "Invalid Secret data",
        "A live Secret's data could not be decoded (not base64, or not UTF-8 where text is required).",
        "Fix the live Secret, or import from a file or environment variable instead.",
        False,
        "secrets",
    ),
    _E(
        "secret-generator-failed",
        "Secret generator failed",
        "openssl failed, timed out, or did not match its openssl_sha256 pin.",
        "Fix the openssl path or pin, then plan again.",
        True,
        "secrets",
    ),
    _E(
        "secret-template-invalid",
        "Invalid secret template",
        "A template has a stray brace or a malformed placeholder.",
        "Double a brace to write it literally, and use {output} for values.",
        False,
        "secrets",
    ),
    _E(
        "secret-unknown-reference",
        "Unknown template reference",
        "A template placeholder names an output that no generator exposes.",
        "Use a listed output, e.g. {ca.ca.crt}; internal keys cannot be used.",
        False,
        "secrets",
    ),
    _E(
        "secret-dependency-cycle",
        "Secret dependency cycle",
        "Templates reference each other in a loop.",
        "Break the loop shown in the message.",
        False,
        "secrets",
    ),
    _E(
        "secret-import-unavailable",
        "Secret import unavailable",
        "The import source (file, env var, Secret or key) is missing, empty or unreadable, or the read was refused.",
        "Provide or fix the source, or grant get on the Secret; retry.",
        True,
        "secrets",
    ),
    _E(
        "secret-not-text",
        "Secret value is not text",
        "A raw value or template input is not valid UTF-8.",
        "Use base64 encoding for binary values.",
        False,
        "secrets",
    ),
    _E(
        "secret-rotation-refused",
        "Secret rotation refused",
        "--rotate named a template or static generator.",
        "Rotate the values the template uses, or edit the spec.",
        False,
        "secrets",
    ),
    _E(
        "secret-reveal-required",
        "Reveal not confirmed",
        "A secret value was requested without --reveal or a terminal confirmation.",
        "Add --reveal (owner only), or use --json for metadata only.",
        False,
        "secrets",
    ),
    _E(
        "secret-key-required",
        "Secret key required",
        "The generator has several outputs and no --key was given.",
        "Add --key with one of the listed outputs.",
        False,
        "secrets",
    ),
    _E(
        "secret-not-found",
        "Secret not found",
        "Unknown secret, key or release, or no release has been recorded yet.",
        "Check the name; the message lists what exists.",
        False,
        "secrets",
    ),
    _E(
        "render-target-invalid",
        "Render target invalid",
        "The module:attr target cannot be imported or is not an App, composition or composition function.",
        "Point at `module:attr` or `file.py:attr` of an App, DeploymentComposition or build(ctx) function.",
        False,
        "render",
    ),
    _E(
        "render-model-invalid",
        "Typed model invalid",
        "The typed model failed validation while rendering (for example a selector conflict or an ExistingClaim collision).",
        "Fix the model as the message describes; `piceli render` shows the result without a cluster.",
        False,
        "render",
    ),
    _E(
        "replace-precondition-failed",
        "Replace precondition failed",
        "At apply time the object is managed, retained or owned by another object, or no backup directory is available. Nothing was deleted.",
        "Plan again.",
        False,
        "execution",
    ),
    _E(
        "replace-backup-failed",
        "Replace backup failed",
        "The backup of the object could not be written (permissions, disk). Nothing was deleted.",
        "Fix the state directory, then plan again.",
        True,
        "execution",
    ),
    _E(
        "replace-delete-timeout",
        "Replaced object not deleted in time",
        "The deleted object was still present after readiness_seconds, usually because of finalizers. The execution is blocked.",
        "Inspect the finalizers, then resume or plan again.",
        True,
        "execution",
    ),
    _E(
        "replace-recreated-by-another-writer",
        "Replaced object recreated by another writer",
        "Another client created an object with the same name after the delete. The execution is blocked and that object is not touched.",
        "Decide which object to keep; the backup holds the deleted one.",
        False,
        "execution",
    ),
    _E(
        "replace-delete-not-observed",
        "Replace delete not observed",
        "On resume, the original object is still there although the journal recorded its delete. The execution is blocked.",
        "Inspect the object, then plan again.",
        False,
        "execution",
    ),
    _E(
        "invalid-metadata-change",
        "Invalid metadata change",
        "A metadata-only write was asked to set a non-string value or one of Piceli's own annotations.",
        "Fix the composition's labels or annotations.",
        False,
        "kubernetes",
    ),
    _E(
        "invalid-propagation",
        "Invalid delete propagation",
        "Internal guard: a delete used a propagation policy other than Background or Orphan.",
        "Report a bug; this should not happen.",
        False,
        "kubernetes",
    ),
    # --- WP3.4 diff ---
    _E(
        "invalid-dry-run-response",
        "Invalid dry-run response",
        "The API server's answer to a server-side dry run did not describe the requested object. The object gets no dry-run evidence and is compared literally.",
        "Nothing to fix for the plan (it may list the object as `apply`); if it persists, report the API server version.",
        True,
        "kubernetes",
    ),
    _E(
        "dry-run-limit-exceeded",
        "Too many dry runs",
        "The plan has more changed-candidate objects than the per-plan limit of server dry runs (256); the rest are compared literally.",
        "Nothing to fix for correctness; objects past the limit may be listed as `apply` although unchanged. Split the release to get exact no-ops.",
        False,
        "kubernetes",
    ),
    _E(
        "image-not-immutable",
        "Image reference is not immutable",
        "A build receipt entry has no registry digest, so its only reference is a movable tag.",
        "Deliver the image (`piceli artifacts deliver --to oci://…` or node import with a content tag `--ref repo:sha256-<12hex>`) and use the delivery receipt.",
        False,
        "images",
    ),
    _E(
        "receipt-invalid",
        "Receipt invalid",
        "A receipt could not be read, has an unknown schema, or has malformed fields.",
        "Pass a receipt written by `piceli artifacts build-spec run` or `piceli artifacts deliver`.",
        False,
        "images",
    ),
    _E(
        "delivery-not-succeeded",
        "Delivery did not succeed",
        "The delivery receipt's result is not pushed/imported/already-present.",
        "Deliver the image again and use the new receipt.",
        False,
        "images",
    ),
    _E(
        "image-digest-mismatch",
        "Image digest mismatch",
        "A pinned digest, or a build and delivery receipt for the same image, disagree on the digest.",
        "Use receipts from the same build, or update the pinned digest.",
        False,
        "images",
    ),
    _E(
        "image-declared-twice",
        "Image declared twice",
        "The same image name, or the same delivered image, appears in more than one source.",
        "Keep one declaration per image.",
        False,
        "images",
    ),
    _E(
        "receipt-unmatched",
        "Delivery receipt matches no image",
        "A delivery receipt in `images_from` matches no built image by config digest.",
        "Add the build receipt that produced the image, or use `[images.<name>] receipt = …`.",
        False,
        "images",
    ),
    # --- P7 access/status ---
    _E(
        "access-target-invalid",
        "Access target invalid",
        "TARGET is neither a readable release.toml whose composition yields an App "
        "or composition, nor `module:attr` of an object with `.app` (a piceli App) "
        "and `.target` (explicit kubeconfig, context and namespace).",
        "Pass `path/to/release.toml`, or `module:attr` of a pipeline object; the "
        "message says which part is missing.",
        False,
        "access",
    ),
    _E(
        "access-none-declared",
        "No access declared",
        "The app declares no forward, so there is nothing to supervise. A "
        "composition function that returns `app.composition(ctx)` hides the "
        "App's declarations.",
        "Add `access=app.access.forward(local=PORT)` to a Service, and return the "
        "App itself from the composition function.",
        False,
        "access",
    ),
    _E(
        "access-unknown-forward",
        "Unknown forward",
        "`--only` names a forward id the app does not declare.",
        "Use an id from `piceli status TARGET --json` (`access.forwards[].id`); "
        "it defaults to the Service name.",
        False,
        "access",
    ),
    _E(
        "access-port-conflict",
        "Declared local port already in use",
        "A required forward's local port is already held by another process "
        "(often an older `piceli access`, dashboard or `kubectl port-forward`). "
        "Piceli never takes a port over; the rejection lists each port's owner "
        "pid and command when it can be found.",
        "Stop the listed process (or the dashboard that supervises it), or change "
        "`local=` in the model, then run the command again.",
        False,
        "access",
    ),
    _E(
        "access-kubectl-missing",
        "kubectl required",
        "`piceli access` runs `kubectl port-forward` and no kubectl was found or "
        "it is not executable.",
        "Install kubectl or pass `--kubectl PATH`.",
        False,
        "access",
    ),
    _E(
        "access-forwards-failed",
        "Every forward failed",
        "All supervised forwards gave up: the restart budget was spent, or a "
        "port was taken by another process while supervising.",
        "Run `piceli status TARGET` to see whether the workloads are ready and "
        "who holds each port, fix it, then run `piceli access` again.",
        True,
        "access",
    ),
    _E(
        "status-cluster-unreadable",
        "Cluster unreadable",
        "Reading a workload failed (network, authentication, RBAC or timeout). "
        "The detail is withheld because it could contain credentials.",
        "Check that the target's kubeconfig context reaches the cluster and may "
        "read Deployments and Pods in the namespace, then retry.",
        True,
        "access",
    ),
    _E(
        "access-kubeconfig-invalid",
        "Kubeconfig unusable",
        "The target's kubeconfig or context cannot be loaded (missing file or "
        "context, exec/auth-provider credentials, insecure or proxied transport).",
        "Point the target at a kubeconfig file with a static-credential context; "
        "Piceli never falls back to the current context.",
        False,
        "access",
    ),
    _E(
        "status-release-unreadable",
        "Release state unreadable",
        "The release state directory (catalog, journal or history) could not be read.",
        "Check `[release] state_dir` and run `piceli release status --spec release.toml`.",
        False,
        "access",
    ),
    _E(
        "status-port-occupied",
        "Forward port held by another process",
        "A declared forward's local port is held by a process Piceli did not "
        "start for this declaration (another project's `kubectl port-forward`, "
        "a dev server, an orphaned forward). `piceli status` reports the forward "
        "as `occupied` with that process's pid only, never its command line, and "
        "never as `up`.",
        "Stop the process holding the port (`lsof -nP -iTCP:PORT -sTCP:LISTEN`) "
        "or change `local=`, then run `piceli access TARGET`.",
        True,
        "access",
    ),
    _E(
        "status-checks-unreadable",
        "Checks result unreadable",
        "The target's `last_checks()` hook raised.",
        "Run the checks again; the rest of the status is still valid.",
        True,
        "access",
    ),
    # --- D0b retrofit ---
    _E(
        "invalid-release-spec",
        "Invalid release spec",
        "release.toml could not be read or parsed, or a value in it is invalid (the message names the field).",
        "Fix the field named in `message`, then run `piceli release plan --spec release.toml`.",
        False,
        "release",
    ),
    _E(
        "invalid-composition",
        "Invalid composition",
        "The composition entry point could not be loaded, did not return a DeploymentComposition, declared a cluster-scoped object or another namespace, or its secret bindings do not match the declared secret inputs.",
        "Fix the composition function named by `[release] composition`, then plan again.",
        False,
        "release",
    ),
    _E(
        "invalid-adopt-entry",
        "Invalid adopt or replace entry",
        "An `--adopt`/`--replace` flag or a `[release] adopt`/`replace` entry is not `Kind/name` or `apiVersion/Kind/name`.",
        "Write the entry as `Kind/name`, e.g. `--adopt Deployment/web`.",
        False,
        "release",
    ),
    _E(
        "adopt-entry-not-declared",
        "Adopt entry names no declared object",
        "An adopt entry does not name exactly one resource that the composition declares (a typo is refused, never ignored).",
        "Use the kind and name of a resource the composition declares; add `apiVersion/` when two kinds share a name.",
        False,
        "release",
    ),
    _E(
        "replace-entry-not-declared",
        "Replace entry names no declared object",
        "A replace entry does not name exactly one resource that the composition declares.",
        "Use the kind and name of a resource the composition declares.",
        False,
        "release",
    ),
    _E(
        "adopt-and-replace",
        "Object named by adopt and replace",
        "The same object is listed for adoption and for replacement.",
        "Keep it in only one of `--adopt`/`[release] adopt` and `--replace`/`[release] replace`.",
        False,
        "release",
    ),
    _E(
        "resource-requires-adoption",
        "Existing object requires adoption",
        "An object the composition declares already exists and is not managed by this release's owner (see `blocking` for each object and the flags that unblock it).",
        "Plan again with `--adopt Kind/name` (or `--replace Kind/name` for non-retained objects), `[release] adopt`/`replace`, or `--adopt-all-desired`; or delete the object.",
        False,
        "release",
    ),
    _E(
        "replace-refused",
        "Replace refused",
        "A `--replace` entry names an object that may not be replaced: it is managed, retained or owned by another object (see `blocking`).",
        "Use `--adopt Kind/name` for an unmanaged object, or remove the entry from `--replace`/`[release] replace`.",
        False,
        "release",
    ),
    _E(
        "retained-content-differs",
        "Retained object differs",
        "A retained object's spec or data differs from the composition; only its labels and annotations may change.",
        "Change the composition to match the live object, then plan again.",
        False,
        "release",
    ),
    _E(
        "plan-blocked",
        "Plan blocked",
        "Several objects block the plan for different reasons; each is listed in `blocking` with its own `code`.",
        "Resolve every entry of `blocking` (run `piceli explain <code>` for each), then plan again.",
        False,
        "release",
    ),
    _E(
        "approve-with-planning-flags",
        "--approve combined with planning flags",
        "`--approve` executes a stored plan, so it cannot be combined with `--auto-approve`, `--rotate`, `--adopt`, `--replace` or `--adopt-all-desired`.",
        "Plan with those flags first, then run apply with only `--spec` and `--approve <hash>`.",
        False,
        "release",
    ),
    _E(
        "unknown-rotate-secret",
        "Unknown secret to rotate",
        "`--rotate` names a secret generator that `[secrets]` does not declare.",
        "Use a name declared under `[secrets]`.",
        False,
        "release",
    ),
    _E(
        "rotate-not-valid-for-rollback",
        "--rotate with rollback",
        "A rollback re-applies a stored release with its stored secret values, so it cannot rotate.",
        "Roll back without `--rotate`; rotate later with `piceli release plan --rotate NAME`.",
        False,
        "release",
    ),
    _E(
        "discovery-incomplete",
        "Discovery incomplete",
        "Live discovery could not read every kind the plan needs, so the plan would not be authoritative (the message lists the failing kinds).",
        "Check RBAC and API availability for the listed kinds, then plan again.",
        True,
        "release",
    ),
    _E(
        "cluster-identity-changed",
        "Cluster identity changed",
        "The cluster or namespace differs from the one recorded in this state directory; a state directory serves one cluster and namespace.",
        "Point `[target]` back at the recorded cluster, or use a new `state_dir` for the other cluster.",
        False,
        "release",
    ),
    _E(
        "invalid-plan-hash",
        "Invalid plan hash",
        "`--approve` is not 64 lowercase hex characters.",
        "Copy the full `plan_hash` from the `release plan` output.",
        False,
        "release",
    ),
    _E(
        "plan-not-found",
        "Plan not found",
        "No pending plan has this hash: it is unknown, expired or already applied.",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "plan-expired",
        "Plan expired",
        "The approved plan is older than `approval_window_seconds`.",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "plan-intent-mismatch",
        "Plan intent mismatch",
        "The hash approves an apply plan where a rollback plan was expected, or the reverse.",
        "Approve the hash printed by the same command (`release rollback <target>` for a rollback).",
        False,
        "release",
    ),
    _E(
        "plan-release-mismatch",
        "Plan release mismatch",
        "The hash approves a plan for another release than the rollback target.",
        "Run `piceli release rollback <target> --spec release.toml` and approve the hash it prints.",
        False,
        "release",
    ),
    _E(
        "unknown-release",
        "Unknown release",
        "The release name is not in this state directory's catalog.",
        "Run `piceli release status --spec release.toml` to list the releases.",
        False,
        "release",
    ),
    _E(
        "no-release-applied",
        "No release applied",
        "`rollback previous` was asked before any release became ready.",
        "Apply a release first; there is nothing to roll back to.",
        False,
        "release",
    ),
    _E(
        "no-previous-release",
        "No previous release",
        "Only one release has been ready, so `previous` has nothing to roll back to.",
        "Name a release explicitly (`piceli release status` lists them), or apply a new one.",
        False,
        "release",
    ),
    _E(
        "stored-discovery-missing",
        "Stored discovery missing",
        "The release was planned but its stored discovery is missing from the state directory.",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "release-owner-mismatch",
        "Release owner mismatch",
        "The stored release was planned for another owner or field manager than `[release]` now names.",
        "Restore the original `owner`/`field_manager`, or plan a new release.",
        False,
        "release",
    ),
    _E(
        "stored-release-mismatch",
        "Stored release mismatch",
        "The catalogued release no longer reproduces the approved plan.",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "stored-evidence-mismatch",
        "Stored evidence mismatch",
        "The stored discovery no longer reproduces the approved plan hash.",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "execution-refused",
        "Execution refused",
        "The executor refused the approved plan before changing anything (the message says why).",
        "Run `piceli release plan --spec release.toml` again and approve the new plan hash.",
        False,
        "release",
    ),
    _E(
        "resume-refused",
        "Resume refused",
        "The executor refused to resume the execution (the message says why).",
        "Run `piceli release status --spec release.toml`; plan and apply again if the execution cannot continue.",
        False,
        "release",
    ),
    _E(
        "no-execution-recorded",
        "No execution recorded",
        "There is no apply, rollback or resume of this release in the history.",
        "Check `--release`, or apply the release first.",
        False,
        "release",
    ),
    _E(
        "not-resumable",
        "Execution not resumable",
        "Only first applies of a created release can resume; re-applies and rollbacks cannot.",
        "Run `piceli release plan` (or `rollback`) again and approve the new plan.",
        False,
        "release",
    ),
    _E(
        "execution-not-started",
        "Execution not started",
        "The latest execution was recorded but never started, so there is nothing to stop.",
        "Run `piceli release status --spec release.toml` to see its state.",
        False,
        "release",
    ),
    _E(
        "nothing-to-stop",
        "Nothing to stop",
        "The latest execution of the release is already ready or cancelled.",
        "No action needed; `piceli release status` shows the result.",
        False,
        "release",
    ),
    _E(
        "execution-other-owner",
        "Execution belongs to another owner",
        "The execution was granted to another owner than `[release] owner`.",
        "Stop it with the spec (and owner) that started it.",
        False,
        "release",
    ),
    _E(
        "execution-other-target",
        "Execution belongs to another target",
        "The execution was granted for another cluster or namespace.",
        "Stop it with the spec whose `[target]` started it.",
        False,
        "release",
    ),
    _E(
        "release-history-malformed",
        "Release history malformed",
        "`history.json` in the state directory is not a valid history file.",
        "Restore the state directory from a backup; do not edit it by hand.",
        False,
        "release",
    ),
    _E(
        "release-refused",
        "Release command refused",
        "A release command was refused for a reason without a more specific code (the message says why).",
        "Read `message`; fix the input it names, then run the command again.",
        False,
        "release",
    ),
    _E(
        "release-state-unavailable",
        "Release state unavailable",
        "A file in the spec's `state_dir` (or a file the spec names) could not be read or written.",
        "Check that the paths exist and are readable and writable by this user.",
        True,
        "release",
    ),
    _E(
        "execution-not-ready",
        "Execution not ready",
        "The execution ran but did not become ready, and recorded no more specific failure (see `execution.state`).",
        "Run `piceli release status --spec release.toml`; resume, fix and apply, or roll back.",
        False,
        "release",
    ),
    _E(
        "kubeconfig-rejected",
        "Kubeconfig rejected",
        "The kubeconfig or context is missing, unreadable or uses a feature Piceli refuses (exec credentials, proxies, disabled TLS verification, a non-https server).",
        "Pass a kubeconfig file and an explicit context with a static certificate or token over https.",
        False,
        "kubernetes",
    ),
    _E(
        "cluster-identity-unreadable",
        "Cluster identity unreadable",
        "The kube-system namespace (the cluster identity) could not be read, or the answer had no UID.",
        "Check that the context can `get` namespaces (and pinned nodes), then retry.",
        True,
        "kubernetes",
    ),
    _E(
        "namespace-not-found",
        "Namespace not found",
        "The target namespace does not exist; Piceli never creates it implicitly.",
        "Create the namespace explicitly, then retry.",
        False,
        "kubernetes",
    ),
    _E(
        "node-not-found",
        "Node not found",
        "A node named in `[target.nodes]` does not exist.",
        "Fix the node name in the spec, or remove the entry.",
        False,
        "kubernetes",
    ),
    _E(
        "node-identity-mismatch",
        "Node identity mismatch",
        "A node's UID differs from the one pinned in the spec.",
        "Check the kubeconfig and context; update the pinned uid only if the node was replaced.",
        False,
        "kubernetes",
    ),
    _E(
        "invalid-inputs-spec",
        "Invalid inputs spec",
        "inputs.toml could not be parsed or declares an invalid source (the message names the field).",
        "Fix inputs.toml: only [[source]] tables with name, path and optional ref, allow_dirty and subpath.",
        False,
        "inputs",
    ),
    _E(
        "inputs-lock-invalid",
        "Invalid inputs lock",
        "The lock passed to `--lock` is not a valid `piceli inputs record` lock.",
        "Record a new lock with `piceli inputs record --spec inputs.toml --out inputs.lock`.",
        False,
        "inputs",
    ),
    _E(
        "source-not-git",
        "Source is not a git work tree",
        "A declared source path is not a directory or not the top level of a git work tree.",
        "Declare the repository root as `path` and use `subpath` for a directory inside it.",
        False,
        "inputs",
    ),
    _E(
        "source-has-no-commit",
        "Source has no commit",
        "The source repository has no commit at HEAD.",
        "Commit at least once, then record again.",
        False,
        "inputs",
    ),
    _E(
        "source-subpath-missing",
        "Source subpath missing",
        "The declared `subpath` does not exist in the source repository.",
        "Fix `subpath` in inputs.toml.",
        False,
        "inputs",
    ),
    _E(
        "source-dirty",
        "Source has uncommitted changes",
        "A source has uncommitted changes and does not set `allow_dirty = true`.",
        "Commit or stash the changes, or set `allow_dirty = true` for that source.",
        False,
        "inputs",
    ),
    _E(
        "source-ref-not-found",
        "Required ref not found",
        "The `ref` a source requires does not resolve to a commit in its repository.",
        "Fetch the ref or fix `ref` in inputs.toml.",
        False,
        "inputs",
    ),
    _E(
        "source-ref-mismatch",
        "Source not at required ref",
        "A source's HEAD differs from the commit its `ref` resolves to.",
        "Check out the required ref, or change `ref` in inputs.toml.",
        False,
        "inputs",
    ),
    _E(
        "git-unavailable",
        "git not available",
        "The `git` executable was not found on PATH.",
        "Install git or add it to PATH.",
        False,
        "inputs",
    ),
    _E(
        "git-timed-out",
        "git timed out",
        "A git call took longer than `--timeout` seconds.",
        "Retry, or pass a larger `--timeout`.",
        True,
        "inputs",
    ),
    _E(
        "source-capture-failed",
        "Source capture failed",
        "git could not describe a source (a git call failed, its output exceeded the budget, or a changed path has an unsupported type).",
        "Run `git status` in the source named in `message` and fix what it reports.",
        False,
        "inputs",
    ),
    _E(
        "inputs-io-error",
        "Inputs file unavailable",
        "A file the command reads or writes (spec, lock or `--out`) could not be accessed.",
        "Check the paths and their permissions.",
        True,
        "inputs",
    ),
    _E(
        "invalid-session-archive",
        "Invalid session archive",
        "The `--archive` file is not a canonical Piceli deployment session archive.",
        "Pass the session archive written by the release that deployed the objects.",
        False,
        "observe",
    ),
    _E(
        "invalid-access-profile",
        "Invalid access profile",
        "The access profile or `--ui-config` TOML could not be read or validated (the message names the field).",
        "Fix the TOML named in `message`.",
        False,
        "observe",
    ),
    _E(
        "unknown-shortcut",
        "Unknown shortcut id",
        "`--only` names a shortcut id the access profile does not declare.",
        "Use ids declared as [[shortcuts]] id in the profile.",
        False,
        "observe",
    ),
    _E(
        "forward-port-conflict",
        "Forward port conflict",
        "A required forward's local port is already in use or declared twice, or a shortcut has no namespace; nothing was started (see `preflight.errors`).",
        "Stop the process that owns the port, change `local_port` in the profile, or pass `--namespace`.",
        True,
        "observe",
    ),
    _E(
        "local-port-in-use",
        "Local port in use",
        "The `--port` for the local server is already in use.",
        "Choose another `--port`, or stop the process that owns it.",
        True,
        "observe",
    ),
    _E(
        "no-saved-forwards",
        "No saved forwards",
        "The user has no saved port-forward preferences.",
        "Save one with `piceli observe forward-save`.",
        False,
        "observe",
    ),
    _E(
        "unknown-forward",
        "Unknown saved forward",
        "The user has no saved port forward with this name.",
        "List them with `piceli observe forward-list --user USER`.",
        False,
        "observe",
    ),
    _E(
        "invalid-forward-preference",
        "Invalid forward preference",
        "The port-forward preference is invalid (name, namespace, target or ports).",
        "Use DNS names, a service/, deployment/ or pod/ target and ports between 1 and 65535.",
        False,
        "observe",
    ),
    _E(
        "invalid-preference-store",
        "Invalid preference store",
        "The preferences file is not a valid Piceli preference store.",
        "Fix or remove the file passed to `--preferences` (or the default one).",
        False,
        "observe",
    ),
    _E(
        "invalid-log-request",
        "Invalid log request",
        "The namespace, target, container or tail of the log request is invalid.",
        "Use a DNS namespace, a pod/ or workload target and `--tail` between 1 and 10000.",
        False,
        "observe",
    ),
    _E(
        "forward-unhealthy",
        "Forward unhealthy",
        "A required forward's health probe failed (see `forwards[].error`).",
        "Start the forwards with `piceli observe forwards apply`, or check the service behind the port.",
        True,
        "observe",
    ),
    _E(
        "invalid-release-catalog",
        "Invalid release catalog",
        "The `--catalog` file is not a valid Piceli release catalog.",
        "Pass the catalog written by Piceli.",
        False,
        "observe",
    ),
    _E(
        "promote-refused",
        "Promotion refused",
        "The promotion could not be recorded: the source release is unknown or the target name is taken or invalid (the message says which).",
        "Check the names with `piceli operator status`, then retry with a new target name.",
        False,
        "observe",
    ),
    _E(
        "operator-state-unavailable",
        "Operator state unavailable",
        "A file in the operator state directory is corrupt, or the directory cannot be read or written.",
        "Check `--state-dir` and its permissions; restore it with `piceli operator restore` if a file is corrupt.",
        False,
        "observe",
    ),
    _E(
        "state-locked",
        "Operator state locked",
        "Another process holds the operator state directory's writer lock.",
        "Stop the other writer (for example `piceli operator serve`), then retry.",
        True,
        "observe",
    ),
    _E(
        "backup-refused",
        "Backup refused",
        "The operator state could not be backed up (the message says why).",
        "Check `--state-dir` and that `--output` does not exist yet.",
        False,
        "observe",
    ),
    _E(
        "restore-refused",
        "Restore refused",
        "The backup archive is invalid or unsafe, or the destination is not empty.",
        "Restore a backup made by `piceli operator backup` into an empty directory.",
        False,
        "observe",
    ),
    _E(
        "command-failed",
        "Build command failed",
        "The pinned external command exited with a non-zero status.",
        "Fix the build inputs, preview again and approve the new plan.",
        False,
        "artifacts-delivery",
    ),
    _E(
        "command-timed-out",
        "Build command timed out",
        "The pinned external command ran longer than `--timeout`.",
        "Retry with a larger `--timeout`.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "command-cancelled",
        "Build command cancelled",
        "The pinned external command was cancelled before it finished.",
        "Run it again.",
        True,
        "artifacts-delivery",
    ),
    _E(
        "command-output-limit",
        "Build command output limit",
        "The pinned external command printed more output than allowed.",
        "Reduce the command's output, then run it again.",
        False,
        "artifacts-delivery",
    ),
    # --- P6 checks ---
    _E(
        "check-invalid",
        "Check declaration invalid",
        "A `[[checks]]` table or `Checks.*` call is malformed: an unknown type or key, a target kind the check type does not support, or two checks with the same name.",
        "Fix the declaration as the message says; `piceli release plan` validates `[[checks]]` without running them.",
        False,
        "checks",
    ),
    _E(
        "check-callable-invalid",
        "Python check cannot be loaded",
        "A `python` check's `call` names a module or file that cannot be imported, or an attribute that is not callable.",
        "Use `module:function` (importable) or `path/file.py:function` relative to release.toml.",
        False,
        "checks",
    ),
    _E(
        "check-failed",
        "Check failed",
        "A check ran and its condition was not met: an HTTP status outside `expect` or missing `body_contains`, an exec exit code or output mismatch, a metric sample violating the threshold (or no samples), or a Python check returning False or a failure string.",
        "Read the check's `detail`; fix the application and apply a new release, or roll back (`piceli release rollback previous`).",
        True,
        "checks",
    ),
    _E(
        "check-api-unavailable",
        "Kubernetes API unavailable for a check",
        "The check could not build an API client from the explicit kubeconfig context, or an API read failed (RBAC, network).",
        "Check the `[target]` kubeconfig and context and that the credentials may read Services, Pods and workloads in the namespace.",
        True,
        "checks",
    ),
    _E(
        "check-target-not-found",
        "Check target not found",
        "The check's target Service, workload or pod does not exist in the namespace, or the workload has no ready pod.",
        "Check the target name (`kind/name`) against the composition; for exec, wait until a pod is ready.",
        True,
        "checks",
    ),
    _E(
        "check-port-unknown",
        "Check port unknown",
        "An http or metric check has no `port` and its target declares none.",
        "Set `port = …` on the check.",
        False,
        "checks",
    ),
    _E(
        "check-forward-unavailable",
        "Check port forward unavailable",
        "The temporary loopback port forward to the target did not become healthy in time, or the connection through it failed.",
        "Make sure `kubectl` is on PATH and the target has a ready pod listening on the port; run `piceli release check` to retry.",
        True,
        "checks",
    ),
    _E(
        "check-timed-out",
        "Check timed out",
        "One attempt took longer than the check's `timeout`.",
        "Raise `timeout` or `retries`, or find out why the endpoint or command is slow.",
        True,
        "checks",
    ),
    _E(
        "check-exec-unavailable",
        "Check exec unavailable",
        "The Kubernetes API refused or could not run the exec (for example no `pods/exec` permission, or the command does not exist in the container).",
        "Grant `create` on `pods/exec` in the namespace, or fix `command`/`container`.",
        False,
        "checks",
    ),
    _E(
        "check-metric-invalid",
        "Metric response invalid",
        "The metric endpoint did not answer with a successful Prometheus query result of type vector or scalar.",
        "Point the check at a Prometheus-compatible query API (`path`, `port`) and check the query.",
        False,
        "checks",
    ),
    _E(
        "check-raised",
        "Check raised an exception",
        "A Python check raised an unexpected exception or returned an unsupported value; only the exception type is recorded.",
        "Run the function locally; raise `piceli.checks.CheckFailed(detail)` or return False/a string to fail on purpose.",
        False,
        "checks",
    ),
    _E(
        "checks-rollback-unavailable",
        "No release to roll back to",
        "A release failed its checks with `rollback_on_failed_checks = true`, but no other release has ever been ready here.",
        "Fix the application and apply a new release; the failed release is left running and is not selected.",
        False,
        "checks",
    ),
    _E(
        "checks-rollback-failed",
        "Automatic rollback failed",
        "A release failed its checks and the automatic rollback to the previous release was refused, did not become ready or failed its own checks.",
        "Run `piceli release status` and roll back by hand (`piceli release rollback previous`), with `--skip-checks` only in an emergency.",
        False,
        "checks",
    ),
    # --- WP3.1 exec auth ---
    _E(
        "target-refused",
        "Cluster target refused",
        "The kubeconfig or context is not acceptable (missing or ambiguous context, unsupported user fields, proxy, insecure TLS, non-https server, invalid certificate data) or the cluster's observed identity differs from the expected one. The message names the cause; nothing was changed.",
        "Fix the kubeconfig, the named context (`[target]` or `--context`) or the expected UIDs as the message says, then run the command again.",
        False,
        "target",
    ),
    _E(
        "exec-auth-not-allowed",
        "Exec credential plugin not allowed",
        "The target context's kubeconfig user runs an exec credential plugin (for example gke-gcloud-auth-plugin, aws or kubelogin) and `[target]` does not set `allow_exec = true`. The plugin was not run.",
        "Review the kubeconfig user's `exec` command, then add `allow_exec = true` (and ideally `exec_sha256`) to `[target]`; see docs/managed_clusters.md.",
        False,
        "target",
    ),
    _E(
        "auth-provider-refused",
        "Legacy auth-provider refused",
        "The target context's kubeconfig user uses a legacy `auth-provider` (gcp, oidc, azure). Piceli never runs these.",
        "Regenerate the kubeconfig for the provider's exec plugin (`gke-gcloud-auth-plugin`, `kubelogin convert-kubeconfig`, an OIDC exec plugin) and set `allow_exec = true`.",
        False,
        "target",
    ),
    _E(
        "exec-config-invalid",
        "Exec configuration invalid",
        "The kubeconfig `exec` block is malformed (missing command, apiVersion other than client.authentication.k8s.io/v1 or v1beta1, bad args/env), its cluster CA data is not base64, or `exec_sha256` is set for a user without an exec plugin.",
        "Fix the kubeconfig user or the `[target]` exec keys (regenerate the kubeconfig with the provider's CLI when in doubt).",
        False,
        "target",
    ),
    _E(
        "exec-command-not-found",
        "Exec command not found",
        "The exec plugin command is not in `PATH` (a bare name) or does not exist (a path, resolved from the kubeconfig's directory).",
        "Install the plugin, or put its directory on `PATH`, then run the command again.",
        False,
        "target",
    ),
    _E(
        "exec-command-unsafe",
        "Exec command unsafe",
        "The resolved exec command is not a regular executable file, exceeds 256 MB, or is writable by its group or other users.",
        "Install the plugin somewhere only its owner can write (`chmod go-w <file>`), then run the command again.",
        False,
        "target",
    ),
    _E(
        "exec-pin-mismatch",
        "Exec command pin mismatch",
        "The resolved exec command's sha256 differs from `exec_sha256` in `[target]`, or the file changed after Piceli pinned it during this run.",
        "Check that the plugin upgrade is expected, then set `exec_sha256` to the digest named in the message (`shasum -a 256 <resolved path>`).",
        False,
        "target",
    ),
    _E(
        "exec-interactive-required",
        "Exec plugin needs a terminal",
        "The kubeconfig exec block sets `interactiveMode: Always`; Piceli runs plugins without a terminal.",
        "Log in with the plugin's own command first (for example `kubelogin get-token` or `gcloud auth login`) and use `interactiveMode: IfAvailable` or `Never`.",
        False,
        "target",
    ),
    _E(
        "exec-plugin-failed",
        "Exec plugin failed",
        "The exec credential plugin could not start or exited with a non-zero status; its own message is on stderr.",
        "Follow the plugin's message (usually: log in again, for example `gcloud auth login`, `aws sso login`, `az login`), then run the command again.",
        False,
        "target",
    ),
    _E(
        "exec-plugin-timed-out",
        "Exec plugin timed out",
        "The exec credential plugin did not finish within `exec_timeout_seconds` and was stopped.",
        "Run the command again; if it persists, check the plugin's network access or raise `exec_timeout_seconds`.",
        True,
        "target",
    ),
    _E(
        "exec-credential-invalid",
        "Exec credential invalid",
        "The plugin's output is not a valid ExecCredential of the configured apiVersion: not JSON, over 1 MB, no token or client certificate, invalid PEM, or an expiry in the past.",
        "Run the plugin by hand and check its output format; upgrade the plugin if it is outdated.",
        False,
        "target",
    ),
    # --- P9 import/testing ---
    _E(
        "import-select-invalid",
        "Invalid import selector",
        "A `--select` value is neither `Kind/name` (for example `Deployment/api`) nor `label=value`.",
        "Fix the selector; repeat `--select` to import several objects.",
        False,
        "import",
    ),
    _E(
        "import-nothing-selected",
        "Nothing to import",
        "The namespace or directory holds no importable object, or no object matches `--select`.",
        "Check the namespace or directory and the selectors (kinds are case-sensitive: `Deployment/api`).",
        False,
        "import",
    ),
    _E(
        "import-name-invalid",
        "Invalid app name",
        "The app name (`--name`, or the namespace by default) is not a DNS label.",
        "Pass `--name` with lowercase letters, digits and `-` (at most 63 characters).",
        False,
        "import",
    ),
    _E(
        "import-target-invalid",
        "Import target refused",
        "The kubeconfig, context or namespace cannot be used: the file is missing or invalid, the context is unknown or uses exec/auth-provider credentials, the server is not https, or the namespace does not exist.",
        "Pass an explicit `--kubeconfig` file and `--context` with static credentials, and an existing `--namespace`.",
        False,
        "import",
    ),
    _E(
        "import-discovery-failed",
        "Cluster read failed during import",
        "Listing one of the imported kinds failed (the category, such as `rbac-denied` or `api-unavailable`, is shown on stderr). Nothing was written.",
        "Grant `list` on ConfigMaps, Secrets, Services, PersistentVolumeClaims, Deployments and NetworkPolicies in the namespace, or retry when the API server is reachable.",
        True,
        "import",
    ),
    _E(
        "import-manifests-invalid",
        "Manifest directory invalid",
        "`piceli import yaml` found no directory, a file that is not YAML or JSON, a document without `apiVersion`, `kind` and `metadata.name`, an object declared twice, or objects in more than one namespace.",
        "Fix the file named on stderr, or pass `--namespace` to choose the namespace.",
        False,
        "import",
    ),
    _E(
        "import-roundtrip-mismatch",
        "Generated module does not reproduce the objects",
        "The generated module did not render back to every imported field. This is a bug in the importer; nothing was written.",
        "Report it with the object kinds involved; meanwhile import the other objects with `--select`.",
        False,
        "import",
    ),
    _E(
        "import-output-refused",
        "Import output refused",
        "The `--out` file already exists, or its directory does not exist.",
        "Pass `--force` to overwrite the file, or choose another path.",
        False,
        "import",
    ),
    # --- P5 pipeline ---
    _E(
        "pipeline-not-found",
        "Pipeline not found",
        "The `MODULE:ATTR` given to `piceli deploy` (or to `piceli release … --spec`) does not name a file or module, or its attribute is not a `Pipeline`.",
        "Pass `path/to/app.py:pipeline` or `package.module:pipeline` naming a `piceli.Pipeline` object.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-load-failed",
        "Pipeline module failed to import",
        "Importing the pipeline's module raised an exception (the message on stderr names it).",
        "Fix the module until `python path/to/app.py` imports cleanly, then run the command again.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-invalid",
        "Pipeline declaration invalid",
        "The Pipeline, Target, Build, delivery strategy or secrets are inconsistent (for example a build without `deliver=`, an unknown node alias or a multi-platform build).",
        "Fix the declaration as the message on stderr describes; `piceli deploy … --plan` checks it again without executing anything.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-image-unknown",
        "Build image unknown",
        'The app uses a build image handle (`build["name"]`) that no build of the pipeline produces.',
        "Use one of the build's `[[output.image]]` names, or add the build that produces it to `build=`.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-image-not-pinned",
        "Image not pinned",
        "A workload uses an image that is neither a build handle nor pinned by digest, so the release could reference a tag that moves.",
        "Pin it as `repository@sha256:<digest>` (for example from `docker buildx imagetools inspect`), or build it with the pipeline.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-plan-changed",
        "Combined plan changed",
        "The hash passed to `--approve` is not the combined hash of the current plan: a source, image, cluster object or the pipeline changed since it was planned.",
        "Run `piceli deploy MODULE:ATTR --plan` again, review it and approve the new combined hash.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-nothing-to-resume",
        "Nothing to resume",
        "`--resume` found no interrupted or failed run in the pipeline's state directory (the latest run finished, stopped at `--until`, or none exists).",
        "Run `piceli deploy MODULE:ATTR --plan` and approve a new run; unchanged stages are skipped.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-resume-changed",
        "Pipeline changed since the run was approved",
        "`--resume` would re-run a stage whose inputs no longer match the approved run (a build's staged files, the release, or the app's target or owner).",
        "Plan and approve a new run: `piceli deploy MODULE:ATTR --plan`.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-locked",
        "Pipeline state directory in use",
        "Another `piceli deploy` run holds the lock of this pipeline's state directory.",
        "Wait for the other run to finish, then run the command again.",
        True,
        "pipeline",
    ),
    _E(
        "pipeline-release-refused",
        "Release refused",
        "The release engine refused the plan or apply stage (for example an unmanaged object that needs adoption); stderr has the reason and the blocking objects.",
        'Apply the suggestion on stderr (for example `adopt=["Kind/name"]` or `replace=[…]` on the Pipeline), then plan again.',
        False,
        "pipeline",
    ),
    _E(
        "pipeline-stage-error",
        "Stage failed unexpectedly",
        "A stage raised an unexpected local error (a file or tool could not be used); stderr has the error type.",
        "Fix the local problem, then continue with `piceli deploy MODULE:ATTR --resume`.",
        True,
        "pipeline",
    ),
    _E(
        "pipeline-delivery-failed",
        "Image delivery failed",
        "Delivering a built image did not succeed and its receipt carries no more specific code.",
        "Check the registry or node, then continue with `piceli deploy MODULE:ATTR --resume`.",
        True,
        "pipeline",
    ),
    _E(
        "pipeline-registry-not-ready",
        "Node-loopback registry not ready",
        "The registry release of `NodeLoopbackRegistry` was applied but did not become ready (image pull, volume or node problem).",
        "Inspect the registry pod with a read-only tool, fix it, then run `piceli deploy MODULE:ATTR --resume`.",
        True,
        "pipeline",
    ),
    _E(
        "pipeline-apply-not-ready",
        "Release not ready",
        "The release was applied but did not become ready in time; the result has the execution's `failure_category`.",
        "Fix the workload (image, probe, resources) and continue with `piceli deploy MODULE:ATTR --resume`, or deploy the previous source.",
        True,
        "pipeline",
    ),
    _E(
        "pipeline-checks-failed",
        "Post-deploy checks failed",
        "The release was applied but at least one check failed, so the run is not ready. With `rollback_on_failed_checks` the previous release was re-applied (see `checks.rollback` in the result).",
        "Read the check results in the result JSON, fix the application and deploy again.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-not-delivered",
        "Pipeline images not delivered",
        "`piceli release plan|preview|diff|apply --spec MODULE:ATTR` plans a new release from the pipeline's current model, but a build image it uses was not built from the current build inputs and delivered (or no image of the pipeline was ever delivered). The release commands never build.",
        "Run `piceli deploy MODULE:ATTR` (it builds and delivers only what changed). Commands on existing releases (`status`, `rollback`, `secret show`, `stop`, `resume`, `check`) use the recorded images and need no new delivery.",
        False,
        "pipeline",
    ),
    _E(
        "pipeline-checks-unavailable",
        "Checks runner unavailable",
        "The pipeline declares checks but `piceli.checks` is not available in this installation.",
        "Install a Piceli version that ships `piceli.checks`, or remove `checks=` from the Pipeline.",
        False,
        "pipeline",
    ),
    _E(
        "deploy-flags-conflict",
        "Conflicting deploy flags",
        "`piceli deploy` got flags that cannot be combined (`--resume` with planning flags, `--approve` with `--plan` or `--auto-approve`, or `--plan` with `--auto-approve`).",
        "Use `--plan`, then `--approve HASH`; or `--auto-approve` alone; or `--resume` alone.",
        False,
        "cli",
    ),
    _E(
        "deploy-stage-unknown",
        "Unknown stage",
        "`--until` names a stage that does not exist.",
        "Use one of inputs, build, deliver, plan, apply or checks.",
        False,
        "cli",
    ),
)


def lookup(code: str) -> ErrorCode | None:
    """The registry entry for ``code``, or ``None`` when it is unknown."""
    return ERRORS.get(code)
