"""Generate ``docs/reference/errors.md`` and ``docs/reference/cli.md``.

Both pages are generated from code — the error registry
(:data:`piceli.errors.ERRORS`) and the CLI tree (:func:`piceli.cli_contract.help_tree`)
— so they cannot drift from what the commands do::

    python -m piceli.reference_docs          # rewrite the pages
    python -m piceli.reference_docs --check  # exit 1 when a page is stale (CI)

Importing this module is side-effect free.
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

from piceli.cli_contract import EXIT_CODES, help_tree, leaf_commands
from piceli.errors import AREAS, ERRORS

GENERATED = (
    "<!-- Generated by `python -m piceli.reference_docs` from {source}. "
    "Do not edit by hand. -->"
)
DOCS = Path(__file__).resolve().parent.parent / "docs"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def render_errors() -> str:
    """The errors reference page, grouped by area, as MyST Markdown."""
    lines = [
        GENERATED.format(source="`piceli/errors.py`"),
        "",
        "# Error codes",
        "",
        'Every refusal prints `{"state": "rejected", "reason": "<code>"}`, and '
        "receipts and execution results name failures with the same codes. Each "
        "entry says what caused it, what to do next and whether re-running the "
        "same command unchanged can succeed (**retry-safe**). The same entries "
        "are available offline:",
        "",
        "```sh",
        "piceli explain <code>          # human text",
        "piceli explain <code> --json   # the structured entry",
        "```",
        "",
        "Codes never contain paths, secret values or server messages. See "
        "{doc}`../agents` for how an agent should react to them.",
        "",
        "## Index",
        "",
        "| Code | Area | Retry-safe |",
        "| --- | --- | --- |",
    ]
    for entry in ERRORS.values():
        lines.append(
            f"| [`{entry.code}`](#error-{entry.code}) | {entry.area} | "
            f"{'yes' if entry.retry_safe else 'no'} |"
        )
    for area, description in AREAS.items():
        entries = [entry for entry in ERRORS.values() if entry.area == area]
        if not entries:
            continue
        lines += ["", f"## {description}", ""]
        for entry in entries:
            lines += [
                f"(error-{entry.code})=",
                f"### `{entry.code}`",
                "",
                f"**{entry.title}.** {entry.cause}",
                "",
                f"- **Fix:** {entry.fix}",
                f"- **Retry-safe:** {'yes' if entry.retry_safe else 'no'}",
                "",
            ]
    return "\n".join(lines).rstrip() + "\n"


def _first_paragraph(text: str) -> str:
    return _cell(text.strip().split("\n\n")[0]) if text.strip() else ""


def _default(param: Mapping[str, Any]) -> str:
    if "envvar" in param:
        # Env-backed defaults depend on the environment: show the variable.
        return f"env `{param['envvar']}`"
    if param.get("required"):
        return "required"
    value = param.get("default")
    if value is None or value == [] or value == "":
        return ""
    return f"`{value}`"


def _params_table(params: Sequence[Mapping[str, Any]]) -> list[str]:
    if not params:
        return ["No options."]
    rows = ["| Option | Type | Default | Description |", "| --- | --- | --- | --- |"]
    for param in params:
        flags = ", ".join(f"`{flag}`" for flag in param.get("flags", ())) or (
            f"`{param['name'].upper()}`"
        )
        kind = param["type"] + (" (repeatable)" if param.get("multiple") else "")
        rows.append(
            f"| {flags} | {kind} | {_default(param)} | {_cell(param.get('help', ''))} |"
        )
    return rows


def _contract(contract: Mapping[str, Any] | None) -> list[str]:
    if contract is None:
        return ["No contract recorded."]
    effects = contract["side_effects"]
    reads = ", ".join(effects["reads"]) or "nothing"
    writes = ", ".join(effects["writes"]) or "nothing (read-only)"
    exits = ", ".join(
        f"`{code}` {text}" for code, text in contract["exit_codes"].items()
    )
    lines = [
        f"- **Reads:** {reads}",
        f"- **Writes:** {writes}",
        f"- **Cluster:** {effects['cluster']}",
        f"- **Approval required:** {'yes' if contract['approval_required'] else 'no'}",
        f"- **Safe to retry:** {'yes' if contract['safe_to_retry'] else 'no'}",
        f"- **Exit codes:** {exits}",
        f"- **Output contract:** {contract['contract']}",
    ]
    if contract.get("notes"):
        lines.append(f"- **Notes:** {contract['notes']}")
    return lines


def render_cli(tree: Mapping[str, Any] | None = None) -> str:
    """The CLI reference page, generated from ``piceli help-json``."""
    tree = tree if tree is not None else help_tree()
    root = tree["root"]
    lines = [
        GENERATED.format(source="`piceli help-json`"),
        "",
        "# Command reference",
        "",
        "Every `piceli` command with its options and its contract: what it "
        "reads and writes, whether it contacts a cluster, whether it needs "
        "approval and whether it is safe to retry. The same data is available "
        "as JSON from `piceli help-json` (or `piceli --help-json`).",
        "",
        "## Conventions",
        "",
        "- **stdout** is for machine output: one JSON object (JSON lines for "
        "streaming commands; `render` prints YAML manifests unless "
        "`--format json`).",
        "- **stderr** is for human text: summaries and hints.",
        '- A refusal prints `{"state": "rejected", "reason": "<code>", '
        '"message": "<text>"}` and exits `2`; see {doc}`errors` or run '
        "`piceli explain <code>`.",
        "- **Output contract** `conforms` means the command follows these rules "
        "exactly; `partial` (no command since 0.5.1) means it prints JSON but "
        "its refusals do not yet use the rejection shape above.",
        "",
        "| Exit code | Meaning |",
        "| --- | --- |",
        *(f"| `{code}` | {_cell(text)} |" for code, text in EXIT_CODES.items()),
        "",
        "## Commands",
        "",
        "| Command | Summary | Cluster | Approval |",
        "| --- | --- | --- | --- |",
    ]
    leaves = sorted(
        (leaf for leaf in leaf_commands(root) if leaf is not root),
        key=lambda leaf: leaf["path"],
    )
    for leaf in leaves:
        contract = leaf.get("contract") or {}
        anchor = "cli-" + leaf["path"].replace(" ", "-")
        cluster = contract.get("side_effects", {}).get("cluster", "")
        approval = "yes" if contract.get("approval_required") else "no"
        lines.append(
            f"| [`piceli {leaf['path']}`](#{anchor}) | "
            f"{_first_paragraph(leaf.get('help', ''))} | {cluster} | {approval} |"
        )
    for leaf in leaves:
        anchor = "cli-" + leaf["path"].replace(" ", "-")
        lines += [
            "",
            f"({anchor})=",
            f"### `piceli {leaf['path']}`",
            "",
            _first_paragraph(leaf.get("help", "")) or "No description.",
            "",
            *_params_table(leaf["params"]),
            "",
        ]
        if leaf.get("mutually_exclusive"):
            groups = "; ".join(
                " / ".join(f"`{name}`" for name in group)
                for group in leaf["mutually_exclusive"]
            )
            lines += [f"Mutually exclusive: {groups}.", ""]
        lines += ["**Contract**", "", *_contract(leaf.get("contract"))]
    return "\n".join(lines).rstrip() + "\n"


def pages(docs: Path = DOCS) -> dict[Path, str]:
    """Each generated page's path and expected content."""
    return {
        docs / "reference" / "errors.md": render_errors(),
        docs / "reference" / "cli.md": render_cli(),
    }


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m piceli.reference_docs")
    parser.add_argument("--check", action="store_true", help="fail if stale")
    parser.add_argument("--docs", type=Path, default=DOCS)
    args = parser.parse_args(arguments)
    stale = []
    for path, content in pages(args.docs).items():
        current = path.read_text() if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path}", file=sys.stderr)
    for path in stale:
        print(f"stale: {path}; run `python -m piceli.reference_docs`", file=sys.stderr)
    return 1 if stale else 0


if __name__ == "__main__":
    raise SystemExit(main())
