apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: webapp-dev
resources:
  - ../../base
replicas:
  - name: web
    count: 1
patches:
  - target: {kind: ConfigMap, name: settings}
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: debug
  - target: {kind: HorizontalPodAutoscaler, name: web}
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
