"""Secret generators for a pipeline, and references the app binds before values exist.

The generators are the ``[secrets.*]`` types of ``release.toml`` (see
:doc:`secrets`). Values are generated by the release engine only after a plan
is accepted, stored privately and carried over between releases; the app
only ever holds opaque references::

    secrets = Secrets(
        cache_password=Random(32),
        cache_url=Template("redis://:{cache_password}@cache:6379/0"),
    )
    app.secret("cache", {"url": secrets.ref("cache_url")})

Importing this module is side-effect free.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING, Any

from piceli.pipeline.errors import PipelineError

if TYPE_CHECKING:
    from piceli.k8s.ops.secret_versions import SecretVersionRef
    from piceli.k8s.release_secret_spec import (
        GeneratorSpec,
        RandomSecretSpec,
        StaticSecretSpec,
        TemplateSecretSpec,
        TlsCaSpec,
    )

_NAME = re.compile(r"[a-z][a-z0-9_-]{0,62}")


def placeholder(name: str) -> SecretVersionRef:
    """The value-free reference of one secret input (stable per name).

    It is the same reference ``piceli release`` and ``piceli render`` use for
    previews; ``piceli deploy`` rebinds it to the real version at apply time.
    """
    from piceli.k8s.ops.secret_versions import SecretVersionRef

    return SecretVersionRef("0" * 32, hashlib.sha256(name.encode()).hexdigest()[:32])


def Random(bytes: int = 32, *, encoding: str = "base64") -> RandomSecretSpec:
    """A URL-safe random token of ``bytes`` random bytes."""
    from piceli.k8s.release_secret_spec import RandomSecretSpec

    return RandomSecretSpec.model_validate(
        {"type": "random", "bytes": bytes, "encoding": encoding}
    )


def Template(text: str, *, encoding: str = "base64") -> TemplateSecretSpec:
    """Text with ``{name}`` placeholders for other outputs, rendered privately."""
    from piceli.k8s.release_secret_spec import TemplateSecretSpec

    return TemplateSecretSpec.model_validate(
        {"type": "template", "template": text, "encoding": encoding}
    )


def Static(value: str, *, encoding: str = "base64") -> StaticSecretSpec:
    """A public, non-secret value that templates can reference."""
    from piceli.k8s.release_secret_spec import StaticSecretSpec

    return StaticSecretSpec.model_validate(
        {"type": "static", "value": value, "encoding": encoding}
    )


def TlsCa(
    leaves: Mapping[str, Sequence[str]],
    *,
    common_name: str = "piceli private CA",
    days: int = 365,
    ca_days: int = 3650,
) -> TlsCaSpec:
    """A private CA plus one leaf certificate per entry (``name → DNS names``).

    Outputs: ``<secret>.ca.crt`` and ``<secret>.<leaf>.crt``/``.key``. Needs
    ``/usr/bin/openssl``.
    """
    from piceli.k8s.release_secret_spec import TlsCaSpec

    return TlsCaSpec.model_validate(
        {
            "type": "tls-ca",
            "common_name": common_name,
            "days": days,
            "ca_days": ca_days,
            "leaves": {
                name: {"dns_names": list(names)} for name, names in leaves.items()
            },
        }
    )


class Secrets:
    """Named secret generators and the references an app binds to their outputs.

    :param generators: Generator name → spec (``Random``, ``Template``,
        ``Static``, ``TlsCa`` or any ``release.toml`` secret spec).

    :meth:`ref` returns an opaque reference to one output: the generator name
    for single-value generators, ``<name>.<key>`` for multi-output ones
    (``ca.cache.crt``). Unknown names are refused when declared.
    """

    def __init__(self, **generators: GeneratorSpec) -> None:
        from piceli.k8s.release_secret_spec import check_secrets

        for name in generators:
            if not _NAME.fullmatch(name):
                raise PipelineError("pipeline-invalid", f"invalid secret name {name!r}")
        try:
            check_secrets(generators)
        except ValueError as error:
            raise PipelineError("pipeline-invalid", str(error)) from None
        self.generators: dict[str, GeneratorSpec] = dict(generators)

    def inputs(self) -> tuple[str, ...]:
        """Every output an app may bind (internal ones such as a CA key excluded)."""
        from piceli.k8s.release_secrets import input_names

        return tuple(
            item
            for name, spec in self.generators.items()
            for item in input_names(name, spec)
        )

    def ref(self, name: str) -> SecretVersionRef:
        """An opaque reference to the output ``name`` (bound at apply time)."""
        known = self.inputs()
        if name not in known:
            raise PipelineError(
                "pipeline-invalid", f"unknown secret output {name!r}; outputs: {known}"
            )
        return placeholder(name)

    def __getitem__(self, name: str) -> SecretVersionRef:
        return self.ref(name)

    def __repr__(self) -> str:
        return f"Secrets({sorted(self.generators)})"


def as_generators(value: Any) -> dict[str, Any]:
    """Normalize ``Secrets`` or a mapping to ``name → spec``."""
    if isinstance(value, Secrets):
        return dict(value.generators)
    return dict(value or {})
