"""Generate browser types from the public service JSON schemas."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from piceli.services import contracts


def typescript(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(typescript(item) for item in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{typescript(schema['items'])}>"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            return (
                "{ "
                + "; ".join(
                    f"{json.dumps(key)}{'' if key in required else '?'}: {typescript(value)}"
                    for key, value in schema["properties"].items()
                )
                + " }"
            )
        extra = schema.get("additionalProperties", {})
        return f"Record<string, {typescript(extra) if isinstance(extra, dict) else 'unknown'}>"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }.get(kind, "unknown")


def generate() -> str:
    definitions: dict[str, Any] = {}
    for name, model in vars(contracts).items():
        if (
            isinstance(model, type)
            and issubclass(model, contracts.Record)
            and model is not contracts.Record
        ):
            schema = model.model_json_schema(mode="serialization")
            definitions.update(schema.pop("$defs", {}))
            definitions[name] = schema
    return (
        "// Generated by scripts/ui_contract.py; do not edit.\n"
        + "\n".join(
            f"export type {name} = {typescript(schema)};"
            for name, schema in sorted(definitions.items())
        )
        + "\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = Path(__file__).resolve().parents[1] / "ui/src/api/generated.ts"
    rendered = generate()
    if args.check:
        if not target.exists() or target.read_text() != rendered:
            raise SystemExit("UI types are stale; run python scripts/ui_contract.py")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
