"""One app, three environments (dev, staging, prod), with typed custom resources.

The Certificate (cert-manager) and ServiceMonitor (Prometheus operator)
models in ``crds/`` were generated by ``piceli codegen crd`` from the pinned
CRDs in ``tests/fixtures/crds``; see docs/crds.md and docs/environments.md.

piceli render examples/environments/app.py:app --env prod
piceli render examples/environments/app.py:app --env staging --diff-env prod
piceli render examples/environments/app.py:pipeline --env dev --format json
piceli deploy examples/environments/app.py:pipeline --env prod --plan
"""

from __future__ import annotations

from crds import certificate, service_monitor

from piceli import App, Pipeline, Resources, ServicePort, Target

API_IMAGE = "registry.example/shop/api@sha256:" + "a1" * 32

app = App("shop")
settings = app.config("settings", {"LOG_LEVEL": "debug", "CHECKOUT": "on"})
api = app.deployment(
    "api",
    image=API_IMAGE,
    ports=[8080],
    ready=app.probe.http("/healthz", 8080),
    env={"LOG_LEVEL": settings.key("LOG_LEVEL")},
    resources=Resources(cpu="100m", memory="128Mi"),
)
app.service(api, ports=[ServicePort(port=80, target_port=8080, name="http")])
tls = app.resource(
    certificate.API_VERSION,
    certificate.KIND,
    "shop-tls",
    certificate.CertificateSpec(
        secret_name="shop-tls",
        dns_names=["shop.dev.example.com"],
        issuer_ref={"name": "letsencrypt", "kind": "ClusterIssuer"},
    ),
)
monitor = app.resource(
    service_monitor.API_VERSION,
    service_monitor.KIND,
    "api",
    service_monitor.ServiceMonitorSpec(
        selector={"matchLabels": api.selector_labels},
        endpoints=[{"port": "http", "path": "/metrics", "interval": "30s"}],
    ),
    component="monitoring",
)

app.environment("dev", namespace="shop-dev", enabled={"monitoring": False})
app.environment(
    "staging",
    namespace="shop-staging",
    replicas={"api": 2},
    specs={
        "shop-tls": certificate.CertificateSpec(
            secret_name="shop-tls",
            dns_names=["shop.staging.example.com"],
            issuer_ref={"name": "letsencrypt", "kind": "ClusterIssuer"},
        )
    },
)
app.environment(
    "prod",
    namespace="shop-prod",
    replicas={"api": 3},
    resources={"api": Resources(cpu="500m", memory="512Mi", memory_limit="1Gi")},
    config={"settings": {"LOG_LEVEL": "warning"}},
    node_selector={"api": {"node-pool": "general"}},
    specs={
        "shop-tls": {
            "secretName": "shop-tls",
            "dnsNames": ["shop.example.com", "www.shop.example.com"],
            "issuerRef": {"name": "letsencrypt", "kind": "ClusterIssuer"},
        }
    },
)

pipeline = Pipeline(
    app,
    {  # one target per environment; `--env` selects one (with its own state)
        "dev": Target.kubeconfig("dev.kubeconfig", context="dev", namespace="shop-dev"),
        "staging": Target.kubeconfig(
            "cluster.kubeconfig", context="main", namespace="shop-staging"
        ),
        "prod": Target.kubeconfig(
            "cluster.kubeconfig", context="main", namespace="shop-prod"
        ),
    },
)
