import { useState } from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import { Link } from 'react-router-dom';
import type { Operation, PlanRecord } from '../../api/generated';
import { applicationPath } from '../../api/client';
import { Badge, formatTime, Notice } from '../../components/State';

export function RunView({ operation, plan, pending, onResume, onCancel }: { operation: Operation; plan?: PlanRecord; pending: boolean; onResume: () => void; onCancel: () => void }) {
  const [confirm, setConfirm] = useState<'resume' | 'cancel' | null>(null);
  const failedStage = operation.stages?.find(stage => stage.state === 'failed' || stage.state === 'interrupted');
  const capability = confirm ? operation.capabilities?.[confirm] : undefined;
  return <><div className="heading detail-heading"><div><p className="eyebrow">Durable operation</p><h1>Deployment run</h1><p className="subtitle"><code>{operation.id}</code> · Attempt {operation.attempt ?? 1}</p></div><Badge value={operation.state} /></div>
    <div className="context"><span>{operation.trigger.toUpperCase()} · <strong>{operation.actor}</strong></span>{plan && <span>Target <strong>{plan.target.name} / {plan.target.namespace}</strong></span>}<span>Started {formatTime(operation.created_at)}</span><span>Updated {formatTime(operation.updated_at)}</span></div>
    <div className="run-actions">{operation.plan_id && <Link to={`${applicationPath(operation.application_id)}/changes?plan=${encodeURIComponent(operation.plan_id)}`}>View exact plan</Link>}<Link to={`${applicationPath(operation.application_id)}/resources`}>Inspect resources</Link><Link to={`${applicationPath(operation.application_id)}/activity`}>Application activity</Link></div>
    {(operation.state === 'failed' || operation.state === 'interrupted') && <Notice title={operation.state === 'interrupted' ? 'Execution interrupted' : 'Deployment failed'} danger><p>{failedStage ? `First failing stage: ${failedStage.name}. ${failedStage.reason ?? ''}` : 'The operation did not complete successfully.'}</p>{operation.error_code && <p>Reason: <code>{operation.error_code}</code></p>}<p>Completed writes remain in effect. Review the receipts and affected resources before recovery.</p></Notice>}
    {operation.state === 'cancelled' && <Notice title="Operation cancelled">Cancellation stopped further execution at a safe boundary. It did not undo completed changes.</Notice>}
    {operation.state === 'cancelling' && <Notice title="Cancellation requested">The worker will stop at a safe boundary. A request already in flight may still complete.</Notice>}
    <section className="panel"><div className="panelhead"><h2>Execution stages</h2><span className="small muted">Recorded by the deployment engine</span></div><ol className="stage-list">{operation.stages?.map((stage, index) => <li key={`${stage.name}/${index}`}><span className="stage-number" aria-hidden="true">{index + 1}</span><div><strong>{stage.name}</strong>{stage.reason && <p className="small muted">{stage.reason}</p>}</div><Badge value={stage.state} /></li>)}</ol>{!operation.stages?.length && <p className="panelbody muted">No stage evidence has been recorded yet.</p>}</section>
    <section className="panel run-evidence"><div className="panelhead"><h2>Outcomes and evidence</h2></div><div className="panelbody"><dl className="facts"><dt>Deployment outcome</dt><dd><Badge value={operation.deployment_outcome ?? 'unknown'} /></dd><dt>Checks outcome</dt><dd><Badge value={operation.checks_outcome ?? 'unknown'} /></dd><dt>Release</dt><dd>{operation.engine_release ?? 'Not recorded'}</dd><dt>Engine execution</dt><dd><code>{operation.engine_execution_id ?? 'Not recorded'}</code></dd><dt>Approved digest</dt><dd><code>{operation.approved_digest}</code></dd>{operation.recovery_of && <><dt>Recovery of</dt><dd><Link to={`/runs/${encodeURIComponent(operation.recovery_of)}`}>{operation.recovery_of}</Link></dd></>}</dl>
      <details><summary>Receipts ({operation.receipts?.length ?? 0})</summary>{operation.receipts?.length ? <pre aria-label="Execution receipts">{JSON.stringify(operation.receipts, null, 2)}</pre> : <p className="small muted">No receipts recorded. Missing evidence does not imply success.</p>}</details>
    </div></section>
    <section className="panel recovery-panel"><div className="panelhead"><h2>Recovery and control</h2></div><div className="panelbody"><div className="run-actions"><button disabled={!operation.capabilities?.resume?.allowed || pending} onClick={() => setConfirm('resume')}>Resume as a new attempt</button><button disabled={!operation.capabilities?.cancel?.allowed || pending} onClick={() => setConfirm('cancel')}>Cancel operation</button><Link to={`${applicationPath(operation.application_id)}/changes?intent=rollback`}>Review rollback options</Link></div>{!operation.capabilities?.resume?.allowed && <p className="small muted">Resume: {operation.capabilities?.resume?.reason ?? 'Not available for this operation.'}</p>}{!operation.capabilities?.cancel?.allowed && <p className="small muted">Cancel: {operation.capabilities?.cancel?.reason ?? 'Not available for this operation.'}</p>}</div></section>
    <Dialog.Root open={confirm !== null} onOpenChange={open => { if (!open) setConfirm(null); }}><Dialog.Portal><Dialog.Overlay className="dialog-overlay" /><Dialog.Content className="confirm-dialog"><div className="panelhead"><Dialog.Title>{confirm === 'resume' ? 'Resume this exact plan?' : 'Cancel at a safe boundary?'}</Dialog.Title><Dialog.Close aria-label="Close confirmation">✕</Dialog.Close></div><div className="panelbody"><Dialog.Description>{confirm === 'resume' ? 'A new operation attempts the same approved plan using recorded receipts and current state. The previous operation keeps its original outcome.' : 'Cancellation stops further stages when safe. Applied objects and completed changes remain in effect.'}</Dialog.Description><dl className="facts"><dt>Operation</dt><dd><code>{operation.id}</code></dd><dt>Target</dt><dd>{plan ? `${plan.target.name} / ${plan.target.namespace}` : 'See exact plan'}</dd><dt>Approved plan</dt><dd><code>{operation.approved_digest}</code></dd></dl>{!capability?.allowed && <Notice title="Action unavailable">{capability?.reason ?? 'The operation state no longer permits this action.'}</Notice>}</div><div className="review-footer"><Dialog.Close>Keep viewing run</Dialog.Close><button className="primary" disabled={pending || !capability?.allowed} onClick={() => { if (confirm === 'resume') onResume(); else onCancel(); setConfirm(null); }}>{confirm === 'resume' ? 'Approve new attempt' : 'Request cancellation'}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>
  </>;
}
