"""A typed generic object: any kind, custom resources included (``app.resource``).

:class:`Resource` renders one object of any ``apiVersion``/``kind`` whose body
is a typed pydantic model (for a custom resource, one generated by
``piceli codegen crd``, see ``docs/crds.md``) or a plain JSON mapping. A typed
spec is validated when it is constructed, so a wrong value fails at
declaration, like every other ``App`` declaration.

Importing this module has no side effects.
"""

from __future__ import annotations

import json
import re
from collections.abc import Mapping
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from piceli.app.model import Labels, Name
from piceli.k8s.ops.discovery import (
    PUBLIC_FIELDS_ANNOTATION,
)
from piceli.k8s.ops.discovery import (
    RELEASE_REFUSED_CLUSTER_KINDS as REFUSED_CLUSTER_KINDS,
)

#: The two scopes a Kubernetes resource type is served with.
Scope = Literal["namespaced", "cluster"]

_API_VERSION = re.compile(
    r"^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?v[0-9]+"
    r"((alpha|beta)[0-9]+)?$"
)
_KIND = re.compile(r"^[A-Z][A-Za-z0-9]{0,62}$")
_FIELD_PATH = re.compile(r"^[A-Za-z0-9_-]+(\.([A-Za-z0-9_-]+|\*))*$")
_OBJECT_NAME = re.compile(
    r"^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"
)
#: Top-level keys a Resource never takes from ``fields``.
_RESERVED = frozenset({"apiVersion", "kind", "metadata", "spec", "status"})
#: Built-in kinds that are cluster-scoped, so ``scope`` defaults right.
_CLUSTER_KINDS = frozenset(
    {
        "ClusterRole",
        "ClusterRoleBinding",
        "PriorityClass",
        "StorageClass",
        "IngressClass",
        "RuntimeClass",
        "MutatingWebhookConfiguration",
        "ValidatingWebhookConfiguration",
    }
)


def _json(value: Any, what: str) -> Any:
    """``value`` as plain JSON (a fresh copy); refuses anything else."""
    try:
        return json.loads(json.dumps(value, allow_nan=False))
    except (TypeError, ValueError):
        raise ValueError(f"{what} must hold plain JSON values") from None


def spec_json(spec: BaseModel | Mapping[str, Any]) -> dict[str, Any]:
    """The JSON body of a typed or mapping spec.

    A pydantic model dumps by alias (the Kubernetes field names) and keeps only
    the fields that were set and are not ``None``, so server defaults stay the
    server's (Piceli does not claim fields you did not declare).
    """
    if isinstance(spec, BaseModel):
        value = spec.model_dump(
            mode="json", by_alias=True, exclude_unset=True, exclude_none=True
        )
    else:
        value = dict(spec)
    result = _json(value, "a resource spec")
    if not isinstance(result, dict):  # pragma: no cover - dict in, dict out
        raise ValueError("a resource spec must be a mapping")
    return result


def spec_type_metadata(spec: Any) -> tuple[str | None, str | None, str | None]:
    """``(api_version, kind, scope)`` a generated spec class declares, if any."""
    kind = type(spec)
    return (
        getattr(kind, "piceli_api_version", None),
        getattr(kind, "piceli_kind", None),
        getattr(kind, "piceli_scope", None),
    )


class Resource(BaseModel):
    """One object of any kind, declared with ``app.resource(...)``.

    :param api_version: ``group/version`` (``cert-manager.io/v1``) or ``v1``.
    :param kind: The kind (``Certificate``).
    :param name: Object name, a DNS subdomain.
    :param spec: The body under ``spec``: a pydantic model (validated when it
        was built; a model generated by ``piceli codegen crd`` also checks
        that ``api_version`` and ``kind`` are its own) or a JSON mapping.
    :param fields: Other top-level keys, for kinds whose body is not under
        ``spec`` (``{"value": 1000}`` for a PriorityClass). Never
        ``apiVersion``, ``kind``, ``metadata``, ``spec`` or ``status``.
    :param scope: ``namespaced`` (default) or ``cluster``. It defaults to the
        generated spec's scope, or to ``cluster`` for built-in cluster kinds.
        The release checks it against the API server's discovery at plan time.
    :param public: Fields (dotted paths, ``*`` for list items, such as
        ``spec.privateKey``) whose names look sensitive but hold no secret
        material. Plans redact sensitive-looking fields and a release refuses
        to apply a redacted value; references (``secretName``, ``{name,
        key}`` selectors, ``*File`` paths) are recognized without this.
        Rendered as the ``piceli.io/public-fields`` annotation.
    :param labels: Extra labels, over the app's labels.
    :param annotations: Annotations.
    :param component: Deployment component; defaults to ``name``.

    Cluster-scoped objects follow the ownership rules of the app's
    ClusterRoles: they render without a namespace and annotated
    ``piceli.io/namespace: <release namespace>``, so only the release in that
    namespace manages, changes or prunes them, and an object of the same
    name managed from another namespace must be adopted explicitly. Namespace,
    CustomResourceDefinition and PersistentVolume are refused: install
    operators and their CRDs, and create namespaces, outside the app.
    """

    model_config = ConfigDict(extra="forbid", frozen=True, arbitrary_types_allowed=True)

    api_version: str
    kind: str
    name: str = Field(min_length=1, max_length=253)
    #: A pydantic model or a JSON mapping (checked by ``_spec``).
    spec: Any = None
    fields: dict[str, Any] = Field(default_factory=dict)
    scope: Scope = "namespaced"
    public: tuple[str, ...] = ()
    labels: Labels = Field(default_factory=dict)
    annotations: dict[str, str] = Field(default_factory=dict)
    component: Name | None = None

    @field_validator("spec", mode="before")
    @classmethod
    def _spec(cls, value: Any) -> Any:
        if value is None or isinstance(value, BaseModel):
            return value
        if isinstance(value, Mapping):
            return _json(dict(value), "a resource spec")
        raise ValueError("spec must be a pydantic model or a mapping")

    @model_validator(mode="before")
    @classmethod
    def _default_scope(cls, data: Any) -> Any:
        if not isinstance(data, dict) or data.get("scope") is not None:
            return data
        declared = spec_type_metadata(data.get("spec"))[2]
        if declared is not None:
            scope = declared
        elif data.get("kind") in _CLUSTER_KINDS:
            scope = "cluster"
        else:
            scope = "namespaced"
        return {**data, "scope": scope}

    @model_validator(mode="after")
    def _shape(self) -> Resource:
        if not _API_VERSION.fullmatch(self.api_version):
            raise ValueError(
                f"api_version {self.api_version!r} must be 'group/version' or 'v1'"
            )
        if not _KIND.fullmatch(self.kind):
            raise ValueError(f"kind {self.kind!r} must be a CamelCase kind name")
        if not _OBJECT_NAME.fullmatch(self.name):
            raise ValueError(f"name {self.name!r} must be a DNS subdomain")
        api_version, kind, scope = spec_type_metadata(self.spec)
        if api_version is not None and api_version != self.api_version:
            raise ValueError(
                f"the spec is a {type(self.spec).__name__} of {api_version}, not "
                f"{self.api_version}"
            )
        if kind is not None and kind != self.kind:
            raise ValueError(
                f"the spec is a {type(self.spec).__name__} of kind {kind}, not "
                f"{self.kind}"
            )
        if scope is not None and scope != self.scope:
            raise ValueError(
                f"{self.kind} is {scope}-scoped (from its CRD), not {self.scope}"
            )
        for path in self.public:
            if not _FIELD_PATH.fullmatch(path):
                raise ValueError(
                    f"public field {path!r} must be a dotted path such as "
                    "'spec.privateKey' ('*' for list items)"
                )
        if PUBLIC_FIELDS_ANNOTATION in self.annotations:
            raise ValueError("declare public fields with public=, not annotations")
        reserved = sorted(_RESERVED & set(self.fields))
        if reserved:
            raise ValueError(f"fields cannot set {reserved}")
        _json(self.fields, "resource fields")
        _json(self.annotations, "resource annotations")
        if self.scope == "cluster" and self.kind in REFUSED_CLUSTER_KINDS:
            raise ValueError(
                f"an app never manages a {self.kind}: it belongs to the cluster's "
                "administration, not to one release"
            )
        return self

    @property
    def component_name(self) -> str:
        return self.component or self.name

    @property
    def cluster_scoped(self) -> bool:
        return self.scope == "cluster"

    def spec_json(self) -> dict[str, Any] | None:
        """The rendered ``spec`` (see :func:`spec_json`)."""
        return None if self.spec is None else spec_json(self.spec)

    def manifest(
        self,
        namespace: str,
        app_labels: Mapping[str, str],
        namespace_annotation: str,
    ) -> dict[str, Any]:
        """The object; a cluster-scoped one names ``namespace`` in an annotation."""
        labels = {**app_labels, **self.labels}
        annotations = dict(self.annotations)
        metadata: dict[str, Any] = {"name": self.name}
        if self.cluster_scoped:
            declared = annotations.get(namespace_annotation)
            if declared is not None and declared != namespace:
                raise ValueError(
                    f"{self.kind}/{self.name} is annotated {namespace_annotation}="
                    f"{declared!r}, but it renders for namespace {namespace!r}"
                )
            annotations[namespace_annotation] = namespace
        else:
            metadata["namespace"] = namespace
        if self.public:
            annotations[PUBLIC_FIELDS_ANNOTATION] = ",".join(sorted(set(self.public)))
        if labels:
            metadata["labels"] = labels
        if annotations:
            metadata["annotations"] = annotations
        manifest: dict[str, Any] = {
            "apiVersion": self.api_version,
            "kind": self.kind,
            "metadata": metadata,
            **_json(self.fields, "resource fields"),
        }
        spec = self.spec_json()
        if spec is not None:
            manifest["spec"] = spec
        return manifest
